### ISSUE TITLE
FC_API_Android-1 P-4

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tools-issues#149]
UAF v1.1
Client tests
Tool Version 0.9.3

## Issue description

AssertionError: MetadataStatement.userVerificationDetails MUST contain AuthenticatorInfo.userVerification!: expected false to be true

From the FIDO UAF Protocol Specification:
"If MetadataStatement.userVerificationDetails contains multiple entries and all entries MetadataStatement.userVerificationDetails[i] only contain a single entry, then combine all entries into a single value using a bitwise OR operation."

This test case checks the existence of the AuthenticatorInfo.userVerification in the MetadataStatement.userVerificationDetails list and fails in case of multiple entries.

For example in our particular test-case userVerification is 3 (combination of 1 and 2), and this test-case fails, when trying to check the existence of 3 in the list of [1, 2].

**Comment by herrjemand** [comment]
@armenabgaryan Good one. Thanks

**Comment by herrjemand** [comment]
@armenabgaryan Could you email me your metadata?

**Comment by herrjemand** [comment]
@armenabgaryan Awaiting TWG discussion https://github.com/fido-alliance/uaf-specs/issues/621

**Comment by herrjemand** [comment]
So per discussion with CWG: The value of the userVerification must be the bit flag combination of one of the OR userVerificationDescription. 

Consider this example:

```
[
    [ //OR
        {"userVerification": 2}, // AND
        {"userVerification": 4}  // AND
    ],
    [ // OR
        {"userVerification": 1}
    ]
]
```

The value of the userVerification can be either the combination of  {"userVerification": 2} + {"userVerification": 4}, so 0x06 or {"userVerification": 1} so 0x01

**Comment by herrjemand** [comment]
This change will be added to v0.9.7

**Comment by herrjemand** [comment]
Resolved. v0.9.7 should be out in few hours
