### ISSUE TITLE
Authr-MakeCred-Req-2 : missing optional parameters should not mark test as failed

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#153]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
v0.9.412

## Issue description

1. Missing optional "rp.name" parameter should not trigger an error on the authenticator side.
2. Maybe I've missed it, but it's not saying anywhere in the spec that an optional parameter, like "rp.icon", can not be empty. So, why expecting an error in this case?

**Comment by herrjemand** [comment]
Resovled in v0.9.417
