### ISSUE TITLE
Authr-MakeCred-Req-3 : missing optional parameters should not mark test as failed

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#154]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.412

## Issue description
Sending a command with missing optional parameters (user.name and user.displayName) should not trigger an error on the authenticator side.

**Comment by herrjemand** [comment]
Resolved in v0.9.417
