### ISSUE TITLE
Authr-MakeCred-Req-6 : f1Test is not a function

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#155]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## Issue description

TypeError: f1Test is not a function
    at sendCTAP2HIDCommand.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:2268:25)

**Comment by herrjemand** [comment]
Resolved in version 0.9.416
