### ISSUE TITLE
CTAP2HID arbitration mismatch between test and spec

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#158]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Authenticator

## What is the version of the tool are you using?
0.9.413

## Issue description

CTAP2HID P-9 test is not in sync with the latest spec. Sending CTAP2HID_INIT on CID2 while waiting for the continuation frame of the previous CTAP2HID_PING command on CID1, should generate a CTAPHID_ERROR on CID2. Please see 8.1.5.1 chapter from the spec.

**Comment by herrjemand** [comment]
This test was removed. Thanks @eugenIFX *)
