### ISSUE TITLE
Test tool is crashing on CTAPHID error

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#159]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?
0.9.413

## Issue description

The application is crashing when executing F-1 test. Another comment is that BCNT should not be 0, as expected in the test (you have to get BCNT=1 and 1 byte of data).

![capture](https://user-images.githubusercontent.com/29768798/38024265-008f8dfc-3274-11e8-97dd-3300f30be722.PNG)

**Comment by herrjemand** [comment]
@eugenIFX The tool was crashing because of HID issues with Electron. It was moved to a separate process and resolved in v0.9.415.(It's uploading right now)

Sorry for that.

**Comment by eugenIFX** [comment]
thanks, @herrjemand . I will try it and let you know what's happening

**Comment by herrjemand** [comment]
@eugenIFX v0.9.416 will have additional fixes regarding this issue.
