### ISSUE TITLE
Authr-MakeCred-Req-4 F-4 is incorrect.

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#160]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

0.9.413

## Issue description

Authr-MakeCred-Req-4 F-4 changes the type of 1 of 2 credential parameters from public-key to a random word and expects the authenticator to fail because of it. This is incorrect: type is an extension point and future FIDO2 versions may support other types. The authenticator must ignore this credential parameter entry. Because there are 2 credential parameters, the correct result of the current test is success or CTAP2_ERR_UNSUPPORTED_ALGORITHM (if the remaining credential parameter is not supported).

The test should use only 1 credential parameter, change the type to RandomWord() and expect CTAP2_ERR_UNSUPPORTED_ALGORITHM.

**Comment by herrjemand** [comment]
Moving to positive test

**Comment by herrjemand** [comment]
Resolved in v0.9.417
