### ISSUE TITLE
User-presence timeout behavior

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#161]
## What protocol and version of the protocol are you testing?

CTAP2

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?

0.9.413

## Issue description

The tool times out while waiting for user presence, it should not time out while authenticator is still sending keep-alives/status messages or at least have a very long timeout. If the tool decides to time out anyway, it should send a cancel.

**Comment by herrjemand** [comment]
Set timeout to 30s. Resolved in v0.9.417

**Comment by jovasco** [comment]
And you send a cancel command if you time out? If not, the authenticator may use a different timeout and return BUSY on your next test.
