### ISSUE TITLE
Authr-GetAssertion-Resp-1 P-1: credential is optional and MAY be returned

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#162]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?

v0.9.413

## Issue description

The test does not allow the "credential" parameter to be returned. This MAY be omitted if allowList only has 1 credential but this is not mandatory. Parameter should be accepted if present.

**Comment by herrjemand** [comment]
@jovasco Jup. Sorry. Resolved in v0.9.416
