### ISSUE TITLE
Authr-GetAssertion-Resp-1 P-1: user is optional and MAY be returned

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#163]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?

v0.9.413

## Issue description

the test does not want to see a user parameter but this parameter is only forbidden if no user-presence is asked for: otherwise this parameter is optional, not forbidden.

**Comment by herrjemand** [comment]
Resolved in v0.9.416
