### ISSUE TITLE
Authr-GetAssertion-Resp-1 P-1: incorrect fail when optional parameters are present

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#165]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.413

## Issue description
Why the test expects the response must not include "user", "credential" and "numberOfCredentials" and asserts a fail? They are optional parameters and they can be included in the authenticator response.

**Comment by herrjemand** [comment]
Ref #162 Resolved in v0.9.416
