### ISSUE TITLE
rp.name, rp.icon, user.name, user.displayName, user.icon TYPE is not mentioned in the spec

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#166]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.413

## Issue description
rp.name, rp.icon, user.name, user.displayName, user.icon TYPE is not mentioned in the spec, they can be any "human-friendly" thing. Please see tests from Authr-MakeCred-Req-2 F-3, F-4 and Authr-MakeCred-Req-3 F-4, F-6, F-7.

**Comment by herrjemand** [comment]
@eugenIFX The type must be String. Defined in WebAuthn specs https://w3c.github.io/webauthn/#dictionary-pkcredentialentity

**Comment by eugenIFX** [comment]
I can't find anywhere in the CTAP2 spec a reference to WebAuthn for these fields inside makeCredential and getAssertion commands.
