### ISSUE TITLE
HID F-1: wrong BCNT value in test description

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#167]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.415

## Issue description
HID F-1: in the test description, BCNT is expected to be 0 (wrong value), but in the code is compared with 1. This can lead to a misunderstanding of the test.

**Comment by herrjemand** [comment]
Thank @eugenIFX. Resolved in v0.9.416

**Comment by valentinstoia** [comment]
There may be a slight confusion here:
- initially, test spec was wrong, however code was correct
- after modifications - in 0.9.416 - both spec and code are wrong, assuming these CTAPHID specifications are valid:
![ctaphid_error](https://user-images.githubusercontent.com/21098217/38365135-d2da5574-38e3-11e8-94cf-a605ec8d6319.JPG)

This is what we received when running 0.9.416:
![ctaphid-f-1](https://user-images.githubusercontent.com/21098217/38365157-f04d7c3a-38e3-11e8-9c18-64b8c0b39259.JPG)
Both spec and code shoud expect BCNT as 1, not 0.
Please correct me if I'm wrong.
Thanks!
