### ISSUE TITLE
HID tests : update CTAP2HID_ERROR_CODES

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#168]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.415

## Issue description
I think CTAP2HID_ERROR_CODES from hid-1.js needs to be updated with the new values from HID-Tools.js

**Comment by herrjemand** [comment]
@eugenIFX What do you mean?

**Comment by eugenIFX** [comment]
Inside hid-1.js you are trying to use CTAP2HID_ERROR_CODES defined in HID-Tools.js, but, for example, on F-1 test, there is no CTAP2HID_ERROR_CODES.ERR_INVALID_CMD defined anywhere. I think you renamed the error code to CTAP1_ERR_INVALID_COMMAND. Same for ERR_INVALID_CID, ERR_INVALID_SEQ and ERR_CHANNEL_BUSY.

**Comment by herrjemand** [comment]
@eugenIFX Oh yes, you are right.

**Comment by herrjemand** [comment]
@eugenIFX Resolved in v0.9.416
