### ISSUE TITLE
Self Conformance tool Issue in IOS

### ISSUE THREAD

**Issue by silverstar235** [fido-alliance/conformance-tools-issues#170]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client/ASM+Authr combo

## What is the version of the tool are you using?
9.10

## Issue description
The self conformance tool doesn't run normally in IOS, "Before all" hook and time out errors are appear in many times.
![img_0123](https://user-images.githubusercontent.com/19985766/38285878-7aee89e0-37ec-11e8-88db-c27c5f9dec3a.PNG)

**Comment by herrjemand** [comment]
Unable to reproduce

**Comment by herrjemand** [comment]
Increased timeout to 30s
