### ISSUE TITLE
HID F-1: expect wrong BCNT value

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#175]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.416

## Issue description
Test description and test implementation expect now BCNT to be 0. The correct value of the BCNT should be 1, not 0. Please change the value inside test description and source code.

**Comment by herrjemand** [comment]
Resolved in v0.9.417
