### ISSUE TITLE
Authr-MakeCred-Req-2 F-3, F-4, Authr-MakeCred-Req-3 F-4, F-6, F-7 : No reference to WebAuthn specs for rp and user type

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#176]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.416

## Issue description
I know there is a common sense for rp and user sub-fields to be String, but there is no reference inside the FIDO2 spec to WebAuthn for these 2 parameters when describing authenticatorMakeCredential command.

**Comment by herrjemand** [comment]
@eugenIFX https://drafts.fidoalliance.org/fido-2/latest/fido-client-to-authenticator-protocol-v2.0-wd-20180305.html#authenticatorMakeCredential

> This PublicKeyCredentialRpEntity data structure describes a Relying Party with which the new public key credential will be associated. It contains the Relying party identifier, (optionally) a human-friendly RP name, and (optionally) a URL referencing a RP icon image. The RP name is to be used by the authenticator when displaying the credential to the user for selection and usage authorization.

> A sequence of PublicKeyCredentialDescriptor structures, as specified in  [**WebAuthN**]. The authenticator returns an error if the authenticator already contains one of the credentials enumerated in this sequence. This allows RPs to limit the creation of multiple credentials for the same account on a single authenticator.

They are defined in webauthn

**Comment by eugenIFX** [comment]
@herrjemand the reference to the WebAuthN specs is inside excludeList parameter, not inside rp (PublicKeyCredentialRpEntity) or user (PublicKeyCredentialUserEntity) description.

**PublicKeyCredentialRpEntity**: "This PublicKeyCredentialRpEntity data structure describes a Relying Party with which the new public key credential will be associated. It contains the Relying party identifier, (optionally) a human-friendly RP name, and (optionally) a URL referencing a RP icon image. The RP name is to be used by the authenticator when displaying the credential to the user for selection and usage authorization."

**PublicKeyCredentialUserEntity**: "This PublicKeyCredentialUserEntity data structure describes the user account to which the new public key credential will be associated at the RP. It contains an RP-specific user account identifier, (optionally) a user name, (optionally) a user display name, and (optionally) a URL referencing a user icon image (of a user avatar, for example). The authenticator associates the created public key credential with the account identifier, and MAY also associate any or all of the user name, user display name, and image data (pointed to by the URL, if any)."

**Comment by herrjemand** [comment]
PublicKeyCredentialRpEntity and PublicKeyCredentialUserEntity are both only defined in WebAuthn. The fact that they miss  [WebAuthN] tag, does not mean that they are not governed by those IDLs. 

Currently the only thing that is optional is their presence, and not their type. If their type does not match IDL then authenticator must fail with an error.

cc @jovasco

**Comment by jovasco** [comment]
I would agree with @herrjemand here although I admit this should be clarified in the spec if so. Perhaps create a spec issue?

**Comment by herrjemand** [comment]
@jovasco Yes, that would be good idea.

**Comment by eugenIFX** [comment]
@jovasco , @herrjemand I've created a spec issue right here https://github.com/fido-alliance/fido-2-specs/issues/507 . I totally agree with you.

**Comment by herrjemand** [comment]
I was just going to do that! Thanks @eugenIFX!

**Comment by herrjemand** [comment]
Closing

**Comment by andreasWallnerIFX** [comment]
@herrjemand While I agree with the change discussed here I **strongly** disagree with the notion that we are in any way governed by the IDL in the WebAuthn specification where we do not refer to said specification.

**Comment by herrjemand** [comment]
If it is not governed by webauthn, then it needs to be redefined in ctap

ср, 11 апр. 2018 г., 11:40 Andreas Wallner <notifications@github.com>:

**Comment by andreasWallnerIFX** [comment]
@herrjemand agreed
