### ISSUE TITLE
Positive test does not include tokenBinding status.

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#177]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
0.9.416

## Issue description
Positive test does not include tokenBinding status.

It is about the following test
https://github.com/fido-alliance/fido2-conformance-module/blob/master/tests/server/PublicKeyCredentialCreation/Server-ServerAuthenticatorAttestationResponse-Resp-1.js#L21-L52

**Comment by herrjemand** [comment]
@hueno-ttic I am not sure what do you mean?

**Comment by hueno-ttic** [comment]
@herrjemand 
In positive test, I think that the state of tokenBinding must be included in ClientData sent to the server?
https://www.w3.org/TR/webauthn/#sec-client-data

**Comment by herrjemand** [comment]
@hueno-ttic TokenBinding is an optional field.

**Comment by herrjemand** [comment]
```
dictionary CollectedClientData {
    required DOMString           type;
    required DOMString           challenge;
    required DOMString           origin;
    TokenBinding                 tokenBinding;
};
```
