### ISSUE TITLE
HID P-9 does not finish the test and fails with Sequence out of order!

### ISSUE THREAD

**Issue by herrjemand** [fido-alliance/conformance-tools-issues#180]
Test started: P-9

 

        Send a valid MakeCredential request, and while its waiting for user action check that authenticator returns CTAPHID_KEEPALIVE(0x3B), that is 8 byte long, BCNT is 1 and DATA is either STATUS_PROCESSING(0x01) or STATUS_UPNEEDED(0x02)

 

   

./nodehid-webrenderer.js:27 DATA SENT: ffffffff860008375ca71a923c4f7300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

./nodehid-webrenderer.js:32 DATA RECEIVED: ffffffff860011375ca71a923c4f7366a45e6b023e0c000c00000000000000000000000000000000000000000000000000000000000000000000000000000000

 

controller.js:292 Test started: P-9

 

        Send a valid MakeCredential request, and while its waiting for user action check that authenticator returns CTAPHID_KEEPALIVE(0x3B), that is 8 byte long, BCNT is 1 and DATA is either STATUS_PROCESSING(0x01) or STATUS_UPNEEDED(0x02)

 

   

./nodehid-webrenderer.js:27 DATA SENT: ffffffff8600084f7268e2aee0cc1e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

./nodehid-webrenderer.js:32 DATA RECEIVED: ffffffff8600114f7268e2aee0cc1e67a45e6b023e0c000c00000000000000000000000000000000000000000000000000000000000000000000000000000000

66a45e6bbb0001020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

controller.js:292 Test started: P-9

 

        Send a valid MakeCredential request, and while its waiting for user action check that authenticator returns CTAPHID_KEEPALIVE(0x3B), that is 8 byte long, BCNT is 1 and DATA is either STATUS_PROCESSING(0x01) or STATUS_UPNEEDED(0x02)

 

   

./nodehid-webrenderer.js:27 DATA SENT: ffffffff86000802d73a87dd2c3a3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

./nodehid-webrenderer.js:32 DATA RECEIVED: ffffffff86001102d73a87dd2c3a3068a45e6b023e0c000c00000000000000000000000000000000000000000000000000000000000000000000000000000000

66a45e6bbb0001020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

controller.js:292 Test started: P-9

 

        Send a valid MakeCredential request, and while its waiting for user action check that authenticator returns CTAPHID_KEEPALIVE(0x3B), that is 8 byte long, BCNT is 1 and DATA is either STATUS_PROCESSING(0x01) or STATUS_UPNEEDED(0x02)

 

   

./nodehid-webrenderer.js:27 DATA SENT: ffffffff8600088be077ed130e241b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

 

./nodehid-webrenderer.js:32 DATA RECEIVED: ffffffff8600118be077ed130e241b69a45e6b023e0c000c00000000000000000000000000000000000000000000000000000000000000000000000000000000

66a45e6bbb0001020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by herrjemand** [comment]
cc @jovasco

**Comment by jovasco** [comment]
It fails with:

Error: Sequence out of order!
    at processResponseBuffers (eval at compileCode (js/sandbox.js:25:26), <anonymous>:324:19)
    at window.navigator.fido.ctap2conformancetest.sendHIDBuffer.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:348:20)
    at <anonymous>

**Comment by herrjemand** [comment]
Thanks @jovasco *)

**Comment by herrjemand** [comment]
Fixed typoe that cause an issue.
