### ISSUE TITLE
HID Test F-1: BCNT should be 1

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#181]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.416

## What is the OS and the version are you running?
Win10

## Issue description
the test expects an error with BCNT == 0. It should be 1, the content is correctly checked though.

**Comment by herrjemand** [comment]
Duplicate of #175. Resolved in v0.9.417
