### ISSUE TITLE
Conformance-tools support IOS<10

### ISSUE THREAD

**Issue by tamdq** [fido-alliance/conformance-tools-issues#182]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAF v1.0/v1.1

## Issue description
Current, Conformance-tools only support iOS>10. Please reduce version support for ios <10

**Comment by herrjemand** [comment]
Sorry, but Apple has discontinued support of iOS9, and so we are unable to
provide you with the build supporting this version of the iOS. Additionally
our tool was designed for versions 10+. Please update you device

ср, 11 апр. 2018 г., 11:47 tamdq <notifications@github.com>:
