### ISSUE TITLE
Authr-MakeCred-Req-4 P-1

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#183]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

0.9.417

## What is the OS and the version are you running?
Win10

## Issue description

This test creates a single PublicKeyCredentialParameter with type not set to a random word and expects SUCCESS. This is incorrect: since this is the only parameter and it can't be supported, it should return CTAP2_ERR_UNSUPPORTED_ALGORITHM

See also #160 .

**Comment by herrjemand** [comment]
@jovasco Yes, you are correct. Moved to F-7
