### ISSUE TITLE
the way to make rpidhash is different from ctapauthenticator.js and u2fauthenticator.js

### ISSUE THREAD

**Issue by hwpark10** [fido-alliance/conformance-tools-issues#190]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.9.417
## Issue description

in ctapauthenticator.js
this.rpIDHashBuffer    = window.navigator.fido.ctap2conformancetest.crypto.hash('sha256', breakURL(this.origin).host);

in u2fauthenticator.js 
let rpIDHashBuffer   = window.navigator.fido.ctap2conformancetest.crypto.hash('sha256', this.origin);

**Comment by herrjemand** [comment]
Thanks @hwpark10. This will be fixed in v0.9.418
