### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-7.js 

### ISSUE THREAD

**Issue by hwpark10** [fido-alliance/conformance-tools-issues#191]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.9.417
## Issue description

I think , NEGATIVE test case should check the response with expectPromiseToFail(sendAttestationResponse)

but , F1/F2 test case uses sendAttestationResponse(response) 

    it(`F-1

        Send ServerAuthenticatorAttestationResponse with "fido-u2f" attestation, authData.AAGUID is not 0x00, and check that server returns an error

    `, () => {
        let username       = generateRandomString();
        let displayName    = generateRandomName();
        return getMakeCredentialsChallenge({'displayName': displayName, 'username':username, 'attestation': 'none'})
            .then((response) => {
                return webauthnClient.createCredential(response, {'aaguidNot00': true})
            })
            .then((response) => {
                 **return sendAttestationResponse(response)**
            })
    })

**Comment by herrjemand** [comment]
Yes, you are correct. And I had copy pasted the description. Thanks @hwpark10

**Comment by herrjemand** [comment]
Resolved in v0.9.418
