### ISSUE TITLE
"none attestation" cannot be sent on conformance tool

### ISSUE THREAD

**Issue by hwpark10** [fido-alliance/conformance-tools-issues#192]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.417

## Issue description

I think Server-ServerAuthenticatorAttestationResponse-Resp-6 is test case for none attestation .

But the tool checks a validate as following  before send to server and  it shows "none  is not supported attestation format!'

webauthclient.js

    let validateAttestationFormat = (attestationFormat) => {
        let allowedFormats = ['packed', 'tpm', 'fido-u2f', 'android'];

        if(allowedFormats.indexOf(attestationFormat) === -1)
            throw new Error('"' + attestationFormat + '" is not supported attestation format!');

**Comment by herrjemand** [comment]
Yes, you are right. Thanks for that @hwpark10 I will add fix in the next release

Regards. Yuriy!
