### ISSUE TITLE
attestationCertificateKeyIdentifiers in U2FSecp256k1.metadata.json 

### ISSUE THREAD

**Issue by hwpark10** [fido-alliance/conformance-tools-issues#196]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.417

## Issue description

attestationCertificateKeyIdentifiers is defined as "57A041960038EED4969F900786D7BCF0962E1C5F" in U2FSecp256k1.metadata.json 

I think , attestationCertificateKeyIdentifiers should be subjectIdentifier of attestation certificate.

subjectIdentifier value of attestation certificate in u2fauthentifcator.js is  564DF7C0F8C655B6A11F6C4D19F3BF41E2FD0179

**Comment by herrjemand** [comment]
Jup,  you are correct @hwpark10 

Thanks for that. Resolved in v0.9.418
