### ISSUE TITLE
Authr-MakeCred-Req-2 F-4: incorrect fail when rp.icon is an empty TEXT

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#197]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
rp.icon is an optional sub-field for RP. Therefore, if it's missing should not trigger a fail. Please modify the test not to expect a fail for this test case.

**Comment by herrjemand** [comment]
@eugenIFX Thanks for that. Resolved in v0.9.418
