### ISSUE TITLE
Authr-MakeCred-Req-6 : "before all" hook

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#198]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Please find attached the error.

![error](https://user-images.githubusercontent.com/29768798/38811709-ebb0b8c4-4192-11e8-8822-86ccaa842f64.PNG)

**Comment by herrjemand** [comment]
Dublicate of #184. Resolved in v0.9.418
