### ISSUE TITLE
F-2 Testcase  in   Server-ServerAuthenticatorAttestationResponse-Resp-5 

### ISSUE THREAD

**Issue by hwpark10** [fido-alliance/conformance-tools-issues#199]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.417

## Issue description

signatureBaseBuffer variable is undefiend in following block in ctap2authenticator.js

                    if(modifiers.attStmtFullAttestation)
                   		attStmt = this.generatePackedFullAttestation(signatureBaseBuffer);
     		   

the Tool shows error message "error while creating credential  data arugment is missing" before it sends response to server. 

I think , it should be like following

                   if(modifiers.attStmtFullAttestation)
                    {            attStmt = this.generatePackedFullAttestation(mergeArrayBuffers(authData, clientDataHash));
     		   }

**Comment by herrjemand** [comment]
Thanks @hwpark10. I have added fix to v0.9.418
