### ISSUE TITLE
Error ConformanceTool IOS Auth

### ISSUE THREAD

**Issue by tamdq** [fido-alliance/conformance-tools-issues#200]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
v1.1

## What is your implementation class?
Client/ASM+Authr

## What is the version of the tool are you using?
v0.9.12

## What is the OS and the version are you running?
10.2

## Issue description

![img_9356](https://user-images.githubusercontent.com/38279411/38865955-a12057f6-4269-11e8-8e00-ed6dc02b4ba8.PNG)
Can not process test Authentication (Other case process OK).

**Comment by herrjemand** [comment]
@tamdq Can you run Client+Authr  tests instead.

**Comment by tamdq** [comment]
Dear herrjemand,

Thank for your response. But I do not understand what your mean. Because, with ConformanceTool version 0.9.4, I can test with test case Authentication, But the version 0.9.12 through this error.

Thank you very much!

**Comment by tamdq** [comment]
Dear herrjemand,

I am test on iOS: 10.2 (14C92).

Thanks!

**Comment by herrjemand** [comment]
@tamdq Okay, I have detected a bug. TextEncoder is not supported by webkit mobile. The fix is added in v0.9.13

**Comment by herrjemand** [comment]
The build will be up in an hour

**Comment by herrjemand** [comment]
Thanks for that @tamdq!
