### ISSUE TITLE
HID-1 P-11 : result[0].slice is not a function

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#201]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Please see the attached screenshot.

![hid_error](https://user-images.githubusercontent.com/29768798/38928556-e0c219a0-4311-11e8-8734-77abd9589152.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.419. Thanks @eugenIFX
