### ISSUE TITLE
HID-1 F-5 : incorrect expected error code for packet sequencing

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#202]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
According to the spec, 8.1.5.4 section, a spurious continuation frame will be ignored by the authenticator. Therefore, a CTAP1_ERR_TIMEOUT will be received by the host and not CTAP1_ERR_CHANNEL_BUSY.

**Comment by herrjemand** [comment]
Thanks @eugenIFX. This test was removed entirely.
