### ISSUE TITLE
HID-1 F-3 : CTAPHID command missing from the output data

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#203]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
CTAPHID_PING command (0x81) is missing after CID in the output data. Please see attached screenshot.

![error](https://user-images.githubusercontent.com/29768798/38931281-456ae464-431b-11e8-94cd-ceacf909cdd4.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.417
