### ISSUE TITLE
HID-1 F-2 : CTAPHID command missing from the output data

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#204]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
CTAPHID_INIT command (0x86) is missing after CID in the output data. Please see attached screenshot.

![error](https://user-images.githubusercontent.com/29768798/38931514-1e83fdb2-431c-11e8-8c97-adcf47e23f45.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.419
