### ISSUE TITLE
UAFv1.1 Registration tests on IOS - ConformanceTool v0.9.14

### ISSUE THREAD

**Issue by tamdq** [fido-alliance/conformance-tools-issues#207]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAFv1.1

## What is your implementation class?

Client+Authr

## What is the version of the tool are you using?
v0.9.14

## What is the OS and the version are you running?
IOS 10.2 (14C92)

## Issue description
Protocol-Reg-Resp-3 P-2: Failed when check TAG_FINAL_CHALLENGE_HASH
![image](https://user-images.githubusercontent.com/38279411/39029789-dd1fc244-4487-11e8-8063-f6d83f2900df.png)
Request: \{\
  "uafProtocolMessage" : "[\{\\"header\\":\{\\"upv\\":\{\\"major\\":1,\\"minor\\":1\},\\"op\\":\\"Reg\\",\\"appID\\":\\"\\"\},\\"challenge\\":\\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\\",\\"username\\":\\"hello@test.com\\",\\"policy\\":\{\\"accepted\\":[[\{\\"aaid\\":[\\"0057#0001\\"]\}]]\}\}]"\
\}\
Response: \{"message":"\{\\"additionalData\\":\{\},\\"uafProtocolMessage\\":\\"[\{\\\\\\"fcParams\\\\\\":\\\\\\"eyJhcHBJRCI6Im9yZy5maWRvYWxsaWFuY2UubW9iaWxlLmNvbmZvcm1hbmNldG9vbHMiLCJjaGFubmVsQmluZGluZyI6e30sImZhY2V0SUQiOiJvcmcuZmlkb2FsbGlhbmNlLm1vYmlsZS5jb25mb3JtYW5jZXRvb2xzIiwiY2hhbGxlbmdlIjoiSDlpVzl5QTlhQVhGX2xlbFFvaV9EaFVrNTE0QWQ4VHF2MHpDbkNxS0RwbyJ9\\\\\\",\\\\\\"assertions\\\\\\":[\{\\\\\\"assertionScheme\\\\\\":\\\\\\"UAFV1TLV\\\\\\",\\\\\\"assertion\\\\\\":\\\\\\"AT4DAQM-sQALLgkAMDA1NyMwMDAxDi4HAAEAAQIAAAEKLiAALXyhdHvwOyYXQksAlNis11rQwPtL_Fyka483C8xGM0EJLiAA_b6H7BE2etQgPFYpCKusETXcoZz8wn9UcCEk2c2WRl0NLggAAAAAAAAAAAAMLkEABDvP5C0Mb2mJSaZjdXJQCxj5OQt4Y-XJ8ga4fE3J8f6RrbuueTdl6dl1jKZ5qUt10a8g_0lCPfl3NF-YlFp-YGEIPkoABi5GADBEAiBBS24uN7pVux1-d0cykIeM4wCq_ZcqyA0XNMRwMAeO_wIgCpImUCKkHP_mbPhWXVQ-xgLwO9KjgMhJItAvlDulk2c\\\\\\"\}],\\\\\\"header\\\\\\":\{\\\\\\"op\\\\\\":\\\\\\"Reg\\\\\\",\\\\\\"appID\\\\\\":\\\\\\"\\\\\\",\\\\\\"upv\\\\\\":\{\\\\\\"major\\\\\\":1,\\\\\\"minor\\\\\\":1\}\}\}]\\"\}","errorCode":0\}\

For this request:
TAG_FINAL_CHALLENGE_HASH have value (Hex String): 2D7CA1747BF03B2617424B0094D8ACD75AD0C0FB4BFC5CA46B8F370BCC463341

But ConformanceTool expect other value.
Please help me check where I wrong!
Thank you very much!

**Comment by herrjemand** [comment]
@tamdq That is correct. Because it's a hash of FCP buffer, not a string. Decode base64url to buffer, and then take a hash of that.
