### ISSUE TITLE
UAFv1.1 Protocol-Reg-Resp-3 P-2 - ConformanceTool v0.9.14

### ISSUE THREAD

**Issue by tamdq** [fido-alliance/conformance-tools-issues#209]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAFv1.1

## What is your implementation class?

Client+Authr

## What is the version of the tool are you using?
v0.9.14

## What is the OS and the version are you running?
IOS 10.2 (14C92)

## Issue description
Issue 1:
ConformanceTool check and report error HASH:
![image](https://user-images.githubusercontent.com/38279411/39047909-d6760d8e-44c5-11e8-9a27-9d6eb3b9e6e5.png)

Request: json: \{\
  "uafProtocolMessage" : "[\{\\"header\\":\{\\"upv\\":\{\\"major\\":1,\\"minor\\":1\},\\"op\\":\\"Reg\\",\\"appID\\":\\"\\"\},\\"challenge\\":\\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\\",\\"username\\":\\"hello@test.com\\",\\"policy\\":\{\\"accepted\\":[[\{\\"aaid\\":[\\"0057#0001\\"]\}]]\}\}]"\
\}\
Response: \{"additionalData":\{\},"uafProtocolMessage":"[\{\\"fcParams\\":\\"eyJhcHBJRCI6ImlvczpidW5kbGUtaWQ6b3JnLmZpZG9hbGxpYW5jZS5tb2JpbGUuY29uZm9ybWFuY2V0b29scyIsImNoYW5uZWxCaW5kaW5nIjp7fSwiZmFjZXRJRCI6ImlvczpidW5kbGUtaWQ6b3JnLmZpZG9hbGxpYW5jZS5tb2JpbGUuY29uZm9ybWFuY2V0b29scyIsImNoYWxsZW5nZSI6Ikg5aVc5eUE5YUFYRl9sZWxRb2lfRGhVazUxNEFkOFRxdjB6Q25DcUtEcG8ifQ\\",\\"assertions\\":[\{\\"assertionScheme\\":\\"UAFV1TLV\\",\\"assertion\\":\\"AT4DAQM-sQALLgkAMDA1NyMwMDAxDi4HAAEAAQIAAAEKLiAALKIPiFBolsxih6EfUWfMh2YhikU2uHY7r0nZRGj-KbMJLiAA_f0Wc_CToXv6JZnkNPS1a9qZqRPaGj-ACLhDD79szIcNLggAAAAAAAAAAAAMLkEABHKLfpbgIg7NhY8zD8uKpju6GEKdbEStKisXTQ90Vv57t7gopRGEUTEJwB02gJCmzXHOhkOPPQBU941pcER4AWoIPkoABi5GADBEAiAjajmVfBBYm-x2rkZz7ATrE3_JF4-3uZGzpp2dZK0VGwIgbNm0dbrUkb0xnBi9GHoQUnYl_778N2T9ooGKZQXsspA\\"\}],\\"header\\":\{\\"op\\":\\"Reg\\",\\"appID\\":\\"\\",\\"upv\\":\{\\"major\\":1,\\"minor\\":1\}\}\}]"\}\

Issue 2: I have pass all test case previous case: Protocol-Reg-Resp-4 "before-all" and I do not why. 
![image](https://user-images.githubusercontent.com/38279411/39047923-e3668924-44c5-11e8-83e6-5d6b2df32d5d.png)

Request: \{\
  "uafProtocolMessage" : "[\{\\"header\\":\{\\"upv\\":\{\\"major\\":1,\\"minor\\":1\},\\"op\\":\\"Reg\\",\\"appID\\":\\"\\"\},\\"challenge\\":\\"H9iW9yA9aAXF_lelQoi_DhUk514Ad8Tqv0zCnCqKDpo\\",\\"username\\":\\"hello@test.com\\",\\"policy\\":\{\\"accepted\\":[[\{\\"aaid\\":[\\"0057#0001\\"]\}]]\}\}]"\
\}\
Response: \{"message":"\{\\"additionalData\\":\{\},\\"uafProtocolMessage\\":\\"[\{\\\\\\"fcParams\\\\\\":\\\\\\"eyJhcHBJRCI6ImlvczpidW5kbGUtaWQ6b3JnLmZpZG9hbGxpYW5jZS5tb2JpbGUuY29uZm9ybWFuY2V0b29scyIsImNoYW5uZWxCaW5kaW5nIjp7fSwiZmFjZXRJRCI6ImlvczpidW5kbGUtaWQ6b3JnLmZpZG9hbGxpYW5jZS5tb2JpbGUuY29uZm9ybWFuY2V0b29scyIsImNoYWxsZW5nZSI6Ikg5aVc5eUE5YUFYRl9sZWxRb2lfRGhVazUxNEFkOFRxdjB6Q25DcUtEcG8ifQ\\\\\\",\\\\\\"assertions\\\\\\":[\{\\\\\\"assertionScheme\\\\\\":\\\\\\"UAFV1TLV\\\\\\",\\\\\\"assertion\\\\\\":\\\\\\"AT4EAQM-sQALLgkAMDA1NyMwMDAxDi4HAAEAAQIAAAEKLiAALKIPiFBolsxih6EfUWfMh2YhikU2uHY7r0nZRGj-KbMJLiAA7tVQfnUYtnHaRR0nl9rMpvB7P6nA4DAJ5Wojt17ZdjgNLggAAAAAAAAAAAAMLkEABAgFIk7YrZCfg1PbX1g-sOucx_PNIDJQ0fz4i9O9glaYUD2iWhbBC0HRqNP_9xYUsLiabj9lyaRe0FfXKZYmHtwIPksABi5HADBFAiEAxJQjAfLgiZtv1SMQKQW4WI0wXSwMF6nEeryThuBHkskCIEW-3XgBq4HzxkzrHjVOWPQMWuVm4gkqH_ZgMDJtZojJ\\\\\\"\}],\\\\\\"header\\\\\\":\{\\\\\\"op\\\\\\":\\\\\\"Reg\\\\\\",\\\\\\"appID\\\\\\":\\\\\\"\\\\\\",\\\\\\"upv\\\\\\":\{\\\\\\"major\\\\\\":1,\\\\\\"minor\\\\\\":1\}\}\}]\\"\}","errorCode":0\}\

Please help me check where I wrong!

Thank you very much!

**Comment by herrjemand** [comment]
Please review my answer at #207

**Comment by tamdq** [comment]
Daer Yuiry,
Thanks for your response.

I see your answer at #207 but You do not agree sha256(fcParams) have
problem because I show log hash challenge as hex string, so i create this
report to show log as base64url.

For Req-4 issue, the ConformanceTool always show this error while internet
connection stable

Please help me check this problem again.
Thanks.
