### ISSUE TITLE
UAFv1.1 Interop test

### ISSUE THREAD

**Issue by tamdq** [fido-alliance/conformance-tools-issues#210]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/v1.1

## What is your implementation class?

Client+Authr

## What is the version of the tool are you using?
v0.9.15

## What is the OS and the version are you running?
10.2 (14C92)

## Issue description
Can not process test some case with UAFv1.1 Interop test (Case: Test registration, Test authentication...) as picture below:
![image](https://user-images.githubusercontent.com/38279411/39104765-096a3748-46dc-11e8-8a23-35d667d3faca.png)
![image](https://user-images.githubusercontent.com/38279411/39104767-0dcdc2d2-46dc-11e8-853c-14eca4a7aada.png)
![image](https://user-images.githubusercontent.com/38279411/39104771-11dfe0b2-46dc-11e8-8312-160cdf6587b7.png)

Please check it again!

**Comment by herrjemand** [comment]
Thanks @tamdq I have fixed this issue in v0.9.16(Should be out in few hours)

Regards. Yuriy
