### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-4

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#215]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.9.418

## Issue description

In F-10 of the negative test, the test tool tries to send x5cFullChain not in metadata to the server,
Since the intermediate certificate actually sent is the same as the test of P-2, this test can not receive an error from the server.
I think that the test tool should send an intermediate certificate different from P-2 in the F-10 test.

**Comment by herrjemand** [comment]
The test was removed
