### ISSUE TITLE
Authr-MakeCred-Resp-2 P-2: wrong basicConstraints CA value returned by getCertificateInfoObject

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#216]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.419

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
From what I've seen in the code, after calling getCertificateInfoObject(), the basicConstraintsCA has a wrong value: in the certificate is set to FALSE and the functions returns as TRUE.

**Comment by herrjemand** [comment]
can you give me a sample of cert?

**Comment by eugenIFX** [comment]
sent it to you over email

**Comment by herrjemand** [comment]
Resolved in v0.9.420
