### ISSUE TITLE
Authr-MakeCred-Resp-2: test not only self-signed certificate

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#217]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.419

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Inside Authr-MakeCred-Resp-2, P-2 test case, the tool is assuming that the attStmt certificate is self-signed. Please provide a way to test also a certificate generated using a CA.

**Comment by herrjemand** [comment]
Thans resolved in v0.9.420
