### ISSUE TITLE
Authr-GetAssertion-Req-1 P-1: test is using random credential

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#218]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.417

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Inside P-1 test, the credential used for getAssertion is not the same as the previous one used for makeCredential.

**Comment by herrjemand** [comment]
Can you send me makeCredResp and credId you expect?

**Comment by herrjemand** [comment]
Sorry, I am very confused on why it does that

**Comment by eugenIFX** [comment]
Before running the tests from Authr-GetAssertion-Req-1 the tool is creating a new credential by sending a makeCredential command. But, the rp used for it is different than the one used for getAssertion. That's why the authenticator will return CTAP2_ERR_NO_CREDENTIALS error code.

The first screenshot is for makeCredential and the second one for getAssertion.

![makecredential](https://user-images.githubusercontent.com/29768798/39614805-503a1b00-4f7b-11e8-9115-46050bc35dae.PNG)


![getassertion](https://user-images.githubusercontent.com/29768798/39614815-5467eefa-4f7b-11e8-84e8-efec88ff0396.PNG)

**Comment by herrjemand** [comment]
Hm... Weird... Looking at it right now

пт, 4 мая 2018 г., 9:14 eugenIFX <notifications@github.com>:

**Comment by herrjemand** [comment]
Resolved. The id was okay, the issue was incorrect rpId.

Sorry for that
