### ISSUE TITLE
ClientData challenge should be base64url encoded

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#221]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.419

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

ClientData contains the server sent challenge for the "create" as well as "get" APIs. The challenge should be base64url encode of the challenge sent by the server.

**Comment by herrjemand** [comment]
@pranav-bbhardwaj I am not sure what do you mean by that? Can you provide an example?

**Comment by pranav-bbhardwaj** [comment]
Refer to the WebAuthn specs section 5.10.1. 
The dictionary of the collectedClientData suggests that the challenge in the response is the base64url encoding of the challenge provided by the RP.
e.g. if the challenge sent by the RP in 'create' and 'get' requests is 'x', the response collectedClientData should be the challenge should be 'b64url(x)'

**Comment by herrjemand** [comment]
The challenge is base64url encoding of the challenge buffer. So the tool performs as expected

**Comment by pranav-bbhardwaj** [comment]
Can you confirm it's the base64url of the challenge sent by RP ? The logs on my end suggest differently.

When you talk about challenge buffer, how do you get the challenge buffer? Has it been base64 decoded already of the RP challenge? that would be an issue then

**Comment by herrjemand** [comment]
RP generates a random challenge buffer and then just base64url encodes it. 
Please refer to https://github.com/fido-alliance/webauthn-demo

**Comment by herrjemand** [comment]
@pranav-bbhardwaj Please read the latest server specs draft https://drafts.fidoalliance.org/fido-2/latest/fido-server-v2.0-wd-20180508.html#transport-binding-profile
