### ISSUE TITLE
GetAssertion tests : pre requisite registrations do not send rawId

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#222]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.419

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

GetAssertion request and responses have a pre requisite registration step. In this pre-requisite step the "rawId" is missing in the PublicKeyCredential object.

**Comment by herrjemand** [comment]
@pranav-bbhardwaj rawId is a buffer value of the id. I have added this field to the assertion, but it has the same value as id

**Comment by herrjemand** [comment]
@pranav-bbhardwaj Please read the latest server specs draft https://drafts.fidoalliance.org/fido-2/latest/fido-server-v2.0-wd-20180508.html#transport-binding-profile
