### ISSUE TITLE
Modifying variables at getAssertion method (ctap2Authenticator.js)

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#223]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
0.9.419

## Issue description
"webauthnRequest.userVerification" must be modified to "getAssertionRequestStruct.userVerification" 
at getAssertion method (ctap2Authenticator.js)
https://github.com/fido-alliance/fido2-conformance-module/blob/master/js/authenticator/ctap2Authenticator.js#L382

**Comment by herrjemand** [comment]
Yes, you are correct. Thanks @hueno-ttic !

**Comment by herrjemand** [comment]
Resolved in v0.9.421
