### ISSUE TITLE
RSA algorithm tests uses same certs

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#228]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.9.420

## Issue description
On Server-ServerAuthenticatorAttestationResponse-Resp-10, all the tests using the RSA algorithm use the same certs.
I think that different certs should be used depending on the difference like PSS or PKCS.

**Comment by herrjemand** [comment]
RSAPSS is not supported option in openssl for X509 certificates.
