### ISSUE TITLE
HID-1 P-10: incorrect fail after CTAPHID_INIT command

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#230]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The tool is triggering a false fail after receiving the response for CTAPHID_INIT. Please have a look on the screenshots.

![capture](https://user-images.githubusercontent.com/29768798/39910748-5cd717d8-5501-11e8-851d-b2ff674e57b0.PNG)

![error](https://user-images.githubusercontent.com/29768798/39910751-5f81b222-5501-11e8-927b-f997fcfb61b2.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.421
