### ISSUE TITLE
HID-1 P-9: this test is making the following ones to fail

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#231]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
P-9 test is making the following tests to fail. From my understanding, the tool is not waiting for the KEEPALIVE message from the authenticator. Please have a look on the screenshots.

![capture](https://user-images.githubusercontent.com/29768798/39911188-38540c2a-5503-11e8-942c-fd4b33664145.PNG)

![error2](https://user-images.githubusercontent.com/29768798/39911217-4dad2750-5503-11e8-920a-bafdd6811fe4.PNG)

![error](https://user-images.githubusercontent.com/29768798/39911223-529f51ac-5503-11e8-93ba-5f8cdd419520.PNG)

**Comment by herrjemand** [comment]
The tool is sending cancel after checking that authr is sending keep alive. Looks like the authenticator is not canceling operation, and so it make continuious tests to fail

**Comment by eugenIFX** [comment]
What I'm understanding from the trace log is that the tool is sending CTAPHID_INIT, waits for the response and after that is going to the next test case without sending makeCredential command. Please correct me if I'm wrong.

**Comment by herrjemand** [comment]
@eugenIFX No, the tool is sending Init and then make credentials

**Comment by herrjemand** [comment]
@eugenIFX I think what confuses you is that I forgot to add tracelog to syncronous HID requests. Will do that in v0.9.421

**Comment by herrjemand** [comment]
Closing for now
