### ISSUE TITLE
Authr-GetAssertion-Resp-1 P-2: tool is using different rpId for makeCredential and getAssertion

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#232]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The tool is using one rpId for makeCredential and another rpId to calculate rpIdHash.

![error](https://user-images.githubusercontent.com/29768798/39915320-4a1cd7ae-5510-11e8-9ca8-6656075ca28a.PNG)

![error2](https://user-images.githubusercontent.com/29768798/39915324-4c6feb36-5510-11e8-80d2-e2a49c43ca00.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.421
