### ISSUE TITLE
Authr-GetAssertion-Resp-2 P-1: key is not defined

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#234]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
I think there is a type on line 410 inside fido2dep.js: define "keys" variable and on the next line you are calling "key". 

P.S. Another typo is inside Authr-GetAssertion-Resp-2.js description, where you are using "Authr-GetAssertion-Resp-1.js"

**Comment by herrjemand** [comment]
Resolved in v0.9.421
