### ISSUE TITLE
Authr-MakeCred-Resp-2 P-2: verifyCertificateChain is using CACert in wrong format

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#236]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Inside verifyCertificateChain() from utils.js, the CACert is used in raw format and not in x.509 format when making Signature.init(CACert). I think this the root cause of the following error.

![capture](https://user-images.githubusercontent.com/29768798/39927319-7845e6fa-553a-11e8-9b82-4984ff0bcaed.PNG)

**Comment by herrjemand** [comment]
Could send you batch certificate to me? @eugenIFX

**Comment by herrjemand** [comment]
Close per not an issue
