### ISSUE TITLE
Authr-ClientPin1-GetKeyAgreement P-1 : COSE key alg is not required

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#237]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.420

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The alg is not required for a COSE key used  for a clientPIN command. This is required only for makeCredential use cases.

**Comment by herrjemand** [comment]
Good point @eugenIFX . Resolved in v0.9.421
