### ISSUE TITLE
Packed Attestation Certificate Chain Validation fails

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#239]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.419

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description
For "MakeCredential" Response tests:
Server-ServerAuthenticatorAttestationResponse-Resp-4
(P-2)

The certificate chain attestation fails chaining the certificate chain in the attestation to the certificates in the metadata statement for the AAGUID : 80f53d1e-852e-43ed-bb3f-d02f1322e5af
Requires investigation into the generated attestation certificate chain as the chain validation fails for following error: 
basic constraints check failed: this is not a CA certificate (certificate at index 1 in the chain is not chaining correctly to the trusted anchors in the metadata statement corresponding to the AAGUID metadata statement)

**Comment by herrjemand** [comment]
Unrelated since this test was removed
