### ISSUE TITLE
F-5 of AssertionResponse-Resp-2 is a positive test

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#241]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
0.9.421

## Issue description
F5 of AssetionResponseResp4 is a positive test.
https://github.com/fido-alliance/fido2-conformance-module/blob/master/tests/server/GetAssertion/Server-ServerAuthenticatorAssertionResponse-Resp-2.js#L95-L107

The "type" member  is "webauthn.get" is positive when getting an assertion.
https://www.w3.org/TR/webauthn/#dom-collectedclientdata-type

**Comment by herrjemand** [comment]
@hueno-ttic yes, you are correct, there is a typoe as it has to be set to create in order to be negative test.

**Comment by herrjemand** [comment]
Resolved in v0.9.422
