### ISSUE TITLE
Multiple Errors with 'not a function' in ASM Tests

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#242]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Client ASM

## What is the version of the tool are you using?
v0.9.20

## What is the OS and the version are you running?
Android 6.0.1

## Issue description

When running the test set for ASM, multiple errors are reported back with "xxx is not a function"

**Comment by herrjemand** [comment]
Resolved in v0.9.21
