### ISSUE TITLE
Android key Attestation 

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#243]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

Android key Attestation test case not sending a valid AAGUID in the response.  (AAGUID sent is 0x00)
Test case : ServerAuthenticatorAttestationResponse-Resp-7 (P-1)

The AAGUID should match the AAGUID listed in : 
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Android Key Attestation(.json)
i.e. "550e4b54-aa47-409f-9a95-1ab76c130131"

**Comment by herrjemand** [comment]
Resolved in v0.9.422
