### ISSUE TITLE
FIDO2 Authentication 

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#244]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

The authentication test cases, call /assertion/options endpoint with a username which has no registrations. This seems to be the case on multiple test cases, e.g. : Server-ServerAuthenticatorAssertionResponse-Resp-1 (F-1) 

The server fails the /assertion/options call as the user does not have any existing registrations, the server fails for this user , as the "User does not exists!". This is expected behavior as per the FIDO2 server specs, conformance tool is deviating from this behavior.

Please look for this issue for all test cases under  Server-ServerAuthenticatorAssertionResponse-Resp-1 

Thanks!

**Comment by herrjemand** [comment]
Resolved in v0.9.422
