### ISSUE TITLE
clientData type field check for Authentication

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#245]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

ServerAuthenticatorAssertionResponse-Resp-2 (F-4 and F-5) 

the type check between webauthn.create and webauthn.get types are not matching the expected values for authentication. These test cases should be considered for a fix for correct type check.

**Comment by herrjemand** [comment]
Resolved in v0.9.422
