### ISSUE TITLE
Authr-MakeCred-Resp-2, P-2 : expected wrong OU

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#247]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The test tool is verifying the OU from the Issuer and not from the Subject to be "Authenticator Attestation".

**Comment by herrjemand** [comment]
Resolved in v0.9.422
