### ISSUE TITLE
Authr-ClientPin1-NewPin, P-2 : missing pinHashEnc

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#248]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Missing pinHashEnc from generateClientPin_ChangePIN() function.

**Comment by herrjemand** [comment]
Resolved in v0.9.422
