### ISSUE TITLE
Negative test does not require username at AssertionResponse-Resp-1.js

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#251]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.9.421

## Issue description
Negative test does not require username at AssertionResponse-Resp-1.js
Because this test first generates a username and uses its username.
For example
https://github.com/fido-alliance/fido2-conformance-module/blob/master/tests/server/GetAssertion/Server-ServerAuthenticatorAssertionResponse-Resp-1.js#L59

**Comment by herrjemand** [comment]
Resolved in v0.9.422

Thanks @hueno-ttic
