### ISSUE TITLE
Since Promise.race is used, the behavior changes depending on the order of credIds returned.

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#252]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.9.421

## Issue description
Since Promise.race is used, the behavior changes depending on the order of credIds returned.
https://github.com/fido-alliance/fido2-conformance-module/blob/master/js/authenticator/webauthnClient.js#L153

For example, in P-1 of AssertionResponse-Resp-3, since multiple credIds are registered with the same username, we can not pass the test properly.
https://github.com/fido-alliance/fido2-conformance-module/blob/master/tests/server/GetAssertion/Server-ServerAuthenticatorAssertionResponse-Resp-3.js#L31-L54

**Comment by herrjemand** [comment]
@hueno-ttic well, if a credential is a valid credential, then it does not matter which one of the credentials returned.

**Comment by hueno-ttic** [comment]
@herrjemand 
As Promise.race, if the error process is executed first, does not the test pass?

**Comment by hueno-ttic** [comment]
@herrjemand 
Yes.
At the start of the P-1 test of AssertionResponse-Resp-3, two credIds are saved with the same username, and the test result changes according to the way of passing allowCredentials returned by /assertion/options.

I think that the test result does not depend on the order of allowCredentials returned in /assertion/options.

**Comment by herrjemand** [comment]
@hueno-ttic If you are sending allowCredentials and any those assertions returned, you must succeed
