### ISSUE TITLE
UAF 1.0, ASM General tests, Client-ASM_Protocol-1 test cases fail

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tools-issues#254]
UAF v1.0
ASM General tests
Tool Version 0.9.21

## Issue description
After installing the mfac client and ASM, when you first run the ASM General tests the following test cases fail:

 - Client-ASM_Protocol-1  P-1
AssertionError: AuthenticatorInfo.isUserEnrolled MUST be set to true!: expected false to be true

 - Client-ASM_Protocol-1  P-2
AssertionError: GetRegistrations response is empty!: expected [] not to be empty

When you first run (or after the mentioned above failures) the ASM Register tests, and then you run the ASM General tests again - all tests in both test cases pass.

**Comment by herrjemand** [comment]
@armenabgaryan yes, that's correct. AuthenticatorInfo.isUserEnrolled needs to be presented, and GetRegistrations needs to be presented as an empty array, if no registrations is actually presented.
