### ISSUE TITLE
Authenticator Metadata statement validation

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#255]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.421

## What is the OS and the version are you running?
Mac osx 10.12.4

## Issue description

Error while checking conformance of the webAuthn authenticator metadata published with the conformance tool : Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Self(surrogate) attestation.json. 

 root certificate(s) should not be present for this metadata statement for self (surrogate) attestation.

**Comment by herrjemand** [comment]
@pranav-bbhardwaj Thanks for that. It's now resolved in v0.9.422
