### ISSUE TITLE
Timeout after 2 seconds in ASM Dereg tests for UAF 1.0

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tools-issues#256]
UAF v1.0
ASM tests
Tool Version 0.9.21

## Issue description
For the ASM Dereg tests timeout is set to 2000ms, and sometimes it's hard to complete operation in time.
For the other test cases looks like the timeout is set to 30000ms.

**Comment by herrjemand** [comment]
Resolved in v0.9.22
