### ISSUE TITLE
iOS app installation failed 

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#257]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is the version of the tool are you using?
v0.9.21

## What is the OS and the version are you running?
iOS 11.3.1

## Issue description
Currently unable to install the conformance tool via Xcode. (Screenshot is attached)

**Comment by jenkay** [comment]
<img width="634" alt="screen shot 2018-05-24 at 2 25 30 pm" src="https://user-images.githubusercontent.com/5342760/40514783-5a529876-5f5f-11e8-83bf-47dc4b6900e6.png">

**Comment by herrjemand** [comment]
@jenkay Is this a new device?

**Comment by herrjemand** [comment]
@jenkay yes. We are still doing ad-hoc build. Please email me UDID and I will update the latest build.
