### ISSUE TITLE
There is bug in authenticatorDataContainsInvalidRPIdHash.

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#259]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.9.421

## Issue description
There is bug in authenticatorDataContainsInvalidRPIdHash.

I think "rpIDHashBuffer" is correct, not "this.rpIDHashBuffer".
https://github.com/fido-alliance/fido2-conformance-module/blob/master/js/authenticator/ctap2Authenticator.js#L440

**Comment by herrjemand** [comment]
Resolved in v0.9.422

Thanks @hueno-ttic
