### ISSUE TITLE
Options test error

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#260]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Receive tool error at the beginning of the test sequence. No test case is executed. Please see attached screenshot.

![options_failed](https://user-images.githubusercontent.com/29768798/40639713-17ebc998-631b-11e8-9c0a-6f35a8da251b.PNG)

**Comment by herrjemand** [comment]
Build issue. Thanks for that @eugenIFX. The build was re-uploaded
