### ISSUE TITLE
Authr-MakeCred-Resp-3.js - wrong file description

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#261]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Wrong file description for Authr-MakeCred-Resp-2.js (see line 5).

**Comment by herrjemand** [comment]
Resolved in v0.9.422
