### ISSUE TITLE
When authenticatorDataFlagsUPisFALSE, authenticatorData is not set correctly.

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#262]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.9.422

## Issue description
When authenticatorDataFlagsUPisFALSE, authenticatorData is not set correctly.
https://github.com/fido-alliance/fido2-conformance-module/blob/master/js/authenticator/ctap2Authenticator.js#L429-L430

I think that it would be better to do as follows.
```
if(modifiers.authenticatorDataFlagsUPisFALSE) { 
                        flagsObject.up = false;
                        this.generateAuthData(this.rpIDHashBuffer, flagsObject, counterBuffer);
}

```

**Comment by herrjemand** [comment]
@hueno-ttic Yes, you are correct. And I found some more bugs. Resolved in v0.9.423

Thank you!
