### ISSUE TITLE
Salt length is not set on RSASSA-PSS algorithm

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#263]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.9.422

## Issue description

When creating the RSASSA-PSS algorithm signature, I think salt length should be set.
https://tools.ietf.org/html/rfc8230#section-2

**Comment by herrjemand** [comment]
Thanks for that @prvjhamada 

Resolved in v0.9.423
