### ISSUE TITLE
HID-1 P-11 : remove payload verification

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#265]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
I think there is no need to verify if the received payload is an array of 57 bytes (BCNT = 0). Please have a look what is happening on this test case.

![capture2](https://user-images.githubusercontent.com/29768798/40716939-46be2df8-6413-11e8-8ec1-27bead362bf2.PNG)

![capture](https://user-images.githubusercontent.com/29768798/40717054-b503ea46-6413-11e8-8a07-96504487822b.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.9.423. Thanks @eugenIFX!
