### ISSUE TITLE
HID-1 P-10: CANCEL sequence is failing due to sendHIDBufferSync/readHIDResponseSync

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#266]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The tool seems that is not receiving the response from the authenticator for the CANCEL command. If I replace sendHIDResponseSync with sendCTAPHIDCommand and readHIDResponseSync with parseCTAPHIDPacket, the response is visible and can be seen in the console output.

**Using sendHIDResponseSync / readHIDResponseSync :**

![cancel_failling](https://user-images.githubusercontent.com/29768798/40722277-90c15a7c-6424-11e8-9374-a527c5c76cde.PNG)

**Using sendCTAPHIDCommand / parseCTAPHIDPacket:**

![cancel_ok](https://user-images.githubusercontent.com/29768798/40722303-a1e6d156-6424-11e8-92af-16fcfadb8e02.PNG)

**Comment by herrjemand** [comment]
@eugenIFX DATA READ BUFFER: is the log for synchronous buffer reading

**Comment by eugenIFX** [comment]
The problem is that is something wrong when using sync mode (it's not an authenticator problem).

**Comment by herrjemand** [comment]
@eugenIFX I can increase timeout to 200ms if yo want?

**Comment by eugenIFX** [comment]
@herrjemand , I set readHIDResponseSync to 1 sec, but no change. Is this the timeout you mentioned?

**Comment by herrjemand** [comment]
@eugenIFX I can't see what's wrong. Here is what I get:
<img width="801" alt="screenshot 2018-06-21 17 56 15" src="https://user-images.githubusercontent.com/1636116/41733675-77c2d2e4-757c-11e8-9cab-ab50663d1899.png">

You can see that cancel is sent

**Comment by eugenIFX** [comment]
Hi @herrjemand . Sorry, the problem was from the authenticator side due to the recent update from the spec.

**Comment by herrjemand** [comment]
@eugenIFX *)
