### ISSUE TITLE
ServerAuthenticatorAttestationResponse-Resp-10 test cases

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#269]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

The test case for positive cases, the COSE algorithm identifiers does not seem to map to COSE algorithm identifiers values  : https://www.iana.org/assignments/cose/cose.xhtml
e.g. For test case P-11 : ECDSA SHA512 the COSE algo id returned by the tool is -39 , but instead it should be -36. 

Please check for all test cases within this test suite.

Additionally, according to the webAuthn specs , ECDSA signatures should be ASN.1 DER encoded and 
RSASSA-PKCS1-v1_5, RSASSA-PSS should not be ASN.1 DER wrapped.
refer : https://www.w3.org/TR/webauthn/#signature-attestation-types
Seems like test cases names should be updated accordingly for ECDSA test cases.

**Comment by pranav-bbhardwaj** [comment]
@herrjemand : seeing similar issues with GetAssertion response test cases where they fail on prerequisite "registration" steps. Can you please check for the signature and attestation certificates for test cases under Server-ServerAuthenticatorAssertionResponse-Resp-1 test suite.

thanks.

**Comment by herrjemand** [comment]
Resolved in v0.9.423
