### ISSUE TITLE
Authr-ClientPin1-NewPin P-4 : wrong pinToken length

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#270]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The getPINToken() function return wrong pinToken (16-byte array), its length must be 32-byte. The reason is that decryptAES256CBCIV0 returns a 16-byte decrypted pinToken.

**Comment by herrjemand** [comment]
From the specs:

> First 16 bytes of HMAC-SHA-256 of encrypted contents using sharedSecret. See Setting a new PIN, Changing existing PIN and Getting pinToken from the authenticatorfor more details.

<img width="819" alt="screenshot 2018-06-02 14 27 27" src="https://user-images.githubusercontent.com/1636116/40876457-4966c226-6671-11e8-9183-78ce32472962.png">

**Comment by herrjemand** [comment]
Yes, you are correct @eugenIFX. Resolved in v0.9.423
