### ISSUE TITLE
"none" attestation is sent on "android-key" attestation test

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#272]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.9.422

## Issue description

In Server-ServerAuthenticatorAttestationResponse-Resp-9.js,
Since the argument "attestation" of getMakeCredentialsChallenge () is none, an attestation of none is created.
I think that android-key should be specified.

**Comment by herrjemand** [comment]
Resolved in v0.9.423
