### ISSUE TITLE
Signature validation fails for certain crypto algos

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#275]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the OS and the version are you running?
0.9.423

## Issue description
Certain signature algo. are failing for signature validation for attestation signature.

Server-ServerAuthenticatorAttestationResponse-Resp-10:
ALG_SIGN_RSASSA_PSS_SHA512_RAW
ALG_SIGN_RSASSA_PSS_SHA384_RAW
ALG_SIGN_RSASSA_PKCS1_SHA1_RAW

the test cases with these 3 algo are failing on attestation signature validation.

Note: ALG_SIGN_RSASSA_PSS_SHA256_RAW signature validation is successful. Other test cases in this suite are successful as well.

**Comment by herrjemand** [comment]
Resolved in v0.9.425
