### ISSUE TITLE
HID-1 P-9: tool is not sending CANCEL command

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#276]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.423

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Seems that the tool is not sending CANCEL command after verifying that response.CMD =  KEEPALIVE.

![capture](https://user-images.githubusercontent.com/29768798/40960205-b063ea8e-68a7-11e8-94f7-fa3dd41f0c11.PNG)

**Comment by herrjemand** [comment]
@eugenIFX There is a problem with logging which I am working on fixing. However the tool actually sends it:
<img width="836" alt="screenshot 2018-06-20 12 49 14" src="https://user-images.githubusercontent.com/1636116/41656598-71e4d97a-7488-11e8-9d84-398a2d68607e.png">

**Comment by eugenIFX** [comment]
Hi @herrjemand . If I put 2 window alerts before and after "window.navigator.fido.fido2conformancetest.hid.sendHIDCancel(getDeviceInfo(), NEWCID);" I can see that the authenticator cancels makeCredential command. 

Please also have a look on the attached screenshot and see that the authenticator is able to cancel makeCredential command.

![image](https://user-images.githubusercontent.com/29768798/41663783-e5ac2f74-74ac-11e8-93d0-ef59920e84dd.png)

**Comment by herrjemand** [comment]
@eugenIFX But you first have sent keep alive
<img width="404" alt="screenshot 2018-06-20 15 53 09" src="https://user-images.githubusercontent.com/1636116/41666292-153035c0-74a2-11e8-8d6a-f5643947afa9.png">

**Comment by eugenIFX** [comment]
@herrjemand , correct me if I'm wrong but I think this is the normal behavior of an authenticator: receive makeCredential command, send keepalive, receive CANCEL command and send back the response for it.

The reported problem is that before sending CANCEL command from the tool, a delay is required. I can't figure out why. On my logs, you can see that I don't have any delay on my scripts and the authenticator response is ok.

**Comment by eugenIFX** [comment]
Short update: if I replace the line which is calling sendHIDCancel() with the code below, I can see that the authenticator cancels the makeCredential command.

_let cancelBuffers = generateRequestFrames(CTAPHID_CMD.CTAPHID_CANCEL, [], NEWCID);
window.navigator.fido.fido2conformancetest.hid.sendHIDBufferSync(getDeviceInfo(), cancelBuffers);_

**Comment by herrjemand** [comment]
Resolved in v0.9.425
