### ISSUE TITLE
GetAssertion test cases for different crypto algos

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#277]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.424

## What is the OS and the version are you running?
Mac osx 10.12.4

## Issue description
Suggestion for test cases: The get assertion test cases should be enhanced for each crypto signature algorithm to be tested which is supported by the FIDO2 server specs.
Maybe this is already on the roadmap?

**Comment by herrjemand** [comment]
@pranav-bbhardwaj This is done with self attestation tests

**Comment by pranav-bbhardwaj** [comment]
thanks for the update on this!
