### ISSUE TITLE
Authr-MakeCred-Req-5 F-7 : sendINITCommand is not a function

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#278]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.424

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Seems there is a bug on F-7 test. Please see the attached screenshot.

![capture](https://user-images.githubusercontent.com/29768798/41218481-eafb4ad2-6d63-11e8-8991-976ef90ee230.PNG)

**Comment by herrjemand** [comment]
resolved in v0.9.425
