### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-4 Test server processing "packed" FULL attestation

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#279]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server
## What is the version of the tool are you using?
0.9.424

## What is the OS and the version are you running?
Mac OSX 10.12.4

## Issue description

The test expects to fail as the leaf cert has not yet started, but the leaf cert validity date suggests it's valid from 18th March 2018, hence the operation is successful, though the conformance tool expects otherwise

**Comment by herrjemand** [comment]
@pranav-bbhardwaj you need to update your metadata
