### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-A test suite issue 

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#280]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.424

## What is the OS and the version are you running?
Mac osx 10.12.4

## Issue description

Android key attestation test cases are sending the attestation format as "none"  instead of "android-key". 
Also, the AAGUID is send as {00000000-00..} , this requires update to send AAGUID as appropriate for the test cases within the suite.

**Comment by herrjemand** [comment]
Resolved in v0.9.425
