### ISSUE TITLE
signature field value missing in GetAssertion Payload

### ISSUE THREAD

**Issue by pranav-bbhardwaj** [fido-alliance/conformance-tools-issues#282]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.424

## What is the OS and the version are you running?
mac osx 10.12.4

## Issue description

The GetAssertion response is missing the 'signature' field value in the response. 

Test cases with this issue :
Server-ServerAuthenticatorAssertionResponse-Resp-1 
& 
Server-ServerAuthenticatorAssertionResponse-Resp-3 . (multiple test cases within this suite)

**Comment by herrjemand** [comment]
Resolved in v0.9.425
