### ISSUE TITLE
SSL certificate expired on fidoalliance.co.nz

### ISSUE THREAD

**Issue by armenabgaryan** [fido-alliance/conformance-tools-issues#283]
UAF v1.1
Client tests
Tool Version 0.9.22

## Issue description
The following SSL error was got:

**NET::ERR_CERT_DATE_INVALID
Subject: fidoalliance.co.nz
Issuer: Let's Encrypt Authority X3
Expires on: Jun 13, 2018
Current date: Jun 15, 2018**

As a result Protocol-Reg-Req-4 P-4 and P-6 test cases are failing.

**Comment by herrjemand** [comment]
Resolved. Ugh.  Sorry
