### ISSUE TITLE
Signature verification fails on RSA-PSS and RSA-PKCS

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#284]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.9.425

## Issue description

In the test of RSA of Server-ServerAuthenticatorAttestationResponse-Resp-4,
Signature verification fails because the length of signature and the length of n of RSA public key generated from credentialPublicKey are different.
I confirmed that the length of signature is 256 bytes, but the length of n is 171 bytes.
I think public key is incorrect, would you confirm it?

**Comment by herrjemand** [comment]
resolved in v0v10.101
