### ISSUE TITLE
Add RESET after each test suite

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#285]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.426

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
@herrjemand , I just figure out that after I'm running ClientPIN tests, I not able to fully run MakeCredential tests because the authenticator keeps the previous PIN settings. I think after (or before) each test suite the tool must reset the authenticator.

**Comment by herrjemand** [comment]
Resolved in v0.10.105
