### ISSUE TITLE
NFC-1 P-1: wrong expected version

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#288]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.426

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The tool is expecting to receive "U2F_V2" and not "FIDO_2_0".

**Comment by herrjemand** [comment]
@eugenIFX Good point. Resolved in v0.10.101
