### ISSUE TITLE
NFC-1 P-2, P-3, P-4: sending SELECT applet in a loop

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#290]
FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.426

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
I can see in the Console output that the tool is continuously sending SELECT applet command even if the authenticator response is "FIDO_2_0".

![capture](https://user-images.githubusercontent.com/29768798/42169237-cce1ccba-7e1b-11e8-987e-b05dc2a61d24.PNG)

**Comment by herrjemand** [comment]
Thanks for that @eugenIFX. This issue is now resolved in v0.10.101
