### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp_A-B failures

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#291]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.0

## Issue description
Server-ServerAuthenticatorAttestationResponse-Resp_A-B Tests are failing
A- Test server processing “android-key” attestation
F-1
F-2
F-3

B- Test server processing “android-safetynet” attestation
F-1 — F7

**Comment by herrjemand** [comment]
Resolve in v0.10.103
