### ISSUE TITLE
userHandole is fixed as an empty string

### ISSUE THREAD

**Issue by hueno-ttic** [fido-alliance/conformance-tools-issues#293]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.100

## Issue description
The userHandle test fails because userHandole is fixed as an empty string.

https://github.com/fido-alliance/fido2-conformance-module/blob/master/tests/server/GetAssertion/Server-ServerAuthenticatorAssertionResponse-Resp-1.js#L372-L430

https://github.com/fido-alliance/fido2-conformance-module/blob/master/js/authenticator/webauthnClient.js#L162

**Comment by herrjemand** [comment]
Closed as dublicate of issue in #292
