### ISSUE TITLE
Timeout self-validation test cases

### ISSUE THREAD

**Issue by mervynokm** [fido-alliance/conformance-tools-issues#295]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1,1

## What is your implementation class?

Client

## What is the version of the tool are you using?

v0.9.22

## What is the OS and the version are you running?
iOS 11.2

## Issue description

As the number of test cases increased in the self-validation test tools (iOS/Android), the number of records stored on the FIDO mobile client increases. Currently, the client has no indicator that a test case has ended, and no tear downs are performed after each test case, causing an unless buildup to the DB which would unrealistically impact performance as the number of records store are much greater than real-world scenarios. This possibly leads to before-hook test failures as test timeouts are currently set to 30s, whereas large retrieval and decryption would be impacted without any cleanup. Is there any means of the self-validation tool to indicate to the mobile client that the test case has started/ended to perform the proper teardowns, or increase the timeout?

Believe #152 would resolve this

**Comment by herrjemand** [comment]
Yes #152 will resolve your issue. Will close this issue so we don't have dublicates
