### ISSUE TITLE
Tool throws an error on Windows 7

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#297]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.102

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Seems that the tool is searching for a USB BLE dongle. It's not a critical issue because if I click OK the tool is not crashing, but it will be nicer not having this error.

![capture](https://user-images.githubusercontent.com/29768798/42493060-04bb70a6-8424-11e8-9593-adcd9f6c812d.PNG)

**Comment by herrjemand** [comment]
This issue is FINALLY solve in v0.10.104
