### ISSUE TITLE
NFC-1 F-3, F-4: wrong decoded response from the authenticator

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#298]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.102

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
In the console log, I can see that the authenticator response is the one expected, but the tool is triggering a fail.

![capture](https://user-images.githubusercontent.com/29768798/42494230-4c12baf0-8428-11e8-9560-104c165ede11.PNG)

![log](https://user-images.githubusercontent.com/29768798/42494236-4f30495a-8428-11e8-822d-9ddf764a73e1.PNG)

**Comment by herrjemand** [comment]
Thanks for that @eugenIFX. I found that I had a typoe in the code table that was rewriting value of SW_WRONG_DATA. Just ignore those too issues for now.

Resolved in v0.10.103

**Comment by eugenIFX** [comment]
No worries :)
