### ISSUE TITLE
HID-1 P-10: second CTAPHID_CANCEL should expect no response from the authenticator

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#300]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.102

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
The tool is sending a second CTAPHID_CANCEL and expects to receive CTAPHID_ERROR from the authenticator. According to pull request #483 for the spec, a cancel received without no ongoing operation should be ignored by the authenticator.

**Comment by herrjemand** [comment]
Resolved in v0.10.104
