### ISSUE TITLE
User Verification error thrown for UAF 1.1 on Android

### ISSUE THREAD

**Issue by dssebastian** [fido-alliance/conformance-tools-issues#302]
## What protocol and version of the protocol are you testing?

v1.1

## What is your implementation class?

ASM

## What is the version of the tool are you using?
v.0.9.22
Also, tested with BETA/v0.9.102

## What is the OS and the version are you running?

Android, v7.0
## Issue description

I am executing the ASM tests on Android FIDO Conformance tool, with a Face & Voice authenticator:
The userVerification value for this authenticator is 1048 (Face and Voice).

In the FIDO Conformance tool (0.9.22), I selected the options, UAF 1.1, ASM, and General Tests

The Client-ASM-Protocol-1 (Test P-1) fails with error: userVerification is not set to one of the algorithms specified in Registry of Predefined Values! Expected undefined to not equals undefined.

The metadata for this authenticator also indicates userVerification as 1048.
Could you please let me know why this error is reported? 

[fido_conformance_android_facevoice_uverror.txt](https://github.com/fido-alliance/conformance-tools-issues/files/2193236/fido_conformance_android_facevoice_uverror.txt)

Thanks,
Dalys

**Comment by herrjemand** [comment]
@dssebastian Resolved in v0.9.103. I will release a build tomorrow.
