### ISSUE TITLE
Fido2 Conformance Test Tool : PSS Salt Length Setting Issue

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#304]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

### **PSS Salt Length Setting Issue**
Set SaltLength of signWithRSAKeyAsync and verifyRSASignatureAsync function in fido2dep.js 

In this RSA PSS case,  I know that the saltLength setting for SHA-256, SHA-384, SHA-512 is as follows.
But, currently, SaltLength is only fix 32.

**PSS SHA-256 Salt Length 32**
Reference Site: http://javadoc.iaik.tugraz.at/iaik_jce/old/iaik/security/rsa/SHA256withRSAandMGF1Signature.html

**PSS SHA-384 Salt Length 48**
Reference Site: http://javadoc.iaik.tugraz.at/iaik_jce/old/iaik/security/rsa/SHA384withRSAandMGF1Signature.html

**PSS SHA-512 Salt Length 64**
Reference Site: http://javadoc.iaik.tugraz.at/iaik_jce/old/iaik/security/rsa/SHA512withRSAandMGF1Signature.html

**Comment by herrjemand** [comment]
Resolved in v0.10.103
