### ISSUE TITLE
Fido2 Conformance Test Tool : Android Key Store Attestation isn't match with android key intermediate certification

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#305]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
An error occurs because the issuer is different from the issuer.

<Subject Info in Android key intermediate certification>
L = Wakefield
S = MY
C = US
OU = CWG
O = FIDO Alliance
E = conformance-tools@fidoalliance.org
CN = FAKE Android Keystore Software Attestation Intermediate FAKE

**Comment by herrjemand** [comment]
Resolved in v0.10.104
