### ISSUE TITLE
Fido2 Conformance Test Tool : Need not EDDSA SHA256 HASH

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#307]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
EDDSA 25519 is include SHA-512 HASH.
So, I think Need to change algorithm name from ALG_SIGN_ED25519_EDDSA_SHA256_RAW to ALG_SIGN_ED25519_EDDSA_SHA512_RAW.
And, EDDSA crypto tool perform sha-512 hash internally.
Then, I think Need not additional hash operation.

<Currently Code: EDDSA Name Variable>
ALG_SIGN_ED25519_EDDSA_SHA256_RAW

<Modified Code: EDDSA Name Variable>
ALG_SIGN_ED25519_EDDSA_SHA512_RAW

**Comment by herrjemand** [comment]
@dongho78 Yes,  you are correct. Reported back to TWG. Waiting for confirmation of the fix.

**Comment by dongho78** [comment]
@herrjemand We need a quick decision on this because the first fido2 interoperability test isn't much time left.
