### ISSUE TITLE
Fido2 Conformance Test Tool : make Invalid RSA 2048 Public Key

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#308]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
I think, the problem related to RSA is that when the COSE Public Key is 2048 bit, it is generated as 171 Byte instead of 256 Byte.
Analysis of the cause, It is decode hex from the string data.
This is problem.
It need to decode base64url because the string data is base64url encoded value.
Can you check this?

'-1': hex.decode(rsaPKCoefficients.n),
'-2': hex.decode(rsaPKCoefficients.e)

->

'-1': base64url.decode(rsaPKCoefficients.n),
'-2': base64url.decode(rsaPKCoefficients.e)

**Comment by herrjemand** [comment]
Resolved in v0.10.104
