### ISSUE TITLE
Fido2 Conformance Test Tool : missing byte on TPM Test Case

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#309]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
When the TPM CertInfo is generated, the value of Int is entered and the original target 2 Byte is changed to 1 byte, which causes the problem of not parsing.
So, I add extra 1 byte.

Example
55fb${nameLengthHex}     ->     55fb00${nameLengthHex}

**Comment by herrjemand** [comment]
Thanks for that @dongho78. Resolved in v0.10.104
