### ISSUE TITLE
Fido2 Conformance Test Tool : Not apply negative case value on AndroidKeyAttestatio Test Case

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#310]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
Negative case value is applied after the value is created and is not reflected.

reference generateAndroidKeyAttestation function

**Comment by herrjemand** [comment]
Resolved in v0.10.104
