### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid Certification Version

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#311]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
Intermediate Cert Version is V1.
So, we need to change certification from V1 to V3.
In other word, we add extension field in certification.

reference batchForIntermediate value

**Comment by herrjemand** [comment]
Resolved in v0.10.104
