### ISSUE TITLE
Invalid Signature for authenticatorDataContainsCounterSetToZero Test

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#312]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
Counter changed to 0, but this is not reflected in the data used as signatures.

reference modifiers.authenticatorDataContainsCounterSetToZero

**Comment by herrjemand** [comment]
This was cause by previous attestation none issue. Was resolved in v0.10.103
