### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid basicConstraint in safetyNet Attestation Certification

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#313]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
Invalid basicConstraint in safetyNet Attestation Certification.

**Comment by herrjemand** [comment]
@dongho78 Can you clarify what bit you think  is causing basicConstraint to be invalid?

**Comment by herrjemand** [comment]
Resolved in v0.10.104

**Comment by herrjemand** [comment]
Resolved in v0.10.104
