### ISSUE TITLE
Fido2 Conformance Test Tool : Not unique aaguid in Metadata

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#315]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
The aaguid of CTAP2RSA15SHA256TPMAttestation.metadata.json is same the aaguid of CTAP2RSA15SHA256SafetynetAttestation.metadata.json.
Then, you need to change aaguid of something one.

<aaguid of CTAP2RSA15SHA256TPMAttestation.metadata.json>
c87cdd97-56c1-49b8-9e24-cb363654f350

< aaguid of CTAP2RSA15SHA256SafetynetAttestation.metadata.json>
c87cdd97-56c1-49b8-9e24-cb363654f350

**Comment by herrjemand** [comment]
Thanks for that @dongho78 

Resolved in v0.10.104
