### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid Data for authenticatorDataContainsInvalidRPIdHash, authenticatorDataCounterIsNotIncreased

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#317]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
fido2-conformance-module (Updated cancel test. Fixed #301) version

## What is the OS and the version are you running?
Window 7 64bit

## Issue description
We need to define another rpIDHashBuffer value for authenticatorDataContainsInvalidRPIdHash test in getAssertion function.
If we use this.rpIDHashBuffer, It is affects other test cases.

We need to change from [this.counter - 1] to [1] for authenticatorDataCounterIsNotIncreased test in getAssertion function. 

The "[this.counter - 1]" value varies depending on the test method.

**Comment by herrjemand** [comment]
Resolved in v0.10.103
