### ISSUE TITLE
GetAssertion Response Errors

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#319]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.103

## Issue description
These 2 issues are still reproducible
failures:
Server-ServerAuthenticatorAssertionResponse-Resp-1
F-22
F-25

**Comment by herrjemand** [comment]
@jenkay In 22 Response.userHandle is missing, and in 25 it's empty. The server must fail

**Comment by herrjemand** [comment]
@jenkay Actually nevermind. I have removed those tests.

Resolved in v0.10.104

**Comment by vs-nnl** [comment]
User handle is optional as per https://www.w3.org/TR/webauthn/#verifying-assertion (7.2.2). Editor's Draft (https://w3c.github.io/webauthn/#verifying-assertion) also has the same description. I think F-22 and F-25 should be removed.
