### ISSUE TITLE
Authr-ClientPin1 - GetKeyAgreement: "before" all hook

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#320]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.103

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Please see the attached screenshot.

![clientpin_error](https://user-images.githubusercontent.com/29768798/42865139-6111ac5a-8a71-11e8-887e-66dcebc831fc.PNG)

**Comment by herrjemand** [comment]
Resolved in v0.10.105
