### ISSUE TITLE
F-1 through F5 tests on Server-ServerAuthenticatorAttestationResponse-Resp-9 must be expected to fail.

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#322]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.104

## Issue description

On Server-ServerAuthenticatorAttestationResponse-Resp-9, the results of tests F-1 through F-5 should be expected failure.

```
return expectPromiseToFail(sendAttestationResponse(response))
```

**Comment by herrjemand** [comment]
Resolved in v0.10.104
