### ISSUE TITLE
OKP's COSE_Key is sent on ED25519 algorithm test

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#323]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.104

## Issue description

COSE_Key whose kty is OKP (integer 1) is sent on P-12 of Server-ServerAuthenticatorAttestationResponse-Resp-4.
Does RP MUST support OKP's COSE_Key?

**Comment by herrjemand** [comment]
@prvjhamada The EDDSA key is a single point OKP
