### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid FIDO2 INTERMEDIATE prime256v1 Certification

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#324]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module JUl 23, 2018 Commit: 76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and 
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

The certification on P-2 of Server-ServerAuthenticatorAttestationResponse-Resp-5 Test is invalid.

The subject of certification is "FIDO2 INTERMEDIATE prime256v1".

When it was parsed by x509 module, the error occured, because this certification isn't include basic constraint field.

Please check this certification("FIDO2 INTERMEDIATE prime256v1").

**Comment by herrjemand** [comment]
Resolved in v0.10.105
