### ISSUE TITLE
Fido2 Conformance Test Tool : Not change the exception data in F-3 of Server-Resp-A.

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#326]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module:  76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and 
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

Not change the exception data in F-3 of Server-ServerAuthenticatorAttestationResponse-Resp-A.

I think, need to change the exception handling position.

Please check this data.

**Comment by herrjemand** [comment]
Resolved in 0.10.105
