### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid Issuer field in Android KeyStore Attestation test.

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#327]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module : 76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and 
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

Invalid Issuer field in Android KeyStore Attestation test.

When it was parsed by x509 module, the error occured, because issuer der sequence of certification is invalid.

Please check this data.

**Comment by herrjemand** [comment]
Resolved in 0.10.105
