### ISSUE TITLE
Fido2 Conformance Test Tool : In F-11 test of Server-ServerAuthenticatorAssertionResponse-Resp-3, the result is unclear.

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#329]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module : 76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and 
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

The result is unclear.
Sometimes the encoded client data haven't base64-specific data ("+", "/").
If the encoded client data contains base64-specific data, the expected result will occur.
If the encoded clientdata does not have only base64 data, the unexpected results will occur .

So, I think we need to add base64-specific data in my test case.

Please check this data.

**Comment by herrjemand** [comment]
Hey @dongho78. I  have removed tests as i deemed invalid.

Regards. Yuriy
