### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid response data in android-safetyNet test.

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#330]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module : 76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and 
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

Invalid response data in android-safetyNet test.

When we parsed the response data
When we parsed the response data using JWT Parser, the signature of response data is invalid.

JWT Parser Site: https://jwt.io/

Please check this data.

**Comment by herrjemand** [comment]
Resolved in v0.10.105
