### ISSUE TITLE
AttestationChallenge can not be get from certificate on android-key test.

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#331]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.105

## Issue description

On F-1 of Server-ServerAuthenticatorAttestationResponse-Resp-A, AttestationChallenge can not be get from certificate.
The structure of extensions seems to be broken.
Could you confirm it please?

**Comment by herrjemand** [comment]
@prvjhamada Nope, the certificate encoded correctly. Test it with https://lapo.it/asn1js/

30820304308202a9a003020102020101300a06082a8648ce3d0403023081ce3145304306035504030c3c46414b4520416e64726f6964204b657973746f726520536f667477617265204174746573746174696f6e20496e7465726d6564696174652046414b453131302f06092a864886f70d0109011622636f6e666f726d616e63652d746f6f6c73406669646f616c6c69616e63652e6f726731163014060355040a0c0d4649444f20416c6c69616e6365310c300a060355040b0c03435747310b3009060355040613025553310b300906035504080c024d593112301006035504070c0957616b656669656c643020170d3730303230313030303030305a180f32303939303133313233353935395a30293127302506035504030c1e46414b4520416e64726f6964204b657973746f7265204b65792046414b453059301306072a8648ce3d020106082a8648ce3d03010703420004970579ca1f12c13fd76a1c04048482f573581b623f928a4dbd719e7b8f1442dbce476509c6810a77ff97078beb10d1689751cbe693d7facaad8a247ae58fd83ba382011830820114300b0603551d0f0404030207803081e1060a2b06010401d6790201110481d23081cf0201020a01000201010a01000420ad4daed37761e3403eaa0c6532dc211d964d2a8eb923bc12c94b66beaf0505d104003069bf853d080206015ed3e3cfa0bf85455904573055312f302d0428636f6d2e616e64726f69642e6b657973746f72652e616e64726f69646b657973746f726564656d6f0201013122042074cfcb507488f529108591c7a505919f327732fbc1d803526aea980006d2d8983032a1053103020102a203020103a30402020100a5053103020104aa03020101bf837803020102bf853e03020100bf853f02050030210603551d23041a041830168014529a1b32e056aacd510fef5f8037068bf291231d300a06082a8648ce3d0403020349003046022100b838ebc4caa516d33b1bbd38038a8c1d1e4adb067b73bb1c490ff4adcc011ee0022100d81d9313d0e8c32e2a58ae57985b1ef0653c84ba9361a6041502d56bd312873c
