### ISSUE TITLE
Fido2 Conformance Test Tool : Invalid UP,UV test case in Server-ServerAuthenticatorAssertionResponse-Resp-3

### ISSUE THREAD

**Issue by dongho78** [fido-alliance/conformance-tools-issues#332]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido2-conformance-module : 76dfacffd8d33d2a8c7c0dfe9d056ab6cc68d346 (Changed the test execution order)
and
v0.10.104

## What is the OS and the version are you running?

Window 7 64bit

## Issue description

I think, The content in w3c CR spec isn't matched the UP,UV test case in Server-ServerAuthenticatorAssertionResponse-Resp-3
And, Need to change test case.
So, I changed or added the test items below.
Can you check this?

1. Move and Modify Test Case

P-2 -> P-1
<Test Case Description>
1) Target User Verification: required
2) Set UV: True, UP: False

P-3 -> P-2
<Test Case Description>
1) Target User Verification: required
2) Set UV: False, UP: True

P-4 -> P-3
<Test Case Description>
1) Target User Verification: preferred
2) Set UV: False, UP: True

P-5 -> P-4
<Test Case Description>
1) Target User Verification: discouraged
2) Set UV: False, UP: True

P-1 -> F-6
Change Test Content
<Test Case Description>
1) Target User Verification: required
2) Set UV: True, UP: True

P-7 -> F-8
<Test Case Description>
1) Target User Verification: discouraged
2) Set UV: False, UP: False

2. Add Test Case
P-5
<Test Case Description>
1) Target User Verification: discouraged
2) Set UV: True, UP: True

F-7
<Test Case Description>
1) Target User Verification: preferred
2) Set UV: False, UP: False

**Comment by dongho78** [comment]
@herrjemand We need a quick decision on this because the first fido2 interoperability test isn't much time left

**Comment by herrjemand** [comment]
@dongho78 From Webauthn specs:

> User Verification
> The technical process by which an authenticator locally authorizes the invocation of the authenticatorMakeCredential and authenticatorGetAssertion operations. User verification MAY be instigated through various authorization gesture modalities; for example, through a touch plus pin code, password entry, or biometric recognition (e.g., presenting a fingerprint) [ISOBiometricVocabulary]. The intent is to be able to distinguish individual users. Note that invocation of the authenticatorMakeCredential and authenticatorGetAssertion operations implies use of key material managed by the authenticator. Note that for security, user verification and use of credential private keys must occur within a single logical security boundary defining the authenticator.

**Comment by herrjemand** [comment]
As I understand:

"required"
UV can be true
UP can be true
both can be true

"preferred"
UV can be true
UV can be false
UP can be true

"discouraged"
UV can be true
UV can be false
UP can be true
