### ISSUE TITLE
Fido2 Conformance Test Tool : Server-ServerAuthenticatorAttestationResponse-Resp-9, TPM

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#333]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.105

## What is the OS and the version are you running?

MacOS 10.13.3

## Issue description

On Server-ServerAuthenticatorAttestationResponse-Resp-9] P-2, Certificate in x5c field of TPM Attestation Statement don't same OID.

More specifically, signarueAlgorithm of Certificate Fields and signature field of tbsCertificate don't same. (RFC 3280)

So, An error occurs in the JDK.(at sun.security.x509.X509CertImpl.parse : "Signature algorithm mismatch") 

Could you comfirm it please?

![tpm_check](https://user-images.githubusercontent.com/27984632/43192206-e93c1c2a-9037-11e8-8b40-e159c15292ec.PNG)

**Comment by herrjemand** [comment]
Thanks for reporting @BoReumJung 

Resolved in v0.10.106
