### ISSUE TITLE
Doc points to dead link instead of this repo

### ISSUE THREAD

**Issue by blaisep** [fido-alliance/conformance-tools-issues#335]
## Issue description

The documentation for the fido2 spec at: 
https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html
points to a dead link for the [Issue Tracking page](https://github.com/fido-alliance/fido-2-specs
) : 
https://github.com/fido-alliance/fido-2-specs

I think it should probably point to: 
https://github.com/fido-alliance/conformance-tools-issues/issues/new
I would offer to fix it, but I can't find the repo for the docs.

**Comment by herrjemand** [comment]
Hey @blaisep. The repo isn't dead, it's just accessible only to FIDO members. You are free to email info@fidoalliance.org if you have any suggestions/issues regarding FIDO2 specs.
