### ISSUE TITLE
ServerAuthenticatorAttestationResponse-Resp-B, Android-safetyNest Test

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#336]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
- V0.10.105

## What is the OS and the version are you running?
- MacOS v10.13.3

## Issue description

[Same Issue #330] 

Invalid response data in android-safetyNet test in v0.10.105.
we also parsed the response data using JWT Parser, 
but, the signature of response data is invalid.

JWT Parser Site: https://jwt.io/

Could you comfirm it please?

**Comment by herrjemand** [comment]
@BoReumJung Yes, you are correct. I am working on this issue right now

**Comment by herrjemand** [comment]
Resolved in v0.10.106
