### ISSUE TITLE
current x509 notAfter parser can't handle year 2050

### ISSUE THREAD

**Issue by nuno0529** [fido-alliance/conformance-tools-issues#337]
## What protocol and version of the protocol are you testing?
FIDO2 v1.0/
## What is your implementation class?
Authr
## What is the version of the tool are you using?
v0.10.105(BETA)
Authr-MakeCred-Resp-2.js
P-2
assert.isTrue(certInfo.notAfter.getTime() > new Date().getTime(), `Attestation Certificate is expired! "${certInfo.notAfter}"`);
## What is the OS and the version are you running?
OSX
## Issue description
current x509 notAfter parser can't handle year 2050 and then cause this test item failed.
![image](https://user-images.githubusercontent.com/6506729/43256211-a6468d8e-90fe-11e8-9e24-16f78ff6b994.png)

**Comment by herrjemand** [comment]
@nuno0529 Can you  provide me with a copy of your attestation cert?

**Comment by nuno0529** [comment]
===
MIIBwTCCAWagAwIBAgIBATAKBggqhkjOPQQDAjAdMRswGQYDVQQDExJFZ2lzdGVjIENBIGZvciBVMkYwIBcNMTYwMjI2MDgxMTA2WhgPMjA1MDAyMjUwODExMDZaMGIxCzAJBgNVBAYTAlNFMRIwEAYDVQQKDAlFZ2lzdGVjQ0ExIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xGzAZBgNVBAMTEkVnaXN0ZWMgQ0EgZm9yIFUyRjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKJ/rbqoHEnlMevqro/giurgyUABC6OvAhvEqf/TCaYeq5Xf2uhmJKGVb/X4YJ1gOYwK2UqdXQ7IU+2zbKbtONGjUDBOMB0GA1UdDgQWBBTwdcHIO7A4K27mvde5zeamk4/w/TAfBgNVHSMEGDAWgBTwdcHIO7A4K27mvde5zeamk4/w/TAMBgNVHRMBAf8EAjAAMAoGCCqGSM49BAMCA0kAMEYCIQCx06ZNVE44/rep2qhjpcga0iIBTx9QETst+uU1sn7XzQIhAOoePBtO0DAJj3meUO/xdVla5/MDjNyQ9vedtNTd/e/8
===

**Comment by herrjemand** [comment]
Resolved v0.10.106
