### ISSUE TITLE
Fido2 Conformance Test Tool : The tool requires a server to test non-mandatory algorithms

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#339]
## What protocol and version of the protocol are you testing?

FIDO2 

## What is your implementation class?

Server

## What is the version of the tool are you using?
v.0.10.905(BETA)

## Issue description

When I have looked through Server Requirements and Transport Binding Profile Spec, there are few required algorithms that FIDO2 sever must implement.
However, the conformance testing tool we are using right now tests those recommended and optional algorithms for Server to complete without any option to skip. It means that FIDO2 server has to implement those non-mandatory algorithms to pass conformance tool test.

If the Server requirements spec defines any mandatory and optional algorithms, the conformance test tool has to provide option to skip those non-mandatory algorithms for server testing.

**Comment by herrjemand** [comment]
Resolved
