### ISSUE TITLE
Server_Metadata Service Test Resp-1

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#340]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
V0.10.925

## What is the OS and the version are you running?
macOS 10.13.3

## Issue description

I think that there is an error in the webauthnClient declaration. 
(let webauthnClient = new window.CTAP.WebauthnClient(metadata,'packed',serverURL);) 

In this state, it is not operated. If it declare at the top, it works.

Could you comfirm it please?

Ex :
[Not operated]
 `, () => {
        return getMDSMetadataForTestCase(serverURL, 'good')
            .then((metadata) => {
		let webauthnClient = new window.CTAP.WebauthnClient(metadata,'packed',serverURL);

[Operated]
let serverURL = window.config.test.serverURL;
let webauthnClient;
-------------------------
 `, () => {
        return getMDSMetadataForTestCase(serverURL, 'good')
            .then((metadata) => {
		webauthnClient  = new window.CTAP.WebauthnClient(metadata, 'packed', serverURL); .....

**Comment by YongWoo76** [comment]
Metadata Service Tests does not work.

OS: Windows 7
Version : V0.10.935

same error message at all cases;

TypeError: Cannot read property 'createCredential' of undefined
    at getMDSMetadataForTestCase.then.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:4086:38)
    at <anonymous>

**Comment by herrjemand** [comment]
Resolved in v0.10.106
