### ISSUE TITLE
Server_Metadata Service Test Resp_1 F-4

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#341]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
V0.10.935

## What is the OS and the version are you running?
MacOS v10.13.3

## Issue description

Certificate chain of Metadata Service Test Resp_1 F-4 seems to be normal data.
F-4 requires "certificate chain can not be verified, and check that server"
but, the normal metadata is coming up.

So the server have to check for errors, but, it is passing normally.

Could you confirm it please?

**Comment by herrjemand** [comment]
@BoReumJung There are five endpoints. One of them can not be verified due to bad certificate chain. You must reject it
