### ISSUE TITLE
ServerAuthenticatorAssertionResponse-Resp-3, F-5

### ISSUE THREAD

**Issue by YongWoo76** [fido-alliance/conformance-tools-issues#343]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.935

## What is the OS and the version are you running?

Windows 7

## Issue description

authenticatorData.counter's byte order is 'little endian'

ex [ 40, 0, 0, 0 ]

**Comment by herrjemand** [comment]
Resolved in v0.10.106
