### ISSUE TITLE
Invalid testing signConter less than 0 in registration

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#344]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.935

## What is the OS and the version are you running?

Windows 10

## Issue description

According to specification(https://www.w3.org/TR/webauthn/#sec-authenticator-data ), the signCounter is a 32-bit unsigned big-endian integer, which can not contain negative value.

In the spec below says....

===================WebAuthn API Spec========================
If the authenticator supports:

a global signature counter
        - Use the global signature counter's actual value when generating authenticator data.

a per credential signature counter
        - allocate the counter, associate it with the new credential, and initialize the counter value as zero.

no signature counter
        - let the signature counter value for the new credential be constant at zero.

======================================================

It means that a server can not check whether a received signConter is negative value since the negative value in byte array is converted to a positive value due to unsigned int restrictions

I think that testing signConter less than 0 in registration is not possible for the server in the case of "a global siganture counter" because the signCounter can be any large positive number that can be misled in less than 0 testing case.

**Comment by herrjemand** [comment]
Resolved in v0.10.106
