### ISSUE TITLE
Invalid signCounter in authentication test.

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#345]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.935

## What is the OS and the version are you running?
Windows 10

## Issue description

F-5 Send ServerAuthenticatorAssertionResponse with authenticatorData.counter is not increased, and check that server returns an error
  - The signCounter is increased. So our server responds ok.
1. Registration_SignCounter : 75(0x0000004B) , Authentication_SignCounter : 1258291200(0x4B000000)
2. Registration_SignCounter : 25(0x00000019) , Authentication_SignCounter : 419430400(0x19000000)
3. Registration_SignCounter : 127(0x0000007F) , Authentication_SignCounter : 2130706432(0x7F000000)
4. Registration_SignCounter : 125(0x0000007D) , Authentication_SignCounter : 2097152000(0x7D000000)

**Comment by herrjemand** [comment]
@sangraecho What is the issue?

**Comment by herrjemand** [comment]
Resolved in v0.10.106
