### ISSUE TITLE
Server-ServerAuthenticatorAssertionResponse-Resp-3 P-1, F-6

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#347]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
V.0.10.945

## What is the OS and the version are you running?
mac v10.13.3

## Issue description
[P-1] Send a valid ServerAuthenticatorAssertionResponse, for the authenticator that does not support counter(counter is always 0), and check that server succeeds

I think, username and displayName variable should be added at the line 37 in the Server-ServerAuthenticatorAssertionResponse-Resp-3.js

![serverauthenticatorassertionresponse-resp-3](https://user-images.githubusercontent.com/27984632/43572827-5ce94046-967b-11e8-8731-c586c41e769b.PNG)

[F-6]  For authenticator that DOES NOT supports counter: Send ServerAuthenticatorAssertionResponse with authenticatorData.counter increased, and check that server returns an error

I think, signatureBaseBuffer (signatureBaseBuffer = mergeArrayBuffers(authData, clientDataHash);) should be added at the line 263 in ctap2Authenticator.js.
This is because the authData corresponding to modifiers in the ‘if’ sentences is not mergeArrayBuffers, the signatureBaseBuffer is not created.

![makecredential_signaturebasebuffer_add](https://user-images.githubusercontent.com/27984632/43572839-640caf3e-967b-11e8-9097-4d615fda2ac8.PNG)

could you confirm it please?

**Comment by herrjemand** [comment]
Yes, you are correct! Thank you @BoReumJung!

Resolved in v0.10.106
