### ISSUE TITLE
There is a problem with the CRL file published on the TEST MDS server.

### ISSUE THREAD

**Issue by yiduds** [fido-alliance/conformance-tools-issues#348]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.10.945

## What is the OS and the version are you running?

windows 10

## Issue description

I checked the CRL file posted on the MDS server.
(https://fidoalliance.co.nz/mds/crl/MDSCA-1.crl)

**CRL processing fails because the ASN.1 encoding of the CRL file is invalid.
Please modify the tag value of the extension field when encoding the CRL.**

**- Standard document See**

RFC 3280 defines a specification for the X509 CRL.(http://www.ietf.org/rfc/rfc3280.txt)

![1](https://user-images.githubusercontent.com/39076610/43573591-0ca5b702-967d-11e8-8f36-3d1d160630d9.png)

**- CRL analysis**
** As in the red part above
In ASN.1 encoding, the tag value of the extended field in the CRL is 0.
However, the extended field tag value of the CRL you sent is encoded as 3.**

![2](https://user-images.githubusercontent.com/39076610/43573702-575a2634-967d-11e8-97e2-653aee85824f.png)

The above file is a malformed file. When opening a file in Windows, the following error is displayed.

![3](https://user-images.githubusercontent.com/39076610/43573847-aa72a10c-967d-11e8-8e6a-23dc1b3ae852.png)

**For normal processing You should encode the above encoding [3] to [0].**

![4](https://user-images.githubusercontent.com/39076610/43573943-dd6ba982-967d-11e8-8cbf-e797bf9c6417.png)

Please check the contents and take measures.

thank you.

**Comment by herrjemand** [comment]
I am sorry but I can't reproduce that @yiduds 

https://lapo.it/asn1js/#308201E030820186020101300A06082A8648CE3D0403023067310B300906035504061302555331163014060355040A0C0D4649444F20416C6C69616E636531273025060355040B0C1E46414B45204D6574616461746120544F43205369676E696E672046414B453117301506035504030C0E46414B452043412D312046414B45170D3138303230313030303030305A170D3232303230313030303030305A3081C0302E020F04806749DE307BBD5175A26D73F5F3170D3136303431333030303030305A300C300A0603551D1504030A0100302E020F04AADCAC091764FEE205856C9A599C170D3137303332353030303030305A300C300A0603551D1504030A0100302E020F04CFE24590A0338E069924FBF0C9C1170D3136303330313030303030305A300C300A0603551D1504030A0100302E020F04311C62A204B0EB7B4C069CF01F53170D3138303332353030303030305A300C300A0603551D1504030A0100A32B3029300A0603551D140403020101301B0603551D2304144D6ECD2266227A9ADB8A87126E8C107BC65C8F38300A06082A8648CE3D040302034800304502202A68FAA3D1A5B1C5FBFDAEF0F9A4B102C1185DFCB6361A22BB2D45C8CACA84BB022100DCE9AEB76B3D446C941D12BAC49A7EAEF300F9591D001915274F44DD2485A051
