### ISSUE TITLE
Invalid encoding of a metadata downloaded from URL on MDS TEST.

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#349]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.106

## What is the OS and the version are you running?
Windows 10

## Issue description
- In the MDS specification, this URL must point to the base64url encoding of the UTF-8 representation of the JSON encoded metadata statement as defined in [FIDOMetadataStatement].
- https://drafts.fidoalliance.org/fido-2/all/pr/573/all/fido-v2.0-wd-20180802-13.12.44-build571/fido-metadata-service-v2.0-wd-20180802.html#widl-MetadataTOCPayloadEntry-url

- But the downloaded metadata statement from the url is in JSON encoded instead of base64url encoded.
![image](https://user-images.githubusercontent.com/5744623/43624025-bb055742-971f-11e8-940e-a271a127e653.png)

**Comment by herrjemand** [comment]
Thanks @sangraecho. Resolved!
