### ISSUE TITLE
Testing MDS service procedure is absent

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#350]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.106

## What is the OS and the version are you running?

Window 10

## Issue description

In Metadata testing, I have come across five endpoints as follows:

![image](https://user-images.githubusercontent.com/5744623/43629714-ff50b5e0-9738-11e8-952b-3a3e1be968e8.png)

There should be some procedure described to test MDS Service for server. Otherwise it is extremely difficult to guess how the server handle those five endpoints since there will be only one MDS endpoint in normal situation.

I think MDS testing procedure should be specified in Server Requirements and Transport Binding Profile spec for clear testing instructions.

**Comment by herrjemand** [comment]
@sangraecho You can find processing procedures here: https://drafts.fidoalliance.org/fido-2/latest/fido-metadata-service-v2.0-wd-20180731.html#metadata-toc-object-processing-rules

Actually from FIDO ecosystem perspective, FIDO server must support multiple endpoints.

Regards. Yuriy

**Comment by sangraecho** [comment]
In the spec you have sent me, the following is the first step and it says "download the latest metadata TOC object from the well-known URL". This is why I assumed that there will be a single endpoint.
I think the spec should be changed to reflect the multiple MDS endpoints to be handled by the server.

The FIDO Server must be able to download the latest metadata TOC object from the well-known URL, when appropriate. The nextUpdate field of the Metadata TOC specifies a date when the download should occur at latest.
