### ISSUE TITLE
Server-ServerAuthenticatorAttestataionResponse-Resp-B "android-safetynet" P-1

### ISSUE THREAD

**Issue by BoReumJung** [fido-alliance/conformance-tools-issues#351]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.106

## What is the OS and the version are you running?
macOS v10.13.3

## Issue description

When I try to test the case, it's failed to verify chain of certificate.
The aaguid that have a this problem is "c87cdd9756c149b89e24cb363654f350".
As you know, There is 4 certificates in the metadata's attestationRootCertificates field.
But, I can't verify using them.
So I was wondering if it's correct to issue certificate using one of the them.
and also I was wondering if the previous issue( #343 ) is fixed. 
I supposed that the issue is related to this problem.

**Comment by herrjemand** [comment]
@BoReumJung Please press "download metadata" and update your metadatas
