### ISSUE TITLE
Server-ServerAuthenticatorAssertionResponse-Resp-3 F-6

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#353]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.106

## What is the OS and the version are you running?
Windows 10

## Issue description
For authenticator that DOES NOT supports counter: Send ServerAuthenticatorAssertionResponse with authenticatorData.counter increased, and check that server returns an error

Test results.
- The signCounter for registration is zero. (0)
- The signCounter for authentication is a number greater than zero. (73)

Problem with this test.
- The Authenticator sent a signCounter for registration to 0, the server can not assume that its Authenticator does not support signCounter.
- According to the specification below, the signCounter for registration is set to zero except for the global signCounter.
![image](https://user-images.githubusercontent.com/5744623/43688144-7dfc94cc-991e-11e8-8c1f-b012e8c3c989.png)

Can the server know how this authenticator does not support signCounter?

**Comment by herrjemand** [comment]
@sangraecho Authr start with 0, but when first signature is produced, and authr supports counter, it increments it, and returns 1.

> Increment the credential associated signature counter or the global signature counter value, depending on which approach is implemented by the authenticator, by some positive value. If the authenticator does not implement a signature counter, let the signature counter value remain constant at zero.
https://w3c.github.io/webauthn/#op-get-assertion

**Comment by herrjemand** [comment]
@sangraecho I understand your confusion so I've opened an issues: https://github.com/w3c/webauthn/issues/1025
