### ISSUE TITLE
"https://fidoalliance.co.nz/mds" can not be accessed. 502 Bad Gateway.

### ISSUE THREAD

**Issue by jksc81** [fido-alliance/conformance-tools-issues#354]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.106(BETA)

## What is the OS and the version are you running?

Windows7

## Issue description

"https://fidoalliance.co.nz/mds" can not be accessed. 

502 Bad Gateway.

**Comment by herrjemand** [comment]
Sorry. We were down for maintenance. Now resolved
