### ISSUE TITLE
Server-ServerAuthenticatorAssertionResponse-Resp-3 F-6

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#359]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.106

## What is the OS and the version are you running?

Windows 10
## Issue description

The following test can not be successfully passed in the server.

Server-ServerAuthenticatorAssertionResponse-Resp-3 F-6

![image](https://user-images.githubusercontent.com/5744623/43761574-7332bf10-9a60-11e8-843b-562b56766b02.png)

The test tool assumes that sign counter returns 1 when authentication at first is done. 

 - start with 0, but when first signature is produced, and authr supports counter, it increments it, and returns 1. (Yuriy's comment)

The below is the webauthn spec. It says a counter can be incremented by some positive value, which means it can be 1 or any number bigger than 1.

Increment the credential associated signature counter or the global signature counter value, depending on which approach is implemented by the authenticator, by some positive value. If the authenticator does not implement a signature counter, let the signature counter value remain constant at zero.
https://w3c.github.io/webauthn/#op-get-assertion

So, when the test returns the sign counter with 73, the server has to verify the authenticator successfully according to the spec since the returned counter value is greater than 0.

**Comment by herrjemand** [comment]
This test was removed. Thanks @sangraecho
