### ISSUE TITLE
JWS signature is invalid for MDS TEST (F-5, F-6)

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#360]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.106

## What is the OS and the version are you running?
Windows 10

## Issue description

Test cases related to this issue.
- F-5 Send a valid ServerAuthenticatorAttestationResponse with FULL "packed" attestation for metadata from MDS who's metadata service intermediate certificate is revoked, and check that server returns an error.
- F-6 Send a valid ServerAuthenticatorAttestationResponse with FULL "packed" attestation for metadata from MDS who's metadata service leaf certificate is revoked, and check that server returns an error

Please make sure that the JWS signature is generated correctly. 

Also, please make sure that the certificate chain for testing is configured correctly.
All certificates configured in the Certificate chain are not included in the CRL file.

**Comment by herrjemand** [comment]
@sangraecho That's the point. Some payloads have their signatures invalid and certificate revoked *)

**Comment by herrjemand** [comment]
Resolved in v0.10.108
