### ISSUE TITLE
The certificate chain is normal for MDS F-4 tests

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#361]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.106

## What is the OS and the version are you running?
Windows 10

## Issue description

Test cases related to this issue.
- F-4 Send a valid ServerAuthenticatorAttestationResponse with FULL "packed" attestation for metadata from MDS who's certificate chain can not be verified, and check that server returns an error

The following information was used for the F-4 test.
- aaguid : 2038d423-cbb4-44cf-893a-755848a62cd6
- mdsURL : https://fidoalliance.co.nz/mds/execute/e5448623efda39407a691e087d26696c2055a708e3bf4f3f7239869febbfb5fa
- I confirmed that the rest of MDS endpoints does not have metadata for this aaguid.

The figure below shows the tested certificate path.
- I think the certificate path is correct.
- Please confirm that the certificate path is generated correctly for testing.

MDS's TrustAnchor Certificate

![image](https://user-images.githubusercontent.com/5744623/43764424-63d99d24-9a68-11e8-8a21-14374595aca8.png)

MDS's Certificate Chain

![image](https://user-images.githubusercontent.com/5744623/43764434-67a45ed0-9a68-11e8-9fe8-cb666cc7106c.png)

![image](https://user-images.githubusercontent.com/5744623/43764440-6b084294-9a68-11e8-9771-66c8b57afe28.png)

**Comment by hueno-ttic** [comment]
@herrjemand 
I am dealing with the same problem.
I tried using v0.10.107, but it seemed that the corresponding part did not change.
Please tell me what is going on with this problem.

**Comment by herrjemand** [comment]
Resolved in v0.10.108
