### ISSUE TITLE
Fido2 Conformance Test Tool: CTAPHID_LOCK (0X04) should have BCNT=1

### ISSUE THREAD

**Issue by NickHHC** [fido-alliance/conformance-tools-issues#363]
### What protocol and version of the protocol are you testing?
FIDO2 v2.0

### What is your implementation class?
ASM+Authr

### What is the version of the tool are you using?
fido2-conformance-module : v0.10.106

### What is the OS and the version are you running?
WIN10 (17134)

## Issue description
Test case: HID-1 Test CTAP2 HID support:P-12/P-13
The lock command should have BCNT=1 while tool sends it with BCNT=0.

### Tool log
![1](https://user-images.githubusercontent.com/21193729/43820043-96bc1528-9b17-11e8-802e-910183eddc90.JPG)

### Specification
![2](https://user-images.githubusercontent.com/21193729/43820064-b2a5deb8-9b17-11e8-9d8e-527e1734d871.JPG)

**Comment by herrjemand** [comment]
@NickHHC Thanks for that. Resolved in v0.10.108
