### ISSUE TITLE
ERROR DOMException #1

### ISSUE THREAD

**Issue by herrjemand** [fido-alliance/conformance-tools-issues#364]
What protocol and version of the protocol are you testing?
FIDO2

What is the OS or Browser and the version are you running?
Chrome browser v 69.0.3497.23 beta (64bit)
firefox : 62.0b13(62bit)

** Issue description**
Chrome browser v 69.0.3497.23 beta (64bit) :
error : DOMException: The relying party ID 'https://dev-yus.ydentity.net:9486' is not a registrable domain suffix of, nor equal to 'https://dev-yus.ydentity.net:9486'.

EDGE browser : securityError code:18

FireFox : DOMException : " The operation is insecure"

It occured error when runnung "navigator.credentials.create".

**Comment by herrjemand** [comment]
cc @jazmandorf

**Comment by herrjemand** [comment]
@jazmandorf can you give me a copy of your server request?

**Comment by jazmandorf** [comment]
Hi Yuriy!!
I was solved it.
I have a question.


already exist user occured type error invalid syntax when
"navogator.credentials.create".
How to de-reg user at browser?

thanks
Best regards.

2018-08-09 1:51 GMT+09:00 Ackermann Yuriy <notifications@github.com>:

**Comment by ranjankhanna** [comment]
What was the solution?
