### ISSUE TITLE
Fido2 Conformance Test Tool: a properer error code 

### ISSUE THREAD

**Issue by NickHHC** [fido-alliance/conformance-tools-issues#365]
## What protocol and version of the protocol are you testing?

FIDO2 V2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?

fido2-conformance-module : v0.10.106

## What is the OS and the version are you running?

WIN10 (17134)

## Issue description

Test case: Authr-Reset-1 Test authenticator support of Reset command: p-1
Test case requires to get CTAP2_ERR_NO_CREDENTIALS when send a valid CTAP2 GetAssertion with previous registered credential ID.
It seems CTAP2_ERR_INVALID_CREDENTIAL is more proper for me.
what do you people think?

**Comment by herrjemand** [comment]
1. Locate all credentials that are eligible for retrieval under the specified criteria:
If an allowList is present and is non-empty, locate all denoted credentials present on this authenticator and bound to the specified rpId.
If an allowList is not present, locate all credentials that are present on this authenticator and bound to the specified rpId.
Let numberOfCredentials be the number of credentials found.

8. If no credentials were located in step 1, return CTAP2_ERR_NO_CREDENTIALS.

https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html#authenticatorMakeCredential

**Comment by NickHHC** [comment]
There is credential in step 1 but invalid!!!!!!
