### ISSUE TITLE
FIDO Conformance Tool error : TypeError : cannot read property 'protocolFamily' of undefined

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#367]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.107

## What is the OS and the version are you running?
windows 10

## Issue description

TypeError is generated as shown in the figure below. 
So we can not proceed with the EDDSA_SH512 algorithm test.
please check.

![image](https://user-images.githubusercontent.com/5744623/43943540-e4a7f234-9cb6-11e8-8325-a81aaec51e12.png)

**Comment by herrjemand** [comment]
Resolved in v0.10.108
