### ISSUE TITLE
Authr-MakeCred-Req-4 : F-3, F-4 and F-5 can not set property "alg" / "type" of undefined

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#368]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.107

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
Please have a look on the attached screenshot.

![capture](https://user-images.githubusercontent.com/29768798/43956528-404c4928-9cad-11e8-8b4e-18b1f60006ac.PNG)

**Comment by herrjemand** [comment]
@eugenIFX try v0.10.947 in Experimental.
