### ISSUE TITLE
NFC-1 P-1 : wrong expected response for version string

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#369]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.10.107

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
I think for FIDO2 authenticator, you should expect to receive "FIDO_2_0".

![capture](https://user-images.githubusercontent.com/29768798/43958551-7a0ccc44-9cb4-11e8-8933-68ecf2183b7d.PNG)

**Comment by herrjemand** [comment]
@eugenIFX Try v0.10.947 in experimental *)
