### ISSUE TITLE
The test tool sends valid certificate chain

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#371]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.108

## What is the OS and the version are you running?

Windows 10

## Issue description

This issue has been raised before and closed due to resolved flag.

However, the updated test tool still sends a server a valid certificate chain instead of invalid one.

![image](https://user-images.githubusercontent.com/5744623/44081191-19146bb2-9fe9-11e8-8fcd-ca903dad0f2f.png)

**Comment by herrjemand** [comment]
@sangraecho I can't reproduce this issue.

**Comment by sangraecho** [comment]
Can you please put any invalid certificate in the chain to fail verification in the server?
The certificate chain you are using in this test is valid certificate chain.

**Comment by sangraecho** [comment]
Can you please send me the certificate chain that is used in F-4 test case?
The certificate chain my server stored after F-4 is valid.

**Comment by sangraecho** [comment]
![image](https://user-images.githubusercontent.com/5744623/44193701-ae724900-a16e-11e8-88b1-059f0dff83c5.png)

We have check the every attestation certificate chain in MDS test and come to a conclusion that there is strong evidence that the tool is using the same valid certificate chain in both positive (P-1) and negative (F-4) test.

I have attached the attestation certificate chain at the below.
[attestation certificate chain.zip](https://github.com/fido-alliance/conformance-tools-issues/files/2292710/attestation.certificate.chain.zip)

**Comment by herrjemand** [comment]
@sangraecho Okay, I finally pinned it down.  Will  be updated in the few hours.  You will need to obtain new endpoints though.

Sorry for the  delay
