### ISSUE TITLE
Unable to verify the attestation certificate chain

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#372]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

 v0.10.108

## What is the OS and the version are you running?

Windows 10

## Issue description

The test is supposed to send a server a valid set of attestation certificate chain but the server failed to verify the certificate chain due to incorrect basic constraints in the root certificate.

![image](https://user-images.githubusercontent.com/5744623/44081436-ac1113f2-9fe9-11e8-9bb1-2ab284bb8ddd.png)

The below is the attestation root cert and its basic constraints is True and path length is 0.
Root certificate must have path length set either some positive number (in this case 1) or none.

![image](https://user-images.githubusercontent.com/5744623/44081602-135d499a-9fea-11e8-92c1-91f0b1442026.png)

**Comment by herrjemand** [comment]
Will be resolved in the next hour. Thanks for that @sangraecho
