### ISSUE TITLE
SVR-SvrAuthAttResp-Resp-5, F10 - attStmt x5c containing full chain?

### ISSUE THREAD

**Issue by YongWoo76** [fido-alliance/conformance-tools-issues#373]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.108

## What is the OS and the version are you running?
Windows 10

## Issue description
the test case send x5c [ C1, C2, C-Root ]
so server return error.

is it correct test?
but we can not found any description on the fido2 specifications.

**Comment by herrjemand** [comment]
Yes, you must return an error, since you won't be able to verify certificate chain with two root certs.

Regards. Yuriy
