### ISSUE TITLE
FIDO2 Non-MDS tests do not have registered AAGUIDs in MDS

### ISSUE THREAD

**Issue by tfvbhy** [fido-alliance/conformance-tools-issues#374]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.10.108

## What is the OS and the version are you running?
Windows 7

## Issue description
MakeCredentials Response tests use AAGUIDs not in MDS. Positive test cases fail because metadata of such tests cannot be found/verified.

**Comment by herrjemand** [comment]
@tfvbhy To obtain metadata, please press "Download Metadata" 
<img width="354" alt="screenshot 2018-08-14 19 24 53 4" src="https://user-images.githubusercontent.com/1636116/44208770-53822700-a159-11e8-9c70-47408025d61a.png">

**Comment by dawid-nowak** [comment]
@tfvbhy 
I would agree here that even the test authenticators should be in MDS. 
Otherwise, the server has to deal with two distinctive paths. One for certification and one for business operation. If all certs are in the MDS there is no need to read server metadata from a file.

**Comment by herrjemand** [comment]
@tfvbhy Servers must have an ability to add Metadata directly or/and use MDS
