### ISSUE TITLE
MetaDataService Test Problem  (F4~F6) - v0.10.108

### ISSUE THREAD

**Issue by changsik** [fido-alliance/conformance-tools-issues#378]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server
## What is the version of the tool are you using?
v0.10.108

## What is the OS and the version are you running?
windows10

## Issue description
Problem
    =>  https://fidoalliance.co.nz/mds/getTestMetadata 500 (Internal Server Error)
    

![mds](https://user-images.githubusercontent.com/689859/44190590-6f3dfb00-a162-11e8-95e4-f5205c68d0a3.PNG)

![getmetadata](https://user-images.githubusercontent.com/689859/44190601-7bc25380-a162-11e8-99cc-a88350319df6.PNG)

![error](https://user-images.githubusercontent.com/689859/44190604-7fee7100-a162-11e8-8ec0-be1d1b906487.PNG)

**Comment by herrjemand** [comment]
@changsik Thanks for that. This issue will be resolved in few hours when changes propagate to the server. Please advice that you will need to obtain new endpoints.

Regards. Yuriy
