### ISSUE TITLE
Appears to be a problem with mds URLs

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#379]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## Issue description

Attempting to pull metadata from mds location. 
I had downloaded and imported MDSROOT.crt into my keystore as well.

Here is the error:
This tool requires network connectivity to download the TOC and subsequently the metadata statements.
Properties file parsed!
URL for the location of Metadata TOC looks good!
Input Validation Complete!
Retrieving TOC using Mode : MDS 1.0 and URL : https://fidoalliance.co.nz/mds/execute/03ddb961e7a5d30df7380610b8469f6789361b25d9ab73dddef3f0fbe41af470
Root certificate is valid!
TOC successfully obtained from https://fidoalliance.co.nz/mds/execute/03ddb961e7a5d30df7380610b8469f6789361b25d9ab73dddef3f0fbe41af470
Error in processing: Exception: Certificate Validation Failed.  Validation failed on certificate number: 0. Details: subject/issuer name chaining check failed

**Comment by jenkay** [comment]
Hi Yuriy,
yeah, different error now:

Error in processing: Exception: Certificate Validation Failed.  Validation failed on certificate number: -1. Details: Path does not chain with any of the trust anchors

**Comment by herrjemand** [comment]
@jenkay Can you regenerate endpoints?

**Comment by jenkay** [comment]
Will you reopen the issue? I've refreshed 3x and the endpoints are still the same, and I still receive the same error in my last reply.

**Comment by jenkay** [comment]
Also, I've been downloading a new MDSROOT.crt every time to see if that's got anything to do with it.

**Comment by herrjemand** [comment]
@jenkay I will double check this issues

**Comment by herrjemand** [comment]
@jenkay I've regenerated PKI infrastructure. Working now. Sorry for that

Regards. Yuriy
