### ISSUE TITLE
Metadata TOC object validation error.

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#383]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v.0.10.108

## What is the OS and the version are you running?
windows 10

## Issue description

All of these issues occurred while validating the Metadata TOC object.

1. No issuer certificate for certificate in certification path found.
-- The cases where this issue occurs are P-1, F-1, F-2, and F-4.
-- The certificate chain included in the JWT Header is incorrect. 
-- The certificate chain consisted of two certificates. However, there are no CA certificates, and they are all leaf certificates.
-- This is the mdsUrl used to test P-1.
https://fidoalliance.co.nz/mds/execute/f25e7e310850c95e8cbb571329bae6f1da072a06c45156901a08761a7f3b4e81
-- I have attached the certificate chain at the below.
[mdsCertChain.zip](https://github.com/fido-alliance/conformance-tools-issues/files/2299001/mdsCertChain.zip)

2. JWS signature is invalid
-- The cases where this issue occurs are F-3, F-5, and F-6.
-- This is the mdsUrl used to test F-6.
https://fidoalliance.co.nz/mds/execute/c3318951d5ae21e8da947e3a82543a78d72b6a0cc557184ce22b40a4ab4ffb95

**Comment by herrjemand** [comment]
@sangraecho There are should be 4 JWT with invalid payloads. I am checking P-1 right now

**Comment by herrjemand** [comment]
@sangraecho Okay I've regenerated PKI infrastructure. Please obtain new endpoints and try again.

Sorry for that.
