### ISSUE TITLE
The attestation root cert is not validated due to wrong path length

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#384]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

EXPERIMENTAL/v0.10.918/

## Issue description

This issue has been raised before and it was supposed to be resolved but not.

The test is supposed to send a server a valid set of attestation certificate chain but the server failed to verify the certificate chain due to incorrect basic constraints in the root certificate.

![image](https://user-images.githubusercontent.com/5744623/44420981-391ec380-a534-11e8-945f-aea372d46bf7.png)

The attestation root cert still has its basic constraints is True and path length is 0.
Root certificate must have path length set either some positive number (in this case 1) or none.

**Comment by dawid-nowak** [comment]
@sangraecho 
this seems to be working for me at least as far as the version 0.10 beta is concerned
you can see the code at https://github.com/Mastercard/fido2-rp-spring/tree/feature/testing-against-0.10.0 class AndroidKeyAttestationProcessor

**Comment by sangraecho** [comment]
This is not about the code that caused the problem.
Basic constrains in the root certificate has wrong path length value as 0.

![image](https://user-images.githubusercontent.com/5744623/44422446-08d92400-a538-11e8-9b35-b45f48130dc0.png)
 
Root certificate must have path length set either some positive number (in this case 1) or none.

**Comment by dawid-nowak** [comment]
not sure if this document will muddy the waters even more :) 
http://www.pkiglobe.org/

i am not saying that the cert is correct or not
but it seems to be implying that there is no more CA certs expected in the path and if there is a next cert in the path it has to be end-cert. 

for a root cert, I would probably expect subjecttype=end entity

**Comment by sangraecho** [comment]
The following is the certificate chain I got from the test.
[cert chain.zip](https://github.com/fido-alliance/conformance-tools-issues/files/2307828/cert.chain.zip)

As you can see, there is an intermediate ca certificate after the root certificate.
Therefore, path length in the root certificate should not be 0.
Microsoft Certificate Manager in Windows failed to validate the above cert chain due to path length = 0.

**Comment by dawid-nowak** [comment]
not sure, generally server should return an error if the certificate chain is re-ordered and when the root cert is part of the attestation.

**Comment by herrjemand** [comment]
@sangraecho Yes, you are correct. I missed the certificate in metadata. Will be updated in the next build.

**Comment by sangraecho** [comment]
Can you please make sure that the path length in basic constraints of the root certificate from metadata is set to 1 or none?

Otherwise the certificate chain validation is going to be failed in the server again.

**Comment by herrjemand** [comment]
Resolved. Next build in an hour
