### ISSUE TITLE
The intermediate certificate is not listed in CRL

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#385]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

/EXPERIMENTAL/v0.10.918/

## Issue description

The test requires a server to check revoked certificate in CRL.

![image](https://user-images.githubusercontent.com/5744623/44421364-21940a80-a535-11e8-9d09-9dc2e9868be5.png)

The intermediate certificate is supposed to be listed in the CRL but not.
So the certificate chain validation is passed in the server.

The following url is mds test url that I tested.
 
https://fidoalliance.co.nz/mds/execute/c4e0391a97da8d5399f7c734c54ce0b9ead4478e49db12c2119b80efc4eb18a9

**Comment by herrjemand** [comment]
Resolved now. Please regenerate your endpoints
