### ISSUE TITLE
The leaf certificate is not listed in CRL

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#386]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

/EXPERIMENTAL/v0.10.918/

## Issue description

This test requires a server to check if the leaf certificate is listed in CRL as a revoked certificate.

![image](https://user-images.githubusercontent.com/5744623/44421673-1a213100-a536-11e8-9ec0-b3960becb9dc.png)

However, the leaf certificate is not listed in CRL

The following is MDS URL that I tested.

https://fidoalliance.co.nz/mds/execute/d34f39904c1d84f555bb826c328e66d458b2beb9ef6edf5c9b139a7d0713c014

**Comment by herrjemand** [comment]
Okay found another issues. Resolved now

**Comment by herrjemand** [comment]
Please regenerate your endpoints

**Comment by Spomky** [comment]
Hi,

Same error for the metadata I receive.
For example, the MDS for the AAGUID [`e96b8a94-578f-4160-9250-2630080f7dc2`](https://fidoalliance.co.nz/mds/metadata/e96b8a94-578f-4160-9250-2630080f7dc2.json) is supposed to fail, but no CRL url is present in the certificate.

**Comment by chrismccaw** [comment]
@Spomky Did you figure this out? I'm hitting the same issue
