### ISSUE TITLE
FIDO2 NFC tests power-cycling authenticator between getNextAssertion

### ISSUE THREAD

**Issue by serianox** [fido-alliance/conformance-tools-issues#389]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authenticator

## What is the version of the tool are you using?

v0.10.108

## Issue description

In test CTAP2 / Options / Resident-Key / P-2 & P-3.
Between getAssertion and getNextAssertion commands, test tool power-cycle the authenticator, which resets the credentialCounter.
The test tool should not power-cycle the authenticator between getAssertion and getNextAssertion, and successive getNextAssertion commands.

**Comment by herrjemand** [comment]
@serianox can you pull the latest fido2-conformance-tests branch?
