### ISSUE TITLE
Problem with MDS negative tests F3,F4,F5,F6

### ISSUE THREAD

**Issue by dawid-nowak** [fido-alliance/conformance-tools-issues#390]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/U2F/FIDO2 v1.0/v1.1/v1.2
FIDO2
## What is your implementation class?

Server/Client/ASM+Authr

## What is the version of the tool are you using?
FIDO Conformance Tools v0.10.108 (BETA)((BETA) FIDO2 )

## What is the OS and the version are you running?
Windows 7

## Issue description
The test tool expects the failure but it doesn't seem to be verifying how the root cause of the failure. For example :
F-4 Send a valid ServerAuthenticatorAttestationResponse with FULL "packed" attestation for metadata from MDS who's certificate chain can not be verified, and check that server returns an error 

Our RP doesn' verify the certificate chain for the MDS and the server returns the error due to some other problem. The tests are marked as passed even though they probably shouldn't.

**Comment by herrjemand** [comment]
@dawid-nowak RP MUST verify certificate chain.

> The FIDO Server must download the certificate (chain) from the URL specified by the x5u attribute [JWS]. The certificate chain must be verified to properly chain to the metadata TOC signing trust anchor according to [RFC5280]. All certificates in the chain must be checked for revocation according to [RFC5280].

https://drafts.fidoalliance.org/fido-2/latest/fido-metadata-service-v2.0-wd-20180814.html#metadata-toc-object-processing-rules

**Comment by herrjemand** [comment]
> The tests are marked as passed even though they probably shouldn't.

Then you would've failed any of the previous tests.

**Comment by dawid-nowak** [comment]
all MDS tests are passing even though I am not doing any cert validation

![image](https://user-images.githubusercontent.com/25728428/44587326-8ad08380-a7aa-11e8-9cc3-ce149c9601f3.png)

conformance tool should not rely on server voluntarily following the specs. an assertion that server has thrown an error is probably not enough to verify that it failed due to cert validation

i think the way to the fix it would be to ensure that valid entries are in toc which you can't validate. this would catch the problem that I am seeing but it will not remove all possible problems

**Comment by dawid-nowak** [comment]
i think this should be re-opened

**Comment by herrjemand** [comment]
@dawid-nowak I can't know if you failed for one reason or another. There are 150 tests that ensure that you only fail the specific combinations.

More tests will be added in the future.

**Comment by dawid-nowak** [comment]
as i said previously, in this specific use case you can. 
if all entries are valid in the TOC but the only thing that is wrong is the cert path/etc you know that the server has not validated the TOC because it has returned success. 

because the invalid entries are in the TOC that is also not certified certification tool can't figure out the root cause

**Comment by dawid-nowak** [comment]
But it shouldn't. The error was due to the structure of the TOC file and
not the problem with validating it. If the structure was correct the server
would return success and the tests would fail.

**Comment by herrjemand** [comment]
How would I know that? In regards: What exact are issues you are experiencing?

**Comment by dawid-nowak** [comment]
See image for the reason the server is failing. **status": "FIDO_CERTIFIED_L2plus"** is not a valid status
![image](https://user-images.githubusercontent.com/25728428/44599087-13f8b200-a7cd-11e8-8517-8f0cdc7c48ae.png)


I think you will need a TOC file, which is not signed but has correct statuses and correct format. And another TOC file which is signed but there are problems with statuses.

**Comment by herrjemand** [comment]
@dawid-nowak What exactly wrong with this block?

**Comment by dawid-nowak** [comment]
The authenticator status enum is wrong.

**Comment by herrjemand** [comment]
@dawid-nowak 

enum AuthenticatorStatus {
    "NOT_FIDO_CERTIFIED",
    "FIDO_CERTIFIED",
    "USER_VERIFICATION_BYPASS",
    "ATTESTATION_KEY_COMPROMISE",
    "USER_KEY_REMOTE_COMPROMISE",
    "USER_KEY_PHYSICAL_COMPROMISE",
    "UPDATE_AVAILABLE",
    "REVOKED",
    "SELF_ASSERTION_SUBMITTED",
    "FIDO_CERTIFIED_L1",
    "FIDO_CERTIFIED_L1plus",
    "FIDO_CERTIFIED_L2",
    "FIDO_CERTIFIED_L2plus",
    "FIDO_CERTIFIED_L3",
    "FIDO_CERTIFIED_L3plus"
};

**Comment by herrjemand** [comment]
@dawid-nowak What document are you using? Here is from FIDO2 specs:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html#statusreport-dictionary

**Comment by dawid-nowak** [comment]
thanks, unfortunately, I was using an older version returned by Google. apologies for the confusion.

i suppose it might be of benefit to add an info page to the certification tool to specify which specs are used as a reference with links perhaps. to avoid confusion such as mine.

**Comment by herrjemand** [comment]
@dawid-nowak Will do in future versions. Lot's more UI work to be done *)
