### ISSUE TITLE
Conformance tools fido-conformance-tools-electron-win32-x64-0.10.109-installer.msi seems to be installing FIDO Conformance Tools v0.10.108 (BETA)((BETA) FIDO2 )

### ISSUE THREAD

**Issue by dawid-nowak** [fido-alliance/conformance-tools-issues#391]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/U2F/FIDO2 v1.0/v1.1/v1.2
FIDO2
## What is your implementation class?

Server/Client/ASM+Authr

## What is the OS and the version are you running?
Windows 7

## Issue description

Latest and greatest installer downloaded  fido-conformance-tools-electron-win32-x64-0.10.109-installer.msi
but it seems to be installing 
FIDO Conformance Tools v0.10.108 (BETA)((BETA) FIDO2 )
![image](https://user-images.githubusercontent.com/25728428/44585960-f3693180-a7a5-11e8-89a5-eb4d7fa24713.png)

**Comment by herrjemand** [comment]
Okay running rebuild now

**Comment by herrjemand** [comment]
@dawid-nowak Updated the build. Please re-download it again.

Sorry for the inconvenience.
