### ISSUE TITLE
base64string.charCodeAt is not a function

### ISSUE THREAD

**Issue by deanalvero** [fido-alliance/conformance-tools-issues#394]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Client

## What is the version of the tool are you using?

fido-conformance-tools-ionic-v0.9.23.apk

## What is the OS and the version are you running?

Android 8.0.0 (Samsung Galaxy S9)

## Issue description

The test case: Protocol-Reg-Resp-3 Test the AuthenticatorRegistrationAssertion SEQUENCE P-3 passes when only one TAG_ATTESTATION_CERT is sent.

When sending more than 1 TAG_ATTESTATION_CERT, it fails and gives out this error: Error: base64string.charCodeAt is not a function.

https://fidoalliance.org/specs/fido-uaf-v1.1-ps-20170202/fido-uaf-authnr-cmds-v1.1-ps-20170202.html#tag_uafv1_reg_assertion

**Comment by herrjemand** [comment]
Resolved in v0.10.111
