### ISSUE TITLE
UAF Deregistration test with long KeyIDs

### ISSUE THREAD

**Issue by armenan** [fido-alliance/conformance-tools-issues#397]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Client

## What is the version of the tool are you using?

v0.9.23

## What is the OS and the version are you running?

iOS

## Issue description

When running conformance tool for UAF 1.1 and selecting Deregistration tests it fails:
F-7 Send Deregistration request- is failed
AssertionError: Expected PROTOCOL_ERROR (0x06) error. Received UNKNOWN(255): expected 255 to equal 6...

This happens when conformance tool during Deregistration request to FIDO client sends KeyID longer than 32 bytes, but still in [32...2048] range.

According to NORMATIVE [section](https://fidoalliance.org/specs/fido-uaf-v1.1-ps-20170202/fido-uaf-protocol-v1.1-ps-20170202.html#keyid-typedef) of FIDO UAF Protocol specification the KeyID length is in the range of [32...2048].
Thus expecting PROTOCOL_ERROR when the KeyID length is OUT of this range is Ok.

However conformance tool should NOT expect PROTOCOL_ERROR when KeyID is longer than 32 bytes, but still in [32...2048] range. Depending on authenticator type and implementation it may fail with UNKNOWN (or other) error or it may succeed.

Same requirements from conformance tool should be expected for UAF 1.0 and 1.2.

**Comment by herrjemand** [comment]
For first factor authr KeyID is a hash of a keyHandle, thus must be exactly 32bytes.
For 2nd factor authr keyID is the keyHandle, so can be max of 2048 bytes.

**Comment by armenan** [comment]
The [7. KeyIDs and key handles](https://fidoalliance.org/specs/fido-uaf-v1.1-ps-20170202/fido-uaf-authnr-cmds-v1.1-ps-20170202.html#keyids-and-key-handles) section suggests that for 2nd factor bound authenticators KeyID still should be a 32 bytes long (random or the hash of keyHandle).
Then it suggest for 2nd factor roaming authenticator KeyID is the keyHandle.
However that entire section is NON-NORMATIVE (i.e. actually it is up to the authenticator and ASM).

Looks like there are only 2 NORMATIVE requirements from the spec:
1. KeyID length is in [32...2048] range
2. If KeyID is not the key handle itself, the length must be 32 bytes

Why conformance-tool should enforce NON-NORMATIVE definitions from the spec?

**Comment by herrjemand** [comment]
From UAF AuthrCMDs specs:

> If KeyID is not the key handle itself (e.g. such as in case of a second-factor roaming authenticator) - it must be a unique and unguessable byte array with a maximum length of 32 bytes. It must be unique within the scope of the AAID.

> 7. If AuthenticateIn.keyIDs is not empty,

> 7.1 If this is a bound authenticator, then look up ASM's database with AuthenticateIn.appID and AuthenticateIn.keyIDs and obtain the KeyHandles associated with it.
Return UAF_ASM_STATUS_KEY_DISAPPEARED_PERMANENTLY if the related key disappeared permanently from the authenticator.
Return UAF_ASM_STATUS_ACCESS_DENIED if no entry has been found.

> 7.2 If this is a roaming authenticator, then treat AuthenticateIn.keyIDs as KeyHandles

So there for KeyID for bound authr, is not keyHandle, and so must be exactly 32bytes long.
