### ISSUE TITLE
ECDSA signature verification failures

### ISSUE THREAD

**Issue by andychan1998** [fido-alliance/conformance-tools-issues#399]
## What protocol and version of the protocol are you testing?

UAF v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.0

## What is the OS and the version are you running?

macOS Sierra 10.12.6.

## Issue description

Reg-Req-7 (F7) would fail intermittently (1 out of every 3 to 4 times) because of signature verification failure.  I have attached the UAF response message of a failure case here.  I have tried extracting the signed data, public key, and signature from the response, then verify them using the OpenSSL command "openssl dgst -verify pubkey.pem -signature signature.der data.bin", but even that fails, so the problem doesn't seem to be just an implementation error on my part.

[uafResponse.txt](https://github.com/fido-alliance/conformance-tools-issues/files/2421822/uafResponse.txt)

**Comment by andychan1998** [comment]
The same problem also happens with Reg-Resp-8 (P-3).  I have attached the uafResponse message I received.
[uafResponse.bad.txt](https://github.com/fido-alliance/conformance-tools-issues/files/2425523/uafResponse.bad.txt)

**Comment by herrjemand** [comment]
No issue with the tool. Continuing on the emails
