### ISSUE TITLE
Wrong MatchCriteria elements check

### ISSUE THREAD

**Issue by andychan1998** [fido-alliance/conformance-tools-issues#400]
## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.10.110

## What is the OS and the version are you running?

MacOS Sierra (10.12.6)

## Issue description

The checks in Server-Reg-Req-4 (P-3) are wrong.  The attestationTypes should be a sequence of numbers, not just a number.

**Comment by herrjemand** [comment]
Resolved in v0.10.111
