### ISSUE TITLE
Problem in Authr-MakeCred-Resp-2 Test "packed" attestation

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#403]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

Latest

## What is the OS and the version are you running?

Windows 10

## Issue description

I tried to test Authr-MakeCred-Resp-2 Test "packed" attestation with RSA Signature scheme and have the following error.  RSA signature format should be in raw format but the testing tool tried to decode it with ASN.1 DER and gave out the error.

•	P-1 Decode "attStmt" CBOR MAP and: (a) check that "alg" field is presented it matches "alg" in PK (b) check that "sig" field is presented and it is of type BYTE STRING‣
•	P-2 If "x5c" presented: (a) Check that "ecdaaKeyId" is NOT presented (b) Check that "x5c" is of type SEQUENCE (c) Check that metadata statement contains "attestationRootCertificates" field, and it’s not empty. (d) Check that metadata statement "attestationTypes" SEQUENCE contains ATTESTATION_BASIC_FULL(0x3E07) (e) Decode certificate chain (f) If certificate chain does not contain attestationRootCertificates, append them to the chain (g) Verify certificate chain (h) Pick a leaf certificate of the chain and check that: (1) Version is of type INTEGER and is set to 3 (2) Subject-C - is of type UTF8String, and is set to ISO 3166 code specifying the country where the Authenticator vendor is incorporated (UTF8String) (3) Subject-O - is of type UTF8String, and is set to the legal name of the Authenticator vendor (4) Subject-OU - is of type UTF8String, and is set to literal string “Authenticator Attestation” (5) Subject-CN - is of type UTF8String, and is not empty (6) Basic Constraints extension MUST have the CA component set to false. (7) [TBD] If the related attestation root certificate is used for multiple authenticator models, the Extension OID 1.3.6.1.4.1.45724.1.1.4 (id-fido-gen-ce-aaguid) MUST be present, containing the AAGUID as a 16-byte OCTET STRING. The extension MUST NOT be marked as critical. (8) Check that certificate is not expired, is current(notBefore is set to the past date), and is valid for at least 5 years [TBD] (i) Concatenate authenticatorData and signData to clientDataHash. Using key extracted from leaf certificate, signData verify signature in "sig" field.‣
Error: Invalid data: Not a SEQUENCE ASN/DER structure
    at asnLen (C:\Users\yscho\AppData\Local\F\app-0.10.110\resources\app\dependencies\fido2dep.js:19:15)
    at Object.verifySignature (C:\Users\yscho\AppData\Local\F\app-0.10.110\resources\app\dependencies\fido2dep.js:228:17)
    at r.eval (eval at compileCode (js/sandbox.js:25:26), <anonymous>:3448:71)
    at c (js/vendor/mocha.min.js:1:39830)
    at s.h.run (js/vendor/mocha.min.js:1:39766)
    at g.runTest (js/vendor/mocha.min.js:1:45107)
    at file:///C:/Users/yscho/AppData/Local/F/app-0.10.110/resources/app/app/js/vendor/mocha.min.js:1:45969
    at o (js/vendor/mocha.min.js:1:44419)
    at file:///C:/Users/yscho/AppData/Local/F/app-0.10.110/resources/app/app/js/vendor/mocha.min.js:1:44488
    at s (js/vendor/mocha.min.js:1:43894)
if(attStmt.x5c) {
    assert.isUndefined(attStmt.ecdaaKeyId, 'attStmt contains both ECDAA and FULL attestations!');
    assert.isArray(attStmt.x5c, 'attStmt.x5c MUST be of type SEQUENCE!');
    assert.isDefined(metadata.attestationRootCertificates, 'MetadataStatement does NOT contains mandatory attestationRootCertificates field!');
    assert.isArray(metadata.attestationRootCertificates, 'MetadataStatement.attestationRootCertificates MUST be of type SEQUENCE!');
    assert.isNotEmpty(metadata.attestationRootCertificates, 'MetadataStatement.attestationRootCertificates MUST NOT be empty!');
    assert.isDefined(metadata.attestationTypes, 'MetadataStatement missing attestationTypes field!');
    assert.isArray(metadata.attestationTypes, 'MetadataStatement.attestationTypes MUST be of type SEQUENCE!');
    assert.include(metadata.attestationTypes, ATTESTATION_TYPES.ATTESTATION_BASIC_FULL, 'MetadataStatement.attestationTypes MUST include ATTESTATION_BASIC_FULL')
    
    let attStmtCertificateChain = attStmt.x5c.map((cert) => base64StringCertToPEM(HEXToBASE64(cert)))
    let chainIsValid = false;
    for(let attestationRootCertificate of metadata.attestationRootCertificates) {
        let certPem = base64StringCertToPEM(attestationRootCertificate)
        let validationChain = attStmtCertificateChain.concat([certPem]);
        chainIsValid = chainIsValid || verifyCertificateChain(validationChain)                
    }
    assert.isTrue(chainIsValid, 'Can not validate certificate chain!');
    let leafCert = attStmtCertificateChain[0];
    let certificate = new jsrsasign.X509();
    certificate.readCertPEM(leafCert);
    let certInfo = getCertificateInfoObject(certificate);
    assert.strictEqual(certInfo.version, 3, 'Attestation Certificate version MUST be v3!');
    assert.isDefined(certInfo.C, 'Attestation Certificate missing C:countryName attribute!');
    assert.include(listOfCountryCodes, certInfo.C, `CountryName attribute contains unknown "${certInfo.C}" ISO alpha2 code!`);
    assert.isDefined(certInfo.O, 'Attestation Certificate missing O:Organization attribute!');
    assert.isNotEmpty(certInfo.O, 'Attestation Certificate OU attribute MUST be set to the legal name of the authenticator vendor!');
    assert.isDefined(certInfo.OU, 'Attestation Certificate missing OU:OrganizationalUnit attribute!');
    assert.strictEqual(certInfo.OU, 'Authenticator Attestation', 'Attestation Certificate OU attribute MUST be set to the literal string "Authenticator Attestation"!');
    assert.isDefined(certInfo.CN, 'Attestation Certificate missing CN:CommonName attribute!');
    assert.isNotEmpty(certInfo.CN, 'Attestation Certificate CN attribute MUST NOT be empty!');
    assert.isDefined(certInfo.basicConstraintsCA, 'Attestation Certificate missing basicConstraints extension!');
    assert.isFalse(certInfo.basicConstraintsCA, 'Attestation Certificate basicConstraints CA component MUST be set to false!');
    assert.isTrue(certInfo.notBefore.getTime() < new Date().getTime(), 'Attestation Certificate notBefore MUST NOT be set in the future!');
    assert.isTrue(certInfo.notAfter.getTime() > new Date().getTime(), 'Attestation Certificate is expired!');
    // TODO: Discuss with ADAM
    // if(getDateIn5Years().getTime() > certInfo.notAfter.getTime())
        // alert('Your device certificate is set to expire in less than 5 years! This may lead to some negative consequeses for your user!');
    let signatureData = mergeArrayBuffers(hex.decode(cborResponse[MakeCredRespKeys.authData]), clientDataHash);
    let signature     = hex.decode(attStmt.sig);
    let signatureIsValid = window.navigator.fido.fido2.crypto.verifySignature(leafCert, signature, signatureData);
    assert.isTrue(signatureIsValid, 'Cannot validate the signature!');
} else {
    this.skip()
}

**Comment by herrjemand** [comment]
@sangraecho Could you provide me with a copy of your attestation?

**Comment by herrjemand** [comment]
@sangraecho Should be fixed now

**Comment by DaoThanhLong** [comment]
Hi There,
I have the same issue.
Is issue fixed?
Or how do I resolve this issue?
Thank for your help.
