### ISSUE TITLE
Signature verification failed in P-1 Authr-GetAssertion-Resp-1

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#404]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

Latest

## What is the OS and the version are you running?

Windows 10

## Issue description

We tried to test Authr-GetAssertion-Resp-1 to test  GetAssertion response signature and got the following error message from the tool.

•P-1 Merge authData and clientDataHash, and using previously acquired publicKey verify signature from GetAssertion_Response‣
AssertionError: The assertion signature can not be verified!: expected false to be true

Our authenticator uses PS256( ALG_SIGN_RSASSA_PSS_SHA256_RAW) and the below is tested request and response messages between our authenticator and the testing tool.

MakeCredential Command (from the tool to authenticator)
"01A401582018718818F2B6C1D8581F710FCBF77D1A2D270737981504022D764F5FF2248AC702A262696472686F6F6B636F6D6D756E69636174652E6769646E616D657829546865204578616D706C6520436F72706F726174696F6E20776974682066616B6520646F6D61696E2103A46269645820169D7E79C6E5745C812943B06B37BCA4F71640383A4070DE345CDA01289B128F6469636F6E782868747470733A2F2F706963732E61636D652E636F6D2F30302F702F61426A6A6A707150622E706E67646E616D65781B616C65632E70616C617A7A6F40626F756E63797368696E792E6E6F6B646973706C61794E616D656C416C65632050616C617A7A6F0481A263616C67382464747970656A7075626C69632D6B6579";

MakeCredential Response (from authenticator to the tool)
"00A301667061636B656402590166BA080B13038FAFE33ADDBA8BF4B2539000A5D4EF89C11A3474B95A9121C34FCD45000000007610B177C7584E349F1D1405566CFF0F0020D5393A018320D1F001CD74876B060DDFE0701B6734E0B4C75B642ED8F5D4AC1BA4010303382420590100D5BC4D2354CB32AED6059D95823D76E2096ACB16D4FE02F0EA57D7DCD6B79201A2E642A54330EEF4A12C6682AE447665CE61FAEEABD7AE4091FCB50D5D3D742EB551998DB4E699F7DEDC35873485E4569742890855E58BEC6F2433C7734DBA999BDF3FCD1CA0D41AFF7A57E3DF7E4BCCCA0F3D8D1889714CE6FF1F39D5F5850BA0BBAC1914FCE3CB13F98F7301FDAE163A2A76714C8BFD17385996CDACE6EB58CE91EA168BA26C2FF7BE9244ED95E30868FBAF3A4E83C41FC709B62046D537505CC2A2502457D1DB10A387AB9A5E7B60BC5B691C3FBD63A7723FE33D3EDA9255065E88CB9384041B5D8A48B7E6F2783DD8317F991AB3A74D41B7C0C624623A01214301000103A363616C673824637369675901000ED9BC56C7BE48734380DB42F3983EC95D16421FA47C988B328CB0460E8A3F24E9EC75BD2AA601DAC5AA6962F7ADB735E7893CE24DAEEED445052C6D074273E699CA54BE3FD34B4A5519C40B32EAF27636860CB273DED5A52E88E0C3A996C3388BD14FAE7AC2821B9CA01D804906A362F47F37D7D95FD475E09A26103B1606D8825303872A5E2C0C0CE9F431A7DC87AEBE36BF26169B1BE81A78BB44F261C39F3FD7B8BD8EB3BD9BF991343623714DDC30DBD8D71BC3062C3F5E631A3B9CD69B0C2A22C1EC4E2D1B8568B175661D9E9A556BABF58CF638D35543F5DD03C2EF5050FA34F3A85EF5B4171AEBBEBD27DA0C760D533DDC6C57F8AACC88D241049C4863783563815903553082035130820239A00302010202033F7844300D06092A864886F70D01010B05003039310B3009060355040613024B52310D300B060355040A0C0445545249311B301906035504030C1245545249204649444F3220526F6F74204341301E170D3138303930373038303330315A170D3233303930373038303330315A3068310B3009060355040613024B52310D300B060355040A0C044554524931223020060355040B0C1941757468656E74696361746F72204174746573746174696F6E3126302406035504030C1D694F532053572050617373636F64652041757468656E74696361746F7230820122300D06092A864886F70D01010105000382010F003082010A0282010100B6401193994677749218E3B32B86ED9800EEA0408F18368C7903B0C140A7C90FDE25D79B2E3494CE263226F89C0BE68C395ABA4B12B0413C97E4371B6AB1083807DF47975659507F28EEF860BA473DCF19C521DD0FCDD03F79EC5800B0089D5005AEF2E44201DC22B205AAA7341D3D67B10222679EC2F611D8FBD4484566BE3CFD3610BB2EC69868DB46E658A16973639BC338531DF23DF504CED551F311AF4D0F68482F1511127FCF6B593129011E4F75EEF8907C1E06E2CD94DDD73F7445CC6C4E40030586605D1D261721CB33D6FD5033365061BC836B83E37AECE8C73D3E85048D45CBC441D3F3A1A17FE3B2AC87169618BA46D964319AF2D7DF84A517BD0203010001A33330313021060B2B0601040182E51C010104041204107610B177C7584E349F1D1405566CFF0F300C0603551D130101FF04023000300D06092A864886F70D01010B050003820101000BF081E7F92C917935B786E0EEA74A760A59A5A31C5D5EA0B493D00FED5CA1431344FDF615A440FAF9A35F8616F6050B9FC7E0BBB5E37B0CF03A9329BD4713516A78C488053C078FD6FBC593D8200A0E7A3F637715848CFE28533128DFD008152C6539326FF0FDEBD5FF27F0E8B53199BB085D6258C7327223305B8A647875952CB880DB0ACCD99679A6A6E7B4D186C12631F0AF888139BE62F80CEF394222D2915150A09198E1836FBBD6695393FC8B6B0118E33BE2B255A2FABFAADAA43E028C101344EECE5EDD8E64582F109D9AEE483D77D404C2FDFF1A2F2E3F8402A1D1FDA140E4BAD31FDF8BAF3552AC97532109F0247123F613DCFA0C37DB0751E4F9";

GetAssertion Command (from the tool to authenticator) 
"02A30172686F6F6B636F6D6D756E69636174652E6769025820605C237FDCEA7FD5E0CA2C69E7B8254C459E81911B4337D1D06306BC7C9F06330381A26269645820D5393A018320D1F001CD74876B060DDFE0701B6734E0B4C75B642ED8F5D4AC1B64747970656A7075626C69632D6B6579";

GetAssertion Response (from authenticator to the tool, in P-1 the following message used to verify signature)
"00A401A26269645820D5393A018320D1F001CD74876B060DDFE0701B6734E0B4C75B642ED8F5D4AC1B64747970656A7075626C69632D6B6579025825BA080B13038FAFE33ADDBA8BF4B2539000A5D4EF89C11A3474B95A9121C34FCD050000000103590100BECC7F389792B0F0ECCF96573E6FE2BAD6542A0F6E7B6752347B05DA50212C558F4BAD00682A76719C18169E440B83B6BB7663AAF148365B02F6AF61867B60611C8B13D8EC18ACDFEE710425DEA6341BF433A1FF2FADD8DBFAF88BCB89866D9A6E5672FEB201AF7A74E4F33B4C2E2F7B70A7AA4370BBA731FA884307CC6CD20F47ED1F03A589071FEF248806D464B76835B92C52BA59ABACFC18267B6ADBFA76849D5932CFD6B38A39889F8F2D33ED936944119EBB65D71D05BDA1BE9121097AEB6A7CCC95A56154EEECCC427C9D910972CDB26CFE56FD5694147D6D5F6EB8EDB78060AC22DA2BC53B21AE18B5C0E2720D180F6870674E60F8440905431E28EF04A46269645820169D7E79C6E5745C812943B06B37BCA4F71640383A4070DE345CDA01289B128F6469636F6E782868747470733A2F2F706963732E61636D652E636F6D2F30302F702F61426A6A6A707150622E706E67646E616D65781B616C65632E70616C617A7A6F40626F756E63797368696E792E6E6F6B646973706C61794E616D656C416C65632050616C617A7A6F";

We got signature verification successful if we used bouncy castle crypto lib to process verification. 

Can you please check the above message if RSA signature we generated is correctly verified in the testing tool?

**Comment by herrjemand** [comment]
@sangraecho That should be fixed now.
