### ISSUE TITLE
ECDSA signature not doing DER encoding correctly

### ISSUE THREAD

**Issue by andychan1998** [fido-alliance/conformance-tools-issues#406]
## What protocol and version of the protocol are you testing?

UAF v1.0/v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.110

## What is the OS and the version are you running?

macOS Sierra (v10.12.6)

## Issue description

I received the following DER-encoded ECDSA signature from a registration assertion:

00000000: 3044 0220 42f1 4b57 ef2b 813b f645 c8e0 
00000010: 3bee 61b5 c1b8 9fcf b9ec b47c 241e 26b5 
00000020: 862c e12a 0220 cf6e f3ba e5d1 95b3 c5ab 
00000030: 5a78 4cc9 b553 b362 6b72 c2dc 990d 9770 
00000040: b9cb 4e00 2ee5                        

This is a sequence (30) with 68-byte content (44).  The sequence contains integers (02) of 32 bytes (20) each.  The first integer goes from byte 4 to byte 36, and the second integer goes from byte 38 to byte 70.

The problem with this encoding is that the DER spec allows both positive and negative integers.  In this case, the second integer has its msb set, so it will be interpreted as a negative integer.  The correct encoding should prepend a 0 as the first byte to the second integer, as shown below:

00000000: 3045 0220 42f1 4b57 ef2b 813b f645 c8e0 
00000010: 3bee 61b5 c1b8 9fcf b9ec b47c 241e 26b5 
00000020: 862c e12a 0221 00cf 6ef3 bae5 d195 b3c5 
00000030: ab5a 784c c9b5 53b3 626b 72c2 dc99 0d97 
00000040: 70b9 cb4e 002e e5           

I notice that in the eBay open source FIDO server, it chooses to always interpret both integers as positive.  While this would work in this case since both r and s should be positive, it's not necessarily correct according to the DER spec.  In fact, I tried using OpenSSL command line (openssl dgst -sha256 -verify pubkey.pem -signature signature.der data.bin) and PHP ECC library (Mdanter\ECC) to verify the DER-encoded signature, and they both fail because of the wrong DER encoding.

Here's some background information:

https://crypto.stackexchange.com/questions/12488/can-r-and-s-from-an-ecdsa-signature-be-negative-numbers
http://r6.ca/blog/20111119T211504Z.html

**Comment by herrjemand** [comment]
Should be fixed next build. Thanks for reporting *)
