### ISSUE TITLE
Certificate Validation Expired message for MDS URLs

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tools-issues#411]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.110

## Issue description
When attempting to run a fetch command for the MDS TOC; there is an error message:
URL for the location of Metadata TOC looks good!
Input Validation Complete!
Retrieving TOC using Mode : MDS 1.0 and URL : https://fidoalliance.co.nz/mds/execute/1c8027061524fab9191c47358b133f66042ad6ab71e20faf7d16b9819ef48cad
Root certificate is valid!
TOC successfully obtained from https://fidoalliance.co.nz/mds/execute/1c8027061524fab9191c47358b133f66042ad6ab71e20faf7d16b9819ef48cad
Error in processing: Exception: Certificate Validation Failed.  Validation failed on certificate number: 1. Details: Certificate has been revoked, reason: UNSPECIFIED, revocation date: Sat Mar 01 00:00:00 UTC 2014, authority: CN=FAKE Root FAKE, OU=FAKE Metadata TOC Signing FAKE, O=FIDO Alliance, C=US, extension OIDs: [2.5.29.21]

**Comment by herrjemand** [comment]
@jenkay Thats the point. One of the payloads contains expired certificate chain

**Comment by jenkay** [comment]
thanks. I understand. 4/5 failed so I was concerned and I remembered I logged a defect on this before and it was fixed. I'll close this.
