### ISSUE TITLE
Cannot read property 'processUAFOperation' of undefined

### ISSUE THREAD

**Issue by Kieun** [fido-alliance/conformance-tools-issues#412]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAF v1.1
UAF/U2F/FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?
Server
Server/Client/ASM+Authr

## What is the version of the tool are you using?
1.1.0

## What is the OS and the version are you running?
Android

## Issue description
When I trying to run the test case "Test registration" in UAF v1.1 Interop Tools, the type error is thrown.
So, we cannot proceed any other test cases since we fail to register the user.

**Comment by herrjemand** [comment]
Hey @Kieun I have resolved this issue in the latest build.

Regards. Yuriy
