### ISSUE TITLE
iOS conformance tool installation failed

### ISSUE THREAD

**Issue by Kieun** [fido-alliance/conformance-tools-issues#413]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAF
UAF/U2F/FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?
Server
Server/Client/ASM+Authr

## What is the version of the tool are you using?
1.1.0

## What is the OS and the version are you running?
iOS

## Issue description
When trying to install the conformance tool on the device, the installation is failed.
"A valid provision profile for this executable was not found"

**Comment by herrjemand** [comment]
Hey @Kieun I am looking into your issue

**Comment by herrjemand** [comment]
Hey @Kieun Can you try v1.2.0?

**Comment by Kieun** [comment]
@herrjemand Still same error

**Comment by herrjemand** [comment]
Hm... Have you emailed me your UDID?
