### ISSUE TITLE
Invalid Authority Key Identifier extension in TPM certificate

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-tools-issues#415]
## What protocol and version of the protocol are you testing?
FIDO2
## What is your implementation class?
Server
## What is the version of the tool are you using?
0.10.150
## What is the OS and the version are you running?
Windows 10
## Issue description

I have an issue with the attestation certificate which was sent by the 'P-2 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation for SHA-1, and check that server succeeds' test (see end of this issue for certificate as pem).

The certificate parser I'm using fails to parse this certificate on the X509v3 Authority Key Identifier extension. The content value of this extension is `3016A014517F22C8E653A57CD54CDD30587E30FF67368C5D`, which is not valid DER.

`3016` = sequence of length 22 (`0x30`=sequence, `0x16`=length)
`A014 {data bytes}` =tagged context-specific field [0] of length 20, which should be the KeyIdentifier as an (implicit) octet string.

However, the `A0` tag has the constructed flag set, which is incorrect I think. It should be a primitive type since it is an octet string, otherwise the data bytes after `A014` should be valid DER too. If `A0` is changed to `80` it is valid again.

If you open the certificate on a windows machine it won't show the identifier correctly either (see image on the left), while for example with the google.com certificate it works fine:

![screenshot](https://user-images.githubusercontent.com/12815705/48135019-061adf00-e29c-11e8-9e74-ce1bf343095c.png)
```
-----BEGIN CERTIFICATE-----
MIIEWzCCA0OgAwIBAgIPBD9onXAD4F13wOPphVNeMA0GCSqGSIb3DQEBCwUAMEEx
PzA9BgNVBAMTNk5DVS1OVEMtS0VZSUQtMzYxMDRDRTQwQkJDQzFGNDBEODRBNEJC
RDUwQkU5OTAyNEQ5NTdENDAeFw0xODAyMDEwMDAwMDBaFw0yNTAxMzEyMzU5NTla
MAAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC275hXMNo0FL9wfScy
iSZHr12v4zJx1Nr4lydfvryYs/Ea4trkWh3Z3JJvNj7+c7thu39Ccj5kxweOVyfI
AmgPkIAJdTgzQPOnZAwXGCeGLHnaYcT+CC9CLZteeIsvgDZTfvMoAzs+FFVaED8d
BQCVoaeHQwMlcf+/Ns6Zdix7dQBcIyjIQQNTpq4xUq2OoBr+6H0J7JdTbhQ4u5en
uM8BfePm8YoTxExuJdr343Rw68vIfltxow39EIaFzs13LRluBG4UZanUYyxTMm3D
XZi9nXydHBavbRwCNslP8shDn/G+92mRWXW9oaYbBuy5iftOzxqpbkhc37Z5MOfl
bbzdAgMBAAGjggGPMIIBizAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADBT
BgNVHSABAf8ESTBHMEUGCSsGAQQBgjcVHzA4MDYGCCsGAQUFBwICMCoTKEZBS0Ug
RklETyBUQ1BBIFRydXN0ZWQgUGxhdGZvcm0gSWRlbnRpdHkwEAYDVR0lBAkwBwYF
Z4EFCAMwSgYDVR0RAQH/BEAwPqQ8MDoxODAOBgVngQUCAwwFaWQ6MTMwEAYFZ4EF
AgIMB05QQ1Q2eHgwFAYFZ4EFAgEMC2lkOkZGRkZGMUQwMB8GA1UdIwQYMBagFFF/
IsjmU6V81UzdMFh+MP9nNoxdMB0GA1UdDgQWBBRWthozmbA9xRNirYDNCbz5HqAf
iDB4BggrBgEFBQcBAQRsMGowaAYIKwYBBQUHMAKGXGh0dHBzOi8vZmlkb2FsbGlh
bmNlLmNvLm56L3RwbXBraS9OQ1UtTlRDLUtFWUlELTM2MTA0Q0U0MEJCQ0MxRjQw
RDg0QTRCQkQ1MEJFOTkwMjREOTU3RDQuY3J0MA0GCSqGSIb3DQEBCwUAA4IBAQCN
tWz3BzCe/gu5b3oG+Eq60jIy0IUBMjeK6E03auFVEFdDzH8VTUJ4Odl9qAEuoJAP
ImrzmZEwsGU0w8LxOtRa35iCsE9BCWIoxM5zrAKYrx3WWHOgu79wJX/SW/rpzZs7
I9GxC58wIYsWFJJifqLXTDEzRRIEkDHL4zVE1AkKG+njyCCMLC/M0C9CdPtapDJ6
z2aELL/sCji99r0ylq8BE5iKTuuYt934jNCbeidsOwQiSLBQvE3kPQMmeD3T9GK2
L0qMJrzjSAebaj8KELgEXlefABg6aDgbIpFQcBlEEhztQ4ER2zZ29Ft/Zg6MJu7F
sOd61CjIy0P2R74eqCt4
-----END CERTIFICATE-----
```

**Comment by herrjemand** [comment]
So this is jus the issue for AIK?

**Comment by herrjemand** [comment]
Resolved
