### ISSUE TITLE
Invalid attachment hint in metadata

### ISSUE THREAD

**Issue by BaljeetSandhu** [fido-alliance/conformance-tools-issues#423]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.10.191

## What is the OS and the version are you running?

MacOS

## Issue description
The metadata stmts packaged with the conformance tool specify:

> "attachmentHint": 2

The [pre defined attachment hint constants in the spec](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-registry-v2.0-rd-20180702.html#authenticator-attachment-hints) specify

ATTACHMENT_HINT_EXTERNAL 0x0002
> This flag must be combined with one or more other ATTACHMENT_HINT flag(s).

If I understand correctly, this makes the "2" value invalid?

**Comment by herrjemand** [comment]
Thanks @BaljeetSandhu fixed in 192
