### ISSUE TITLE
Invalid attestationCertificateKeyIdentifiers in U2F metadata

### ISSUE THREAD

**Issue by BaljeetSandhu** [fido-alliance/conformance-tools-issues#424]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.191

## What is the OS and the version are you running?

MacOS Mojave

## Issue description

The [metadata statement definition](https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#widl-MetadataStatement-attestationCertificateKeyIdentifiers) spec for _attestationCertificateKeyIdentifiers_ states that:

> All hex letters must be lower case

In _fido2-conformance-module/metadata/U2FSecp256k1.metadata.json_, the hex letters are in uppercase

> "attestationCertificateKeyIdentifiers": ["564DF7C0F8C655B6A11F6C4D19F3BF41E2FD0179"],

**Comment by herrjemand** [comment]
Thanks @BaljeetSandhu Fixed in 192
