### ISSUE TITLE
Stop username randomizing

### ISSUE THREAD

**Issue by ynojima** [fido-alliance/conformance-tools-issues#425]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

FIDO Conformance Tools v0.10.192 (BETA)(FIDO2 )

## What is the OS and the version are you running?

Windows 10 2018 October Update

## Issue description

The test tools randomly generate a username, and it prevents preseeding test user data in the server side.
In my understanding, '/attestation/result' endpoint is for credential registration not for user registration.
So user data must be prepared in advance.

### Expected behavior

A fixed username is used in a testing.

**Comment by herrjemand** [comment]
Hard to share in a state. Removes the cleanest of the test runs. This is expected behaviour.

**Comment by herrjemand** [comment]
@ynojima Yes, server must register new user

**Comment by ynojima** [comment]
I understand. Thank you for clarification.
Could you define it on the TBP spec? I suppose it is not obvious behavior.
If already registered username is specified, how "/attestation/result" endpoint should behave?
