### ISSUE TITLE
Metadata TOC update date format not ISO-8601

### ISSUE THREAD

**Issue by BaljeetSandhu** [fido-alliance/conformance-tools-issues#427]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/U2F/FIDO2 v1.0/v1.1/v1.2

**FIDO2**

## What is your implementation class?

Server/Client/ASM+Authr

**Server**

## What is the version of the tool are you using?

**v0.10.191**
## What is the OS and the version are you running?
**MacOS Mojave**

## Issue description

The metadata TOC object spec states:
> **nextUpdate** of type required DOMString
> _ISO-8601 formatted date_ when the next update will be provided at latest.

In the MDS TOC response I am getting for the test endpoints generated is:

- 2020-0-3 from https://fidoalliance.co.nz/mds/execute/e26778080fe03bb75516342e7fb55af8b025d727da972e7809695b92b06f1373
- 2020-0-3 from https://fidoalliance.co.nz/mds/execute/fe30a9b6b30a0a84d7da0d406726dbb416bda8cb71d88035a526381f0e60ce94

Can you please advise if this is an intentional bad data scenario or an error?

**Comment by herrjemand** [comment]
Hey @BaljeetSandhu. Great spot on. My only issue is that I can't reproduce it. When did you register it?

**Comment by herrjemand** [comment]
@BaljeetSandhu You should regenerate endpoints. I think this is an artefact of the past.

Regards. Yuriy

**Comment by ynojima** [comment]
Hi, I encounter the same issue.

Here is the test endpoints generated:
2020-0-27:
https://fidoalliance.co.nz/mds/execute/9e01885d1d2c174bd42718cb227b0ba6ea9afbe25ee312e6cc2b8bfc0fe8db4c

**Comment by ynojima** [comment]
I encounterd another issue.
https://fidoalliance.co.nz/mds/execute/0f19dfa625f7f56c626e528b79d75946fe92337355681ac47f25f4ccb55aa601

This TOC contains `2020-1-3` in nextUpdate field, but it must be `2020-01-03`

**Comment by herrjemand** [comment]
Resolved

**Comment by herrjemand** [comment]
@BaljeetSandhu @ynojima Please regenerate endpoints
