### ISSUE TITLE
Assertion error: Response is missing "extensions" field!

### ISSUE THREAD

**Issue by pham-vy** [fido-alliance/conformance-tools-issues#431]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.192 (BETA)

## What is the OS and the version are you running?
Windows 10

## Issue description
When running GetAssertion request tests, I got an error as below:
![image](https://user-images.githubusercontent.com/45988191/50888098-387dbf80-1438-11e9-9ba6-0a33b4ace2fc.png)

But as defined in spec, "extensions" field is OPTIONAL member, not MUST (http://w3c.github.io/webauthn/#assertion-options)

**Comment by herrjemand** [comment]
@pham-vy The server is governed by server specs: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html

**Comment by pham-vy** [comment]
Not found any hints. Even in your example, there is no extensions field:
![image](https://user-images.githubusercontent.com/45988191/50890965-96150a80-143e-11e9-93fb-b1c591d7c10c.png)
