### ISSUE TITLE
Resident Key test fails if Authenticator does not support UV

### ISSUE THREAD

**Issue by serianox** [fido-alliance/conformance-tools-issues#432]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

v0.10.110

## Issue description

In test CTAP2 Tests - Options - P-3 FOR AUTHENTICATORS WITHOUT A DISPLAY AND EITHER UV IS TRUE OR CLIENTPIN IS USED.

If the Authenticator doesn't support UV, including not supporting ClientPinV1, the test is always run. The test doesn't set a Pin, nor send uv="true", and fails because the resident credentials returned doesn't contain User Identifiable Information as expected.

The test is probably missing a skip for this case in the beginning, e.g.

```javascript
if(!supportsClientPin1 && !supportedOptions.uv)
    this.skip();
```

**Comment by herrjemand** [comment]
Resolved *)
