### ISSUE TITLE
Duplicate AAGUID in conformance tool test metadata

### ISSUE THREAD

**Issue by aseigler** [fido-alliance/conformance-tools-issues#433]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.192

## Issue description

Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with supported extensions.json:    "aaguid": "326adcf0-0cef-46d0-9392-98d6c4a84a72",

Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator.json:    "aaguid": "326adcf0-0cef-46d0-9392-98d6c4a84a72",

**Comment by herrjemand** [comment]
Thanks @aseigler Fixed now
