### ISSUE TITLE
Conformance tool turns on ED flag and adds single byte empty CBOR map for extensions

### ISSUE THREAD

**Issue by aseigler** [fido-alliance/conformance-tools-issues#435]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.196

## What is the OS and the version are you running?

Windows 10

## Issue description

If server offers extensions support in attestation options, conformance tool turns ED flag on and adds single byte (0xa0) empty CBOR array to authenticator data in attestation result, even if client does not set any extensions in AuthenticationExtensionsClientOutputs indicating that extensions were acted upon.  I would not expect ED flag to be on or any extension data present if all extensions are ignored.

**Comment by herrjemand** [comment]
@aseigler Resolved. Thx for letting me know *)
