### ISSUE TITLE
Server-ServerAuthenticatorAssertionResponse-Resp-3, P-2

### ISSUE THREAD

**Issue by tfvbhy** [fido-alliance/conformance-tools-issues#436]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.201

## What is the OS and the version are you running?
Windows 10 Version 1809

## Issue description
P-2 Send a valid ServerAuthenticatorAssertionResponse with authenticatorData.flags.UP is set, for userVerification set to "required", and check that the server succeeds. 

I believe the test sends UV = false and UP = true in the authenticatorData flags and expects the server to pass the signed challenge. I believe the assumption made is referenced here: https://github.com/fido-alliance/conformance-tools-issues/issues/332#issuecomment-410026702.

However, from the WebAuthn Specification (https://www.w3.org/TR/webauthn/#enumdef-userverificationrequirement):
"This value indicates that the Relying Party requires user verification for the operation and will fail the operation if the response does not have the UV flag set."

I believe the "required" scenario should be:
"required"
UV MUST be true
UP can be false
both can be true

**Comment by herrjemand** [comment]
Resolved

**Comment by tfvbhy** [comment]
@herrjemand how was this resolved? Is this being resolved in a new build of the conformance tool or is my reading of the specification wrong?

**Comment by herrjemand** [comment]
@tfvbhy resolved in the next build

**Comment by tfvbhy** [comment]
Thank you
