### ISSUE TITLE
Test Server-ServerAuthenticatorAssertionResponse-Resp-3 F-5 is postive test, marked as negative

### ISSUE THREAD

**Issue by aseigler** [fido-alliance/conformance-tools-issues#439]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.207

## What is the OS and the version are you running?

Windows 10

## Issue description

Test Server-ServerAuthenticatorAssertionResponse-Resp-3
F-5, Send a valid ServerAuthenticatorAssertionResponse with authenticatorData.flags.UP is set, for userVerification set to "required", and check that server succeeds

This is actually a positive test, not a negative test.

**Comment by herrjemand** [comment]
fixed!
