### ISSUE TITLE
UAF 1.1 Dereg AppID and Facets trustedFacets tests

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#440]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
fido-conformance-tools-ionic-v1.4.3.apk

## What is the OS and the version are you running?
Android 7.0

## Issue description

Deregistration Test for Protocol-Dereg-Req-4 Test client correctly processing AppID and Facets in Deregistration Request section

All of the tests in this section are using the same AppID URL. That URL always returns the same valid trustedFacets data and it never performs a redirect(HTTP 3XX). This causes negative test cases to fail.

This is the URL and trustedFacets data that were seen in the logs.

facetId: android:apk-key-hash:hoG2zCMzhpGCNnLFceBuVpPfDqM
appId: https://fidoalliance.co.nz/execute/0xVaw5EfVxYfcVRLP4aVtedZS6Qv8EkqOILxHxop

```javascript
{
   "trustedFacets": [
     {
       "version": {"major": 1,"minor": 0},
       "ids": [
         "android:apk-key-hash:hoG2zCMzhpGCNnLFceBuVpPfDqM",
         "https://fidoalliance.nz/"
       ]
     }
   ]
}
```

--

**Comment by herrjemand** [comment]
@mirkop There is only one test that does redirect.
