### ISSUE TITLE
Dereg AppID and Facets tests not running

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#441]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
fido-conformance-tools-ionic-v1.4.3.apk

## What is the OS and the version are you running?
Android 7.0

## Issue description

Deregistration Test for Protocol-Dereg-Req-4 Test client correctly processing AppID and Facets in Deregistration Request section

The following tests in this section, do not appear to even run. There is no corresponding “Test started:” for them and the FIDO UAF Client is never called. As a result, they always pass.

Test done: F-13
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" field set to effective "http" URI that has the same effective domain as facetID(facet: http://example.com/login.html and appID: http://example.com/loginIsNotSoSecure), wait for the response, and check that API returns INSECURE_TRANSPORT(0x02) error

Test done: F-14
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" field set to the current facet, that is "http" URI, wait for the response, and check that API returns INSECURE_TRANSPORT(0x02) error

Test done: F-15
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" field set to the current facet, that is "https" URI, and contains insecure mixed content, wait for the response, and check that API returns INSECURE_TRANSPORT(0x02) error

Test done: F-16
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" set to the "https" URI that leads to the trusted facets list, and facetID is a sub-domain of the appID eTLD(effective top-level domain) and is NOT a member(e.g.: appID:https://example.com/facets.json and facetID: https://rogue.example.com) of trusted facet list, wait for the response, and check that API returns UNTRUSTED_FACET_ID(0x07) error

Test done: F-17
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" set to the "https" URI that leads to the trusted facets list, and facetID is a "http" sub-domain of the appID eTLD(effective top-level domain) and is a member(e.g.: appID:https://example.com/facets.json and facetID: http://notsecure.example.com) of trusted facet list, wait for the response, and check that API returns UNTRUSTED_FACET_ID(0x07) error

Test done: F-18
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" set to the "https" URI with domain that is second level eTLD(https://example.co.nz), that leads to the trusted facets list, that contain facet that is first level "https" eTLD in the same zone(https://attacker.nz), wait for the response, and check that API returns UNTRUSTED_FACET_ID(0x07) error

Test done: F-22
If testing DOM JS API: Send DeregistrationRequest UAF message for the given metadata statement, with "header.appID" set to the "https" URI that leads to the redirect(HTTP 3XX codes) to the trusted facets list, that has "FIDO-AppID-Redirect-Authorized" header set to "true", and current facetID is a member of the list, but facetID and appID are do no share the same eTLD(facetID:example.com, redirected-appID:someSite.com) wait for the response and check that API returns UNTRUSTED_FACET_ID(0x07) error

**Comment by herrjemand** [comment]
I think "If testing DOM JS API" should be self explanatory *)
