### ISSUE TITLE
UAF 1.1 Register & Authenticate orphaned appID / keyIDs

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#442]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
fido-conformance-tools-ionic-v1.4.3.apk

## What is the OS and the version are you running?
Android 7.0

## Issue description

During the Registration and Authentication test, whenever there is an appID URL specified, there is never a corresponding Dereg request for the specified appID. That orphans the keyIDs created for those URLs. There are two appIDs for registration and one for authentication. It would be a good idea to add a deregistration request for those appIDs.

**Comment by herrjemand** [comment]
@mirkop Specify example
