### ISSUE TITLE
Android API Test - MetadataStatement.userVerificationDetails AND combos MUST contain AuthenticatorInfo.userVerification

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#443]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
fido-conformance-tools-ionic-v1.4.3.apk

## What is the OS and the version are you running?
Android 7.0

### Android A{PI Test for FC-API-Android-1 Test the FIDO Android API for specification defined behaviour.
```
P-4
Call function "process" providing a valid DISCOVER request as uafRequest parameter and check that
  (a) the call succeeds and that
  (b) the uafResponseListener provided as second parameter is called with a DISCOVER_RESULT parameter. Check all elements included in availableAuthenticators as follows:
      (1) check that all mandatory fields are present.
      (2) Check that the fields title, AAID, assertionScheme, authenticationAlgorithm, attestationTypes, userVerification, keyProtection, matcherProtection, attachmentHint, isSecondFactorOnly, tcDisplay, tcDisplayContentType, tcDisplayPNGCharacteristics, icon and supportedExtensionIDs are as specified for this authenticator model
```
**AssertionError: MetadataStatement.userVerificationDetails AND combos MUST contain AuthenticatorInfo.userVerification!: expected [1, 2, 4, 128] to include 135**

This test appears to be impossible to pass if the metadata statement can have multiple userVerificationDetails values. It appears to expect the DiscoveryData’s Authenticator.userVerification value to equal all of the metadata userVerification values. That is not possible. **_Even if the DiscoveryData’s Authenticator.userVerification value is set to one of [1, 2, 4, 128] it still fails the validation._**

The MetadataStatement's VerificationMethodDescriptor.userVerification is a single USER_VERIFY constant, not a bit flag combination.

The DiscoveryData's Authenticator.userVerification is a set of bit flags indicating the user verification methods supported by the authenticator.

MetadataStatement
```javascript
{
  "aaid": "0000#0000",
  "description": "Authenticator",
  "protocolFamily": "uaf",
  "authenticatorVersion": 1,
  "upv": [{"major": 1, "minor": 1}],
  "assertionScheme": "UAFV1TLV",
  "authenticationAlgorithm": 8,
  "publicKeyAlgAndEncoding": 259,
  "attestationTypes": [15879],
  "userVerificationDetails": [
    [{"userVerification": 1}],
    [{"userVerification": 2}],
    [{"userVerification": 4}],
    [{"userVerification": 128}]
  ],
  "keyProtection": 1,
  "isKeyRestricted": true,
  "matcherProtection": 1,
  "attachmentHint": 1,
  "isSecondFactorOnly": false,
  "tcDisplay": 1,
  "tcDisplayContentType": "text/plain",
  "attestationRootCertificates": ["MII … wye"],
  "icon": "data:image/png;base64, iVB … YII="
}
```

DiscoveryData
```javascript
{
  "availableAuthenticators": [
    {
      "aaid": "0024#03EF",
      "assertionScheme": "UAFV1TLV",
      "attachmentHint": 1,
      "attestationTypes": [
        15879
      ],
      "authenticationAlgorithm": 8,
      "isSecondFactorOnly": false,
      "keyProtection": 1,
      "matcherProtection": 255,
      "supportedExtensionIDs": [],
      "supportedUAFVersions": [{"major": 1, "minor": 1}],
      "tcDisplay": 1,
      "tcDisplayContentType": "image/png",
      "userVerification": 135
    }
  ],
  "clientVendor": "SurePassID Corporation",
  "clientVersion": {"major": 1, "minor": 0},
  "supportedUAFVersions": [{"major": 1, "minor": 1}]
}
```

**Comment by herrjemand** [comment]
@mirkop You made OR statements. If you want and you need to make 

"userVerificationDetails": [
    [{"userVerification": 1},
    {"userVerification": 2},
    {"userVerification": 4},
    {"userVerification": 128}]
  ],

**Comment by lucypark9706** [comment]
Hello, I am setting up FIDO APK and facing a problem. 
How did you get the metadata for FIDO APK?
