### ISSUE TITLE
Not able to execut authenticate tests

### ISSUE THREAD

**Issue by andreasluca** [fido-alliance/conformance-tools-issues#446]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
ASM+Authr

## What is the version of the tool are you using?
fido-conformance-tools-ionic-v1.4.3.apk

## What is the OS and the version are you running?
Android 9

## Issue description
Not able to run Authenticate tests...

<img width="334" alt="Screenshot 2019-03-21 at 18 05 38" src="https://user-images.githubusercontent.com/8311351/54770926-8109e400-4c04-11e9-9d54-f9c25763a051.png">

**Comment by herrjemand** [comment]
Will release new build tomorrow. Sorry for the inconvenience

**Comment by andreasluca** [comment]
Do you know more or less when will you upload the release?
Thanks!!

**Comment by herrjemand** [comment]
Hey @andreasluca. v1.4.4. is up. Sorry for the delay.
