### ISSUE TITLE
MatchCriteria.attestationTypes contains a member "15881" that is that is not isDefined !

### ISSUE THREAD

**Issue by todowenil** [fido-alliance/conformance-tools-issues#448]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.214

## What is the OS and the version are you running?

Window 10

## Issue description

According to Offical doc that Predefined Tags defined TAG_ATTESTATION :

TAG_ATTESTATION_BASIC_FULL 0x3E07
TAG_ATTESTATION_BASIC_SURROGATE 0x3E08
TAG_ATTESTATION_ECDAA 0x3E09

But got error  (Server-Reg-Req-4 P-7) :
AssertionError: MatchCriteria.attestationTypes contains a member "15881" that is that is not isDefined as a valid attestation type in Registry of Predefined values!: expected false to be true
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5555:32)
    at e (js/vendor/mocha.min.js:1:39758)
    at s.run (js/vendor/mocha.min.js:1:39694)
    at h.runTest (js/vendor/mocha.min.js:1:45264)
    at file:///C:/Users/user/AppData/Local/F/app-0.10.214/resources/app/app/js/vendor/mocha.min.js:1:46126
    at r (js/vendor/mocha.min.js:1:44576)
    at file:///C:/Users/user/AppData/Local/F/app-0.10.214/resources/app/app/js/vendor/mocha.min.js:1:44645
    at r (js/vendor/mocha.min.js:1:44051)
    at file:///C:/Users/user/AppData/Local/F/app-0.10.214/resources/app/app/js/vendor/mocha.min.js:1:44463
    at c (js/vendor/mocha.min.js:1:1064)

**Comment by herrjemand** [comment]
0x3E09(16) is 15881(10)

**Comment by todowenil** [comment]
Thanks for your reply, but I still have problems.
1. The tool PREDEFINED_TAGS object doesn't have TAG_ATTESTATION_ECDAA.
![image](https://user-images.githubusercontent.com/49049220/55373447-bf25d280-5537-11e9-8647-817f43ecb244.png)

2. The tool PREDEFINED_TAGS object TAG_ATTESTATION_BASIC_FULL and TAG_ATTESTATION_BASIC_SURROGATE is undefined.
![image](https://user-images.githubusercontent.com/49049220/55373513-090eb880-5538-11e9-80b0-023830a9dc07.png)
