### ISSUE TITLE
Wrong MatchCriteria elements check on AuthReq

### ISSUE THREAD

**Issue by jason-webcomm** [fido-alliance/conformance-tools-issues#449]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
v0.10.214

## What is the OS and the version are you running?
macOS 10.14

## Issue description
The checks in Server-Auth-Req-4 (P-7) are wrong.  AssertionError: MatchCriteria.attestationTypes MUST be of type NUMBER: expected [ 15881 ] to be a number

**Comment by herrjemand** [comment]
Fixed in the newest build
