### ISSUE TITLE
Wrong error message / ServerPublicKeyCredentialCreationOptions-Req-1, P-1

### ISSUE THREAD

**Issue by corocn** [fido-alliance/conformance-tools-issues#450]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?

Server

## What is the version of the tool are you using?

FIDO Conformance Tools v0.10.110 (BETA)((BETA) FIDO2 )

## What is the OS and the version are you running?

macOS Mojave Version 10.14.3

## Issue description

Wrong error messages.

```
assert.match(ServerPublicKeyCredentialCreationOptionsResponse.user.id, /^[a-zA-Z0-9_-]+$/, 'Response.rp.id MUST be base64URL(without padding) encoded!');
```

Testing target is "user.id" but this message shows "rp.id".

**Comment by herrjemand** [comment]
Resolved in the next version. Thx
