### ISSUE TITLE
The tool still seems to be checking the extensions field.

### ISSUE THREAD

**Issue by dlehdwls00** [fido-alliance/conformance-tools-issues#453]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
**v0.10.215** 

## What is the OS and the version are you running?
Window 10

## Issue description

The tool still seems to be checking the extensions field.

Our authenticator does **not support extensions**
but,
We set the conformance-tool as follows
case 1. If all check except "Extensions" field, the submit button is not created
case 2. if check the "Extensions" field, the tool forces the test to proceed

Did we test wrong?? extensions mandatory?? or tool Bug??

**Comment by herrjemand** [comment]
What test are you failing? @dlehdwls00

**Comment by dlehdwls00** [comment]
@herrjemand 
CTAP2 Tests - Extensions    fail
all tests pass except "Extensions" test

In Extension test : 
HMAC-Secret Test 
we do not support this feature & do not support clientPin
but the tool has tested this feature through clientPin(0x06)

Did we misunderstand??

**Comment by dlehdwls00** [comment]
Also,
We implemented the "txAuthSimple" & "txAuthGeneric", but I wonder if this function is also an mandatory

So, if we do not define it in metastatement and getInfo result, I think we should pass the "txAuthSimple" & "txAuthGeneric" test of "Extension"
but Failed

**Comment by herrjemand** [comment]
Fixed in v0.10.219

**Comment by herrjemand** [comment]
Correction @dlehdwls00. It's 1.0.0
