### ISSUE TITLE
Conformance testing MDS endpoints have malformed certs in x5c header

### ISSUE THREAD

**Issue by aseigler** [fido-alliance/conformance-tools-issues#454]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

0.10.217

## What is the OS and the version are you running?

Windows 10

## Issue description

Certificates in x5c header of JWT from endpoints downloaded from https://fidoalliance.co.nz/mds/  have improperly formatted authorityKeyIdentifier and subjectKeyIdentifier, nearly identical to issue described in #438.  This blocks JWT parsing on some platforms.

Sample: https://play.golang.org/p/A7E1gps1wn3

**Comment by herrjemand** [comment]
Ref: #438 Fixed!

**Comment by herrjemand** [comment]
Correction @aseigler. Its 1.0.0

**Comment by aseigler** [comment]
This is not fixed on the server, the x5c in the TOC still has malformed certificates.  Example:

https://fidoalliance.co.nz/mds/execute/221b068999b5a2a1b04ff33c4889ec9f039af26eab2f1b25dc7d2a9dbfd78eb3

Both of the certs in the x5c header are malformed in the manner described in #438.

**Comment by herrjemand** [comment]
@aseigler Oh right. I will regenerate MDS server certs in the morning

**Comment by aseigler** [comment]
This is still broken.  Every cert in the "FAKE Metadata TOC Signing" chain has a corrupted subjectKeyIdentifier and authorityKeyIdentifier.

**Comment by herrjemand** [comment]
Okay, I've regenerated PKI. Try now @aseigler

**Comment by aseigler** [comment]
Server appears down?  I get a 502 going to https://fidoalliance.co.nz/mds/.

**Comment by herrjemand** [comment]
@aseigler Try now

**Comment by aseigler** [comment]
Web site is up, authority key looks good on leaf cert, but the subject key identifier is still malformed.

**Comment by aseigler** [comment]
Exact same problem with intermediate and roots as well.

**Comment by herrjemand** [comment]
@aseigler 

5280 4.1.2.2:

id-ce-subjectKeyIdentifier OBJECT IDENTIFIER ::=  { id-ce 14 }
SubjectKeyIdentifier ::= KeyIdentifier
KeyIdentifier ::= OCTET STRING

![Screenshot 2019-04-29 08 08 20](https://user-images.githubusercontent.com/1636116/56877344-fd8ab080-6a55-11e9-87db-3511171d99f6.png)
![Screenshot 2019-04-29 08 07 43](https://user-images.githubusercontent.com/1636116/56877345-fd8ab080-6a55-11e9-95f6-f40c914c4a4d.png)

**Comment by herrjemand** [comment]
Hm... 

 404    3:           OBJECT IDENTIFIER subjectKeyIdentifier (2 5 29 14)
 409   22:           OCTET STRING, encapsulates {
 411   20:             OCTET STRING
         :               17 7B 92 30 FF 44 D6 66 E1 90 10 22 6C 16 4F C0
         :               8E 41 DD 6D
         :             }
         :           }

**Comment by aseigler** [comment]
It should look like this, with additional octet string wrapper:

![image](https://user-images.githubusercontent.com/6605560/56899958-b656ec80-6a62-11e9-9a48-228595b7ce08.png)

**Comment by herrjemand** [comment]
@aseigler I hate ASN1

**Comment by aseigler** [comment]
![asn1](https://user-images.githubusercontent.com/6605560/56912245-deebe000-6a7c-11e9-9eaa-37f98418e4b1.jpg)

**Comment by herrjemand** [comment]
@aseigler  OCTET STRING IN OCTET STRING seems like something someone would condemn for some reason.

**Comment by herrjemand** [comment]
Okay, i've regenerated PKI. Try now

**Comment by aseigler** [comment]
Getting closer.  Still got malformed attributes in the tpmpki area:

![image](https://user-images.githubusercontent.com/6605560/56967435-2b8ff380-6b2f-11e9-8f30-121766d286d2.png)

**Comment by herrjemand** [comment]
@aseigler what do you mean?

**Comment by aseigler** [comment]
In the "FIDO Fake TPM Root Certificate Authority 2018" cert the subjectKeyIdentifier has a private tag and the authorityKeyIdentifier has an extra tag prepended to the value.  Should be 20 bytes, the starting with 0xA0 is a hint as to how it got this way.

**Comment by aseigler** [comment]
This endpoint: https://fidoalliance.co.nz/mds/execute/f1a7ef657dc6812d436f2db5fcfbfe663c60fff507b18835dc64cd9c88de19bd

Leaf certificate is fine, the intermediate has malformed subjectKeyIdentifier.

**Comment by herrjemand** [comment]
@aseigler That was the test for a bad certificate. I have replaced it with a good bad certificate. Please regenerate the endpoints

**Comment by herrjemand** [comment]
We don't test CRL support for SafetyNet as it is not mandatory.

**Comment by aseigler** [comment]
But the metadata tests require checking CDP and then chasing the CRL from there.  You have to have a valid CDP and accessible CRL or the tests are invalid.  I would argue that all of the certificates for all of the tests should have valid CDP with accessible CRL for all.  It is messy to special case metadata certificate and chain handling and would be much cleaner to use one method for all cases.
