### ISSUE TITLE
The attestation root cert is not validated due to wrong path length

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#455]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.214 (BETA)(FIDO2 )

## Issue description

This issue was raised before as below and resolved.
https://github.com/fido-alliance/conformance-tools-issues/issues/384

However, the attestation root certificate of TPM and Android Key from testing tool still has set path length = 0 which means the root CA doesn't issue CA certificate.

The below is the testing root certificate that caused the problem.

![image](https://user-images.githubusercontent.com/5744623/56188462-8bcb6380-6060-11e9-895f-63c16dc964de.png)
![image](https://user-images.githubusercontent.com/5744623/56188476-9554cb80-6060-11e9-9012-acada47c0ffd.png)

Can you please fix the two root certificates to avoid certificate validation failure?

**Comment by herrjemand** [comment]
Resolved in v1.0.1
