### ISSUE TITLE
How can I test U2F server side?

### ISSUE THREAD

**Issue by whwjdghks** [fido-alliance/conformance-tools-issues#457]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.218
 v1.0.0(≒v0.10.110?) has no server side test.
 v1.0.0(updated at 15-Apr-2019 16:23 ) was same result.

## What is the OS and the version are you running?

Windows7

## Issue description

We`re now testing our U2F server with FCT v0.10.218 to submiting test result.
But it does not work.
![u2f-error](https://user-images.githubusercontent.com/14068366/56410575-823c3880-62b8-11e9-84f3-34ee388dc645.png)

Please see follow code in `Server-Register-Req-1.js` .
This will return 'undefine'.

> let identity = generateRandomIdentity()

and `utils.js` are here.

```
var generateRandomIdentity = () => {
    let name     = generateRandomName();
    let domain   = generateRandomDomain();

    let username = undefined;
    if(generateSecureRandomInt(0, 1))
        username = name.replace(/\s/, '').toLowerCase()
    else
        username = name.replace(/\s/, '.').toLowerCase()

    let email    = generateRandomDomain();
    let password = generateRandomString();
}
```
Function `generateRandomIdentity` has not return anything.
So that `identity` is undefine and test failed now.

I think that FCT(v0.10.218) has some bugs and it is not stable.
Please let me know which tool we should use for U2F server testing?
Or don't we need to submit U2F server test results?

**Comment by herrjemand** [comment]
Fixed in v1.1.0
