### ISSUE TITLE
conformance-tools : Check that authenticator implements Device Information Service(0x180A)

### ISSUE THREAD

**Issue by KennethKarl** [fido-alliance/conformance-tools-issues#458]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 

## What is your implementation class?
Authenticator(peripheral)

## What is the version of the tool are you using?
FIDO Conformance Tools v1.0.0

## What is the OS and the version are you running?
iOS, 12.1.4

## Issue description
Question : Is '(c)' mandatory on the check list from iOS? Please reply.

_Check that authenticator implements Device Information Service(0x180A), and check that:
            (a) It contains "Manufacturer Name String" characteristic(0x2A29).
            (b) It contains "Model Number String" characteristic(0x2A24).
            (c) It contains "Firmware Revision String" characteristic(0x2A26)._

1. Try run 'CTAP2 Tests - Transports' in conformance-tools

2. The result is following.
<img width="769" alt="스크린샷 2019-04-23 오후 1 33 01" src="https://user-images.githubusercontent.com/49893516/56554354-5ed10080-65cc-11e9-95d6-936bdd99a92a.png">

3. When test device(peripheral) is iOS, '180a' is transfer by device to Tool. But Service(180a) has no contain '2a26'.
--------------------------------------------------------------------------------
    service.name 
       : Device Information
    service.type 
       : org.bluetooth.service.device_information
    service.uuid 
       : 180a
    service.characteristics 
       : {"uuid":"**2a29**","name":"Manufacturer Name 
          String","type":"org.bluetooth.characteristic.manufacturer_name_string","properties":    
          ["read"]},{"uuid":"2a24","name":"Model Number 
          String","type":"org.bluetooth.characteristic.model_number_string","properties":["read"]}
    service.characteristics length 
        : 2
--------------------------------------------------------------------------------

4. The data(service include characteristic : Custom UUID) that i sent is following. It is contain '2a26'
--------------------------------------------------------------------------------
    service.uuid 
        : 0000180a00001000800000805f9b34fb
    service.characteristics 
        : {"uuid":"2a29","name":"Manufacturer Name String",
          "type":"org.bluetooth.characteristic.manufacturer_name_string","properties":["read"]},                            
          {"uuid":"2a24","name":"Model Number String",
          "type":"org.bluetooth.characteristic.model_number_string","properties":["read"]},
          {"uuid":"2a26","name":"Firmware Revision String",
          "type":"org.bluetooth.characteristic.firmware_revision_string","properties":["read"]}
    service.characteristics length 
          : 3
--------------------------------------------------------------------------------
<img width="1244" alt="스크린샷 2019-04-23 오전 10 51 02" src="https://user-images.githubusercontent.com/49893516/56554555-0b12e700-65cd-11e9-945f-0ee32d2a1597.png">

5. Tool check List  is following.
 - Tool check that just '180a'

_assert.isDefined(services['180a'], 'Authenticator MUST implement "Device Information" service!');
        assert.isDefined(services['180a'].characteristics['2a29'], '"Device Information" missing "Manufacturer Name String" characteristic(0x2A29)!');
        assert.isDefined(services['180a'].characteristics['2a24'], '"Device Information" missing "Model Number String" characteristic(0x2A24)!');
        assert.isDefined(services['_**180a**_'].characteristics['_**2a26**_'], '"Device Information" missing "Firmware Revision String" characteristic(0x2A26)!');_

<img width="1073" alt="스크린샷 2019-04-23 오전 10 57 14" src="https://user-images.githubusercontent.com/49893516/56555095-ba9c8900-65ce-11e9-904e-3be3c5588364.png">

**Comment by maxwang-dev** [comment]
I still have same issue using conformance tool v1.1.2.
What is the solution?
