### ISSUE TITLE
It seems wrong date of the certificate.

### ISSUE THREAD

**Issue by kg0r0** [fido-alliance/conformance-tools-issues#460]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.211

## What is the OS and the version are you running?
macOS mojave 10.14.4

## Issue description
This version has the following test cases.
> F-6 Send ServerAuthenticatorAttestationResponse with FULL "packed" attestation, with attStmt.x5c contains a leaf certificate that is expired, and check that server returns an error

> F-7 Send ServerAuthenticatorAttestationResponse with FULL "packed" attestation, with attStmt.x5c contains a leaf certificate that is not yet started, and check that server returns an error 

If I want to pass this test, I should do the following.

```
    const jsrsasign = require('jsrsasign');
    const subjectCert = new jsrsasign.X509();
    subjectCert.readCertPEM(certificate);
    const now = (new Date().getTime());
    const notbefore  = Number(subjectCert.getNotBefore().slice(0, -1));
    const notafter = Number(subjectCert.getNotAfter().slice(0, -1));

    if (now < notbefore)
        throw new Error('Leaf certificate is not yet started!')

    if (notafter < now)
        throw new Error('Leaf certificate is expired!')
```

However, the certificate that sent from conformance tool is valid from 180523143943 to 280520143943 in unix timestamp when it is normal.
```
notbefore: 180523143943
now: 1556437489801
notafter: 280520143943
```

It seems wrong date of the certificate that sent from conformance tool.

I confirmed that it is not problem if  I use Yubico Security Key.
```
notbefore: 140801000000
now: 1556437581869
notafter: 20500904000000
```

**Comment by herrjemand** [comment]
The dates are stored in ITU generalised time(year, month, date, hour, minute, second, time zone) https://en.wikipedia.org/wiki/GeneralizedTime

https://github.com/kjur/jsrsasign/issues/171
