### ISSUE TITLE
Unable to parse FIDO2 MDS conformance CRL

### ISSUE THREAD

**Issue by bdewater** [fido-alliance/conformance-tools-issues#461]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?
Server

## What is the version of the tool are you using?
v1.0.0

## What is the OS and the version are you running?
MacOS 

## Issue description
I seem to be running into the same issue as https://github.com/fido-alliance/conformance-tools-issues/issues/348 although in this case I'm using Ruby on macOS. Here's a small repro script:

```ruby
require "net/http"
require "openssl"

URIS = [URI("http://mds.fidoalliance.org/CA-1.crl"),
  URI("http://mds.fidoalliance.org/Root.crl"),
  URI("https://fidoalliance.co.nz/mds/crl/MDSCA-1.crl"),
  URI("https://fidoalliance.co.nz/mds/crl/MDSROOT.crl")]

puts "Ruby #{RUBY_VERSION}, OpenSSL gem #{OpenSSL::VERSION}, system #{OpenSSL::OPENSSL_LIBRARY_VERSION}"

URIS.each do  |uri|
  response = Net::HTTP.get(uri)
  begin
    OpenSSL::X509::CRL.new(response)
    puts "Parsed #{uri}!"
  rescue OpenSSL::X509::CRLError => e
    puts "Unable to parse #{uri}: #{e}"
    puts "Tried to parse:\n#{response}\n\n"
  end
end
```
outputs:
```
Ruby 2.5.3, OpenSSL gem 2.1.2, system OpenSSL 1.0.2q  20 Nov 2018
Parsed http://mds.fidoalliance.org/CA-1.crl!
Parsed http://mds.fidoalliance.org/Root.crl!
Unable to parse https://fidoalliance.co.nz/mds/crl/MDSCA-1.crl: nested asn1 error
Tried to parse:
-----BEGIN X509 CRL-----
MIIB4DCCAYYCAQEwCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBDQS0xIEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIyMDIwMTAwMDAwMFowgcAwLgIPBIBnSd4we71RdaJtc/XzFw0xNjA0MTMwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBKrcrAkXZP7iBYVsmlmcFw0xNzAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBM/iRZCgM44GmST78MnBFw0xNjAzMDEwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBDEcYqIEsOt7TAac8B9TFw0xODAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQCjKzApMAoGA1UdFAQDAgEBMBsGA1UdIwQUTW7NImYi
eprbiocSbowQe8ZcjzgwCgYIKoZIzj0EAwIDSAAwRQIgKmj6o9GlscX7/a7w+aSx
AsEYXfy2Nhoiuy1FyMrKhLsCIQDc6a63az1EbJQdErrEmn6u8wD5WR0AGRUnT0Td
JIWgUQ==
-----END X509 CRL-----

Unable to parse https://fidoalliance.co.nz/mds/crl/MDSROOT.crl: nested asn1 error
Tried to parse:
-----BEGIN X509 CRL-----
MIIB0jCCAVkCAQEwCgYIKoZIzj0EAwMwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBSb290IEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIwMDIwMTAwMDAwMFowgZMwLwIQBCZYfWbvAtCiCiDkzlVBNhcNMTQwMzAxMDAw
MDAwWjAMMAoGA1UdFQQDCgEAMC8CEBChCltfJqUItgJxvHK+UWQXDTE0MDQxMzAw
MDAwMFowDDAKBgNVHRUEAwoBADAvAhB3RNBE2qraHviPj0SPvjXQFw0xNTAzMjUw
MDAwMDBaMAwwCgYDVR0VBAMKAQCjKzApMAoGA1UdFAQDAgEBMBsGA1UdIwQUY1Ea
ILhb+xmToZiafvM6VRsmwHkwCgYIKoZIzj0EAwMDZwAwZAIwdVkVWVCtZHM2vUpq
pRNU5rlqPnp1GGeFJhNqijlb/QKWp4VTc54BpNYqiLZukH84AjAWRDIEnFszkVP4
btg9m/+w1Hz/EvLUbtqrbBjVKdMPppqDGrCtJfYM5C3/WbtsUlI=
-----END X509 CRL-----
```

Inputting these values into https://lapo.it/asn1js/ shows the encoding is `[3]` instead if `[0]` just as described in the original issue.

**Comment by aseigler** [comment]
The authorityKeyIdentifier in the CRL is malformed in the same manner as in #438

**Comment by herrjemand** [comment]
Please try getting new endpoints. Should be fixed now

**Comment by bdewater** [comment]
I'm afraid I'm still getting errors @herrjemand:
```
Unable to parse https://fidoalliance.co.nz/mds/crl/MDSCA-1.crl: nested asn1 error
Tried to parse:
-----BEGIN X509 CRL-----
MIIB5TCCAYoCAQEwCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBDQS0xIEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIyMDIwMTAwMDAwMFowgcAwLgIPBJvhtKHjPwteeGHG3B7VFw0xNjA0MTMwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBBSpsISjx2TgSiPcaQXVFw0xNzAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBNqdJFe/9Ap4Eh1ly678Fw0xNjAzMDEwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBIBnSd4we71RdaJtc/XzFw0xODAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQCjLzAtMAoGA1UdFAQDAgEBMB8GA1UdIwQYMBaAFFBa
Ubxo9hKU9MSPAXOyAdzujD8yMAoGCCqGSM49BAMCA0kAMEYCIQD70UP6o+cnalcd
mqLHUVIFjvabUYVSScNGG+K++vvOKwIhAKobvoYLiRaMoWB9eLKXBTGrsN9EzM9Q
5O5aaTaCr0HI
-----END X509 CRL-----

Unable to parse https://fidoalliance.co.nz/mds/crl/MDSROOT.crl: nested asn1 error
Tried to parse:
-----BEGIN X509 CRL-----
MIIB1zCCAV0CAQEwCgYIKoZIzj0EAwMwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBSb290IEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIwMDIwMTAwMDAwMFowgZMwLwIQBCZYfWbvAtCiCiDkzlVBNhcNMTQwMzAxMDAw
MDAwWjAMMAoGA1UdFQQDCgEAMC8CENvfmsYLNTL8suw5+P0OzVMXDTE0MDQxMzAw
MDAwMFowDDAKBgNVHRUEAwoBADAvAhAG6Epu1kejfI8iKuWc4DtZFw0xNTAzMjUw
MDAwMDBaMAwwCgYDVR0VBAMKAQCjLzAtMAoGA1UdFAQDAgEBMB8GA1UdIwQYMBaA
FN33msgc7+Ff06Hr2zNfMPRqGZlZMAoGCCqGSM49BAMDA2gAMGUCMQCETOUURiSR
h0PyJ6R/2GLZtCrSVA9gBk04b0/o+3ND8QVzLHgCozP4oTKtNDG+xw0CMC6M//2D
erqjWaWx4eNvPRAVLGGtmlYlSMGhWil/TaUIx5LwxRsnF7AwD4cso1A5QQ==
-----END X509 CRL-----
```

**Comment by bdewater** [comment]
Here's a REPL in case you want to try some fixes: https://repl.it/@bartdewater/Parse-FIDO-MDS-conformance-CRL

**Comment by aseigler** [comment]
I was able to patch the CRL to make it valid.  I am not sure how this CRL is being generated, but here is the problem:

Bad:

![image](https://user-images.githubusercontent.com/6605560/57019522-ca325800-6bf4-11e9-9eab-ef3e5c9f04ac.png)

Good:

![image](https://user-images.githubusercontent.com/6605560/57019587-f9e16000-6bf4-11e9-8403-1296f4763120.png)

**Comment by bdewater** [comment]
Could you share those patched CRL files @aseigler? 🙌

**Comment by aseigler** [comment]
Root:

-----BEGIN X509 CRL-----
MIIB1zCCAV0CAQEwCgYIKoZIzj0EAwMwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBSb290IEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIwMDIwMTAwMDAwMFowgZMwLwIQBCZYfWbvAtCiCiDkzlVBNhcNMTQwMzAxMDAw
MDAwWjAMMAoGA1UdFQQDCgEAMC8CENvfmsYLNTL8suw5+P0OzVMXDTE0MDQxMzAw
MDAwMFowDDAKBgNVHRUEAwoBADAvAhAG6Epu1kejfI8iKuWc4DtZFw0xNTAzMjUw
MDAwMDBaMAwwCgYDVR0VBAMKAQCgLzAtMAoGA1UdFAQDAgEBMB8GA1UdIwQYMBaA
FN33msgc7+Ff06Hr2zNfMPRqGZlZMAoGCCqGSM49BAMDA2gAMGUCMQCETOUURiSR
h0PyJ6R/2GLZtCrSVA9gBk04b0/o+3ND8QVzLHgCozP4oTKtNDG+xw0CMC6M//2D
erqjWaWx4eNvPRAVLGGtmlYlSMGhWil/TaUIx5LwxRsnF7AwD4cso1A5QQ==
-----END X509 CRL-----


Intermediate:

-----BEGIN X509 CRL-----
MIIB5TCCAYoCAQEwCgYIKoZIzj0EAwIwZzELMAkGA1UEBhMCVVMxFjAUBgNVBAoM
DUZJRE8gQWxsaWFuY2UxJzAlBgNVBAsMHkZBS0UgTWV0YWRhdGEgVE9DIFNpZ25p
bmcgRkFLRTEXMBUGA1UEAwwORkFLRSBDQS0xIEZBS0UXDTE4MDIwMTAwMDAwMFoX
DTIyMDIwMTAwMDAwMFowgcAwLgIPBJvhtKHjPwteeGHG3B7VFw0xNjA0MTMwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBBSpsISjx2TgSiPcaQXVFw0xNzAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBNqdJFe/9Ap4Eh1ly678Fw0xNjAzMDEwMDAw
MDBaMAwwCgYDVR0VBAMKAQAwLgIPBIBnSd4we71RdaJtc/XzFw0xODAzMjUwMDAw
MDBaMAwwCgYDVR0VBAMKAQCgLzAtMAoGA1UdFAQDAgEBMB8GA1UdIwQYMBaAFFBa
Ubxo9hKU9MSPAXOyAdzujD8yMAoGCCqGSM49BAMCA0kAMEYCIQD70UP6o+cnalcd
mqLHUVIFjvabUYVSScNGG+K++vvOKwIhAKobvoYLiRaMoWB9eLKXBTGrsN9EzM9Q
5O5aaTaCr0HI
-----END X509 CRL-----

**Comment by bdewater** [comment]
@herrjemand I just checked again and the CRLs are still broken. While I can stub HTTP calls in my Ruby test suite to return the patched files @aseigler was so kind to provide, I will not be able to run the conformance tool on the implementation. 

Can this issue be reopened until the problem is actually fixed?

**Comment by herrjemand** [comment]
@bdewater how about now?

**Comment by herrjemand** [comment]
I have regenerated CRL

**Comment by herrjemand** [comment]
sigh...

**Comment by herrjemand** [comment]
I dont know what was that. Fixed now

**Comment by aseigler** [comment]
Confirmed, both look good now.  Thanks!

**Comment by herrjemand** [comment]
Weeeee! Thanks @aseigler and @bdewater for your help!

**Comment by bdewater** [comment]
Thanks @herrjemand !

**Comment by Spomky** [comment]
Hi,

Excuse my ignorance and for digging up this topic, but where did you found all the CRL urls?
I haven't found these in the root certificates.
Thank you for your help.
