### ISSUE TITLE
Problem in Attestation Certificates

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#462]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0/

## What is your implementation class?

Server

## What is the version of the tool are you using?

v1.1.0

## Issue description

The below leaf certificate used in TPM attestation has no subject and its authority key identifier didn't match with that of the intermediate certificate. Therefore the verification is failed.

![image](https://user-images.githubusercontent.com/5744623/57062050-04d1e880-6cfa-11e9-8bab-4012f23a607e.png)

The below leaf certificate used in Android SafetyNet attestation has authority key identifier that didn't match with that of the intermediate certificate. Therefore the verification is failed.

![image](https://user-images.githubusercontent.com/5744623/57062267-a2c5b300-6cfa-11e9-93a5-191c1b16f011.png)

Can you also check the certficiates used in Android keystore?  The verification of digital signature in the leaf certificate was failed.

**Comment by herrjemand** [comment]
@sangraecho I have regenerated PKI for TPM and SafetyNet. New build in few hours

**Comment by sangraecho** [comment]
Certificates in Android Safetynet is ok now. 

But certificates in TPM still has the same problem.
We couldn't find the issuer of the intermediate CA certificate because authority key identifier of the intermediate CA certificate doesn't match with subject key identifier of the root CA Certificate.

**Comment by herrjemand** [comment]
C to the L to the O to the SED!
