### ISSUE TITLE
The U2F server test still fails with FCT v1.1.0

### ISSUE THREAD

**Issue by whwjdghks** [fido-alliance/conformance-tools-issues#463]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F

## What is your implementation class?

Server

## What is the version of the tool are you using?

FCT v1.1.0

## What is the OS and the version are you running?

Windows7

## Issue description

Thanks for [issue 457](https://github.com/fido-alliance/conformance-tools-issues/issues/457).
But there still seems to be some problems.

### Server-Register-Resp-1.js

Is the usage of strictEqual function wrong?
It worked well if we fix it as follows.

> //assert.strictEqual(response.registeredKeys.length === 1, 'Expected to get exactly 1 registered key, as only one registration was performed!');
> assert.strictEqual(response.registeredKeys.length, 1, 'Expected to get exactly 1 registered key, as only one registration was performed!');

### Server-Sign-Req-1.js

'challenge' does not exist in Request but is in Response.
It worked well if we fix it as follows.

>  //assert.isString(request.challenge, 'Expected "challenge" to be of type String');
>  //assert.isNotEmpty(request.challenge, 'Expected "challenge" not to be empty!');
>  //assert.match(request.challenge, /^[a-zA-Z0-9_-]+$/, 'Expected "challenge" to be base64URL(without padding) encoded!');
>  assert.isString(response.challenge, 'Expected "challenge" to be of type String');
>  assert.isNotEmpty(response.challenge, 'Expected "challenge" not to be empty!');
>  assert.match(response.challenge, /^[a-zA-Z0-9_-]+$/, 'Expected "challenge" to be base64URL(without padding) encoded!');

###  Server-Sign-Resp-1.js

Function 'expectPromiseToFail' and 'describe' seems to be required in this case.
For example, function 'describe' seems to be required in F-1, F-5 and F-9.
If it does not used, that test is not executed.
(It meens nested test cases needs to 'describe' function.)

###  Server-Sign-Resp-3.js

The argument 'identity' of function getSign is the server's positive response.
It is not result of function generateRandomIdentity.

Please check the second 'getSign(identity)'.
(P-1 and F-2)

>     it(`P-1
>             
>          Perform a valid Register flow, send two consecutive Sign flows, and check that server succeeds 
> 
>     `, () => {
>         return registerIdentity()
>             .then((identity) => {
>                 return getSign(identity) // identity is result of function generateRandomIdentity.
>             })
>             .then((response) => {
>                 return U2FAuthr.sign(response.appId, response.challenge, response.registeredKeys)
>             })
>             .then((authrResponse) => {
>                 return signResponse(authrResponse)
>             })
>             .then((identity) => {
>                 return getSign(identity) // identity is server's positive response.
>             })
>             .then((response) => {
>                 return U2FAuthr.sign(response.appId, response.challenge, response.registeredKeys)
>             })
>             .then((authrResponse) => {
>                 return signResponse(authrResponse)
>             })
>     })

**Comment by herrjemand** [comment]
Resolved
