### ISSUE TITLE
Issues in TPM attestation certificate mismatch authority key identifier

### ISSUE THREAD

**Issue by berrikso** [fido-alliance/conformance-tools-issues#464]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.1.2

## What is the OS and the version are you running?

Windows 7

## Issue description

I am experiencing failures when running the tests below. 
* ```Server-ServerAuthenticatorAttestationResponse-Resp-9 ``` 
   * ```P-1 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation for SHA-256..```
   * ```P-2 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation for SHA-1...```
   * ```P-3 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation pubArea.nameAlg ...```

I am using metadata from *app-1.1.2\resources\app\modules\fido2-conformance-module\metadata*.

When I observe ```CTAP2RSA15SHA256TPMAttestation.metadata.json``` and ```CTAP2RSA15SHA1TPMAttestation.metadata.json```, their root attestion certificate  (CN=FIDO Fake TPM Root Certificate Authority 2018) has X509v3 Subject Key Identifier **43:11:16:99:9A:EE:9D:50:37:C2:4F:FE:E2:5B:15:C9:09:33:3F:32**.

The TPM attestations sent by FCT is signed by an  (CN=NCU-NTC-KEYID-037AF738110F96054DCDF082EFFA031F9BF810AF). However, this NCU-NTC-KEYID-... certificate has X509v3 Authority Key Identifier **5C:7F:36:2D:90:AD:5A:BC:BA:8E:75:DA:DE:3A:A0:ED:C1:4E:02:8B**

This is breaking the certificate chain validation due to mismatch of FIDO TPM Root Certificate subject key identifier and NCU-NTC-KEYID's authority key identifier. 

From the above, I am assuming that there is an update for the TPM Root certificate. If so, in the meantime, where can I find the TPM Root certificate being used to sign the NCU-NTC-KEYID... cert ?  (Unfortunately the *fido2-conformance-module\pki\TPMROOT.crt* subject key identifier is also **43:11:16:99:9A:EE:9D:50:37:C2:4F:FE:E2:5B:15:C9:09:33:3F:32**)

Thank you in advance

**Comment by vs-nnl** [comment]
Any update on this issue?

**Comment by herrjemand** [comment]
It is now fixed. Was issue with negative value.
