### ISSUE TITLE
Issue in conformance-tool FIDO2 MetadataStatement

### ISSUE THREAD

**Issue by todowenil** [fido-alliance/conformance-tools-issues#466]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.218

## Issue description

In Virtual RSA PKCS 1.5 SHA1 FIDO2 Conformance Testing CTAP2 Authenticator with TPM Attestation.json that attestationTypes define [ 15879 (ATTESTATION_BASIC_FULL), 15880 (ATTESTATION_BASIC_SURROGATE) ]

But doc defined as bellow,
![image](https://user-images.githubusercontent.com/49049220/57599157-61e65d80-7588-11e9-87fc-0ebd23bdb52b.png)

**Comment by herrjemand** [comment]
Updatete to 1.1.2
