### ISSUE TITLE
Problem in P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-key" attestation, and check that server succeeds

### ISSUE THREAD

**Issue by todowenil** [fido-alliance/conformance-tools-issues#467]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
v1.1.2

## Issue description
When testing following case:
P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-key" attestation, and check that server succeeds

And check cert chain fail, is intermediate cert right?
x5c[0]:
IssuerDN: CN=FAKE Android Keystore Software Attestation Intermediate FAKE,E=conformance-tools@fidoalliance.org,O=FIDO Alliance,**OU=CWG**,C=US,ST=MY,L=Wakefield
X509v3 Authority Key Identifier: 
                keyid:52:9A:1B:32:E0:56:AA:CD:51:0F:EF:5F:80:37:06:8B:F2:91:23:1D

x5c[1]:
SubjectDN: CN=FAKE Android Keystore Software Attestation Intermediate FAKE,E=conformance-tools@fidoalliance.org,O=FIDO Alliance,**OU=Authenticator** Attestation,C=US,ST=MY,L=Wakefield
X509v3 Subject Key Identifier: 
                A3:D2:AA:2C:EF:0D:8C:F2:24:02:D5:1C:B4:60:BC:BF:6A:5B:24:14

**Comment by herrjemand** [comment]
Fixed now!
