### ISSUE TITLE
txAuthSimple transaction confirmation tests force errors on empty strings but this is not specified.

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#470]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?

Unknown

## What is the OS and the version are you running?
Windows.

## Issue description

The tests force the authenticator to return an error if the provided string is empty: there is no basis in the specs for this and the tests should not invent extra rules. 
The test should be removed.

**Comment by herrjemand** [comment]
Fixed in the newest build
