### ISSUE TITLE
Android SafetyNet metadata specifies AttCA instead of Basic as attestation type

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-tools-issues#471]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v1.1.3

## What is the OS and the version are you running?

Windows 10

## Issue description

In test Server-ServerAuthenticatorAttestationResponse-Resp-B, part P-1 an "android-safetynet" attestation is sent by the tool. This results in Basic attestation since this is the only type supported by SafetyNet. However, the metadata file `Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json` has attestationTypes  of `[15882]` (0x3E0A, AttCA), causing the server to fail.

**Comment by herrjemand** [comment]
This needs to be clarified with Google

**Comment by herrjemand** [comment]
Okay, fixed now
