### ISSUE TITLE
Testing "Registration" command (failed)

### ISSUE THREAD

**Issue by motionkiev** [fido-alliance/conformance-tools-issues#472]
## What protocol and version of the protocol are you testing?

U2F v1.2

## What is your implementation class?

U2F authenticator (USB key/token)

## What is the version of the tool are you using?

v1.1.3 (U2F 1.1)

## What is the OS and the version are you running?

Windows 10

## Issue description

For processing "Register" command (generating pair of keys, etc.), I need 250-300 ms.  

But testing tool have a timeout for the response of about 200-250 ms and then it repeats the command (again and again, in cycle).

After receiving the first command, I am starting to process it.

In 200-250 ms I am receiving the second "Register" command (during processing first command)

How should I answer to the second "Register" command?

Specifications don't describe this case.

I tried - ERR_CHANNEL_BUSY (that intended for another situation), KEEP_ALIVE (doesn't support by this version of protocol) and ignore the second command.

Only after ignoring, I successfully passed the test.

![Result 1](https://user-images.githubusercontent.com/48795888/60031722-e9f27380-96ad-11e9-88df-1e5b1fd16c2a.png)

![Data exchange 1](https://user-images.githubusercontent.com/48795888/60031729-ee1e9100-96ad-11e9-96a8-a0ad7b92f4a1.png)

During "Test Authentication", the first test is the same "Register" command with some additions.
The data exchange is the same (as in the "Test Registration", except the payloads of the requests and responses), but test fails (with error - "Sequence out of order"). Why I have 2 various results with the same data packets (all the same)?

![Result 2](https://user-images.githubusercontent.com/48795888/60032920-3b9bfd80-96b0-11e9-97cd-238e03f8a7fa.png)

![Data exchange 2](https://user-images.githubusercontent.com/48795888/60032924-3fc81b00-96b0-11e9-820b-e4b94ef2bdf9.png)

**Comment by motionkiev** [comment]
Is it possible to increase the timeout to bigger value?

**Comment by herrjemand** [comment]
@motionkiev I have added timeout of 500ms

**Comment by motionkiev** [comment]
I downloaded new version (1.1.4), but it has the same timeout (250 ms).

**Comment by motionkiev** [comment]
![log](https://user-images.githubusercontent.com/48795888/61777057-f4b33c00-ae04-11e9-9fcf-78a7ff199f06.png)
