### ISSUE TITLE
Server-ServerAuthenticatorAssertionResponse-Resp-3 F1 endpoints mismatch

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-tools-issues#473]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v1.1.3

## What is the OS and the version are you running?

Windows 10

## Issue description

In `Server-ServerAuthenticatorAssertionResponse-Resp-3`, test `F-1 Send ServerAuthenticatorAssertionResponse with authenticatorData contains leftover bytes, and check that server returns an error` the test tool requests an assertion (`/assertion/options`), but sends an assertion response to the attestation response endpoint (`/attestation/result`). This fails because there is no proper context, and the data posted is of the wrong type. Since it is a negative test a failure response passes the test, but the test is not correctly testing the leftover bytes situation.

**Comment by herrjemand** [comment]
Thanks @madwizard-thomas! Will be fixed in the next build.
