### ISSUE TITLE
ASM authenticate not launched if tcDisplay is 0 and the tcDisplayContentType is not set

### ISSUE THREAD

**Issue by andreasluca** [fido-alliance/conformance-tools-issues#474]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
ASM+Authr

## What is the version of the tool are you using?
v1.4.4

## What is the OS and the version are you running?
Android 9

## Issue description
When launching the ASM authenticate tests, the tests expect the metadatastatements to have the tcDisplayContentType field set, which is a not required field in the specifications when the tcDisplay is set to 0.

Example:
metadataStatemts:
{
...
"tcDisplay": 0,
...
}

Launch ASM **Authenticate** tests -> an error appears and won't execute the tests because tcDisplayContentType is not set (which is a not required field).

**Comment by herrjemand** [comment]
Can't reproduce
