### ISSUE TITLE
ServerAuthenticatorAssertionResponse-Resp-3 F-4 false positive because of invalid UV bit 

### ISSUE THREAD

**Issue by grzuy** [fido-alliance/conformance-tools-issues#475]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v1.1.4

## What is the OS and the version are you running?

macOS High Sierra 10.13.3

## Issue description

GetAssertion Resp-3 F-4 test, which, according to it's message

> F-4 For authenticator that supports counter: Send ServerAuthenticatorAssertionResponse with authenticatorData.counter is not increased, and check that server returns an error

is testing that the server verifies an invalid signCount value, it is also sending an invalid UV bit.

By this I mean, in the `/assertion/options` it sends `userVerification: required`, and in the following `/assertion/result` the UV bit is set to `0`.

This means that, if the server, has working UV bit verification but not signCount verification, this test could result in a false positive.

**Comment by herrjemand** [comment]
Thx! Fixed now!
