### ISSUE TITLE
UAF v1.1 iOS API Test - incorrect error message for P-4

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#478]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
v1.4.4

## What is the OS and the version are you running?
iOS

## Issue description
The UAF v1.1 iOS API Test P-4 DISCOVER request returns an incorrect error message. It indicates that the tcDisplayContentType does not match, but it was actually the tcDisplayPNGCharacteristics that didn't match. 

This is the error message. You will notice that it indicates it expects Array(1) to deeply equal Array(1). tcDisplayContentType is a String, not an array. tcDisplayPNGCharacteristics is an array.
![Screen Shot 2019-07-08 at 3 55 08 PM](https://user-images.githubusercontent.com/1010379/60889033-1669cc00-a226-11e9-9439-6e838cadca76.png)

This is how I figured out that the error message was incorrect. The same message is used for tcDisplayContentType and tcDisplayPNGCharacteristics.
![Screen Shot 2019-07-08 at 3 49 45 PM](https://user-images.githubusercontent.com/1010379/60889069-297c9c00-a226-11e9-91db-d0f5fd73e4e0.png)

**Comment by herrjemand** [comment]
Thx, I will take a look.

**Comment by herrjemand** [comment]
Thx. Fixed now!
