### ISSUE TITLE
UAF V1.1 iOS - AppID and Facets

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#479]
## What protocol and version of the protocol are you testing?
UAF v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
v1.4.4 (NOTE: It would be helpful to add the version to the "About" page.)

## What is the OS and the version are you running?
iOS 12.3.1

## Issue description
The AppID and Facets tests for Registration are working. The AppID URL for all of the negative test cases return the correct trusted facets JSON for the test. However, the AppID and Facets tests for Authentication and Deregistration do not appear to be working correctly. The negative test cases always return valid trusted facets JSON for the AppID URL. Specifically tests F-1 through F-11 and F-19 through F-21.

This is the valid trusted facets JSON that is always returned for the Authentication and Deregistration AppID and Facets negative tests.
```javascript
{"trustedFacets":[{"version":{"major":1,"minor":0},"ids":["ios:bundle-id:org.fidoalliance.mobile.conformancetools","https://fidoalliance.nz/"]}]}
```

Screenshot for reference.
![Screen Shot 2019-07-08 at 4 57 09 PMx](https://user-images.githubusercontent.com/1010379/60890633-ae1ce980-a229-11e9-86ac-14dbe1c70476.png)

**Comment by mirkop** [comment]
It turns out that the client was caching the trusted facet data. It is allowed to do that as long as it respects the Expires response header. The AppID URL is not setting that response header.

7. The caching related HTTP header fields in the HTTP response (e.g. “Expires”) should be respected when fetching a Trusted Facets List.

Also, the authentication AppID tests use the same URL for all of the tests. I believe that the Registration tests are using different AppID URLs for each test.

8. The server hosting the Trusted Facets List must respond uniformly to all clients. That is, it must not vary the contents of the response body based on any credential material, including ambient authority such as originating IP address, supplied with the request.

The server hosting the Trusted Facets List is also not setting the MIME Content-Type of "application/fido.trusted-apps+json"

6. The response must set a MIME Content-Type of "application/fido.trusted-apps+json".

**Comment by herrjemand** [comment]
Okay, I will update expiration headers

**Comment by herrjemand** [comment]
Fixed
