### ISSUE TITLE
UAF V1.1 iOS - Algorithm

### ISSUE THREAD

**Issue by FionJHYang** [fido-alliance/conformance-tools-issues#480]
## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Client/ASM+Authr

## What is the version of the tool are you using?

v1.4.4

## What is the OS and the version are you running?

iOS 10

## Issue description

Hi,

I have a problem while testing my iOS application on FIDO UAF 1.1 conformance tool. The algorithm I use is “ALG_SIGN_RSA_EMSA_PKCS1_SHA256_RAW”, but the tool return wrong and the error message is “Uknown signature algorithm ALG_SIGN_RSA_EMSA_PKCS1_SHA256_RAW”.

Although iOS do provide method to sign with algorithm "ALG_SIGN_RSASSA_PSS_SHA256_RAW" , it is not available under version 11.0.

So is there a way to pass the test using algorithm “ALG_SIGN_RSA_EMSA_PKCS1_SHA256_RAW” ?

Thank you for any response.

**Comment by mirkop** [comment]
The conformance tool does not support that algorithm because the libraries that they use do not have support for it. Unless something has changed that I am not aware of.

See this issue: https://github.com/fido-alliance/conformance-tools-issues/issues/444

**Comment by FionJHYang** [comment]
> The conformance tool does not support that algorithm because the libraries that they use do not have support for it. Unless something has changed that I am not aware of.
> 
> See these issues: #94 #444

@mirkop Thank you for your response.  I'll email FIDO to see if they have any suggestions for this case.
