### ISSUE TITLE
UAF 1.1 Server-Reg-Req-4 P-10

### ISSUE THREAD

**Issue by belletda-ui** [fido-alliance/conformance-tools-issues#483]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF

## What is your implementation class?

Server
## What is the version of the tool are you using?

V1.1.0
## What is the OS and the version are you running?
Windows 10

## Issue description
Server-Reg-Req-4 P-10

![fido10-3](https://user-images.githubusercontent.com/52491945/61540390-ba921500-aa67-11e9-84d1-da75d6af3c35.png)
In this scenario, expected 3 pairs of aaid and keyIDs alter each test round.
How can I send aaid and keyIDs as the tools expected ?

**Comment by herrjemand** [comment]
The tool registers three credentials. The server must return their credential identifiers in the disallow policy to ensure that the same authenticator was not double registered.

**Comment by herrjemand** [comment]
The box you've highlighted shows what tools expects

**Comment by belletda-ui** [comment]
> The tool registers three credentials. The server must return their credential identifiers in the disallow policy to ensure that the same authenticator was not double registered.

Thank

 you for your answer. But What I don't understandard is why the tool expects **different KeyIDs ** each round that I test.  Let me show you some result below. I tried 3 rounds for test. I got different 3 keyIDs for each round.

**1st round** 

![UAF 1 1 Server-Reg-Req-4 P-10 ROUND-1](https://user-images.githubusercontent.com/52491945/61698348-2a9fe400-ad63-11e9-8846-f50c6d6aaf91.png)

**2nd round** 
![UAF 1 1 Server-Reg-Req-4 P-10 ROUND-2](https://user-images.githubusercontent.com/52491945/61698376-37243c80-ad63-11e9-9d6b-1a030266c5ff.png)

**3rd round** 
![UAF 1 1 Server-Reg-Req-4 P-10 ROUND-3](https://user-images.githubusercontent.com/52491945/61698384-3b505a00-ad63-11e9-90de-648d849dc5c7.png)


Could you tell me what step should do ? What step the tool registers three credentials ?

**Comment by nehavij** [comment]
I am having the issue for the same Server-Reg-Req-4 P-10 .Can someone explain how to get it work.
