### ISSUE TITLE
Authr-MakeCred-Req-4, F-7 is incorrect

### ISSUE THREAD

**Issue by jovasco** [fido-alliance/conformance-tools-issues#487]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.1.4

## What is the OS and the version are you running?

Windows.

## Issue description

The test changes a single pubKeyCredParams type from "public-key" to a random string and expects an CTAP2_ERR_UNSUPPORTED_ALGORITHM(0x26) error.

This is incorrect. 

type is en extension point and any unknown value should be ignored. 

The CTAP2_ERR_UNSUPPORTED_ALGORITHM(0x26) error should only be returned if this is the ONLY algorithm.

I already reported this is #160 and it is supposedly fixed and has now been returned to the fail tests again?

**Comment by jovasco** [comment]
From https://www.w3.org/TR/webauthn/#enumdef-publickeycredentialtype ,

> This enumeration defines the valid credential types. It is an extension point; values can be added to it in the future, as more credential types are defined.

And from out CTAP spec:

> If the pubKeyCredParams parameter does not contain a valid COSEAlgorithmIdentifier value that is supported by the authenticator, terminate this procedure and return error code CTAP2_ERR_UNSUPPORTED_ALGORITHM.

Which means that as long as there is an algorithm that is supported by the authenticator, the authenticator should NOT return CTAP2_ERR_UNSUPPORTED_ALGORITHM.

All in all, if authenticator return an error if this value is not public-key, it will cause issues if in the future another type is added.

**Comment by jovasco** [comment]
This is one of the requests sent:

> {1: h'8DA20B13E339ABDF9A5F7AF3D6479FF1E7F50E8EEF11C2A0E78D798064BDCA95', 2: {"id": "huckleberrypineapple.mk", "name": "The Example Corporation with fake domain!"}, 3: {"id": h'F77A9D1C6D5865FA4CEC19EF46E312A0FB10878F779D011BDD275EA5FF4B0D13', "icon": "https://pics.acme.com/00/p/aBjjjpqPb.png", "name": "sharda.manier@previousshame.jp", "displayName": "Sharda Manier"}, 4: [{"alg": -7, "type": "fork"}, {"alg": -7, "type": "public-key"}]}

Which means that any authenticator that supports ES256 as protocol (which is the most common, I think), and that passes this test is non-compliant and will break if another type is ever introduced.

**Comment by herrjemand** [comment]
@jovasco I see what happens. So I fixed test. Then I've added params generation for multiple algorithms. And that broke the test for people who support more than one algorithm.

Will be fixed next version!

**Comment by jovasco** [comment]
We only support 1 algorithm...
