### ISSUE TITLE
Android Keystore certificate path validation issue

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-tools-issues#489]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
Mac

## Issue description

I am observing a failing test case which I believe is because the tool is sending the wrong attestation certificate:

Server-ServerAuthenticatorAttestationResponse-Resp-A Test server processing "android-key" attestation
P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-key" attestation, and check that server succeeds

Here's a captured set of data from the conformance tool sent to the server:
{"id":"vGbofwPHA8cILW0tz7gfxeN9yIhk2Pd-rdRcxBIqXas","rawId":"vGbofwPHA8cILW0tz7gfxeN9yIhk2Pd-rdRcxBIqXas","response":{"attestationObject":"o2NmbXRrYW5kcm9pZC1rZXlnYXR0U3RtdKNjYWxnJmNzaWdYRzBFAiAkeqMyiX_jVI1262KIBkwy_2o7ulBIZD3Qum5o0TMs9wIhAO8QDg9kXtGMr6FonsKqUPhcI4-IeWaOxMSc8pW2KTNJY3g1Y4JZAwUwggMBMIICp6ADAgECAgEBMAoGCCqGSM49BAMCMIHOMUUwQwYDVQQDDDxGQUtFIEFuZHJvaWQgS2V5c3RvcmUgU29mdHdhcmUgQXR0ZXN0YXRpb24gSW50ZXJtZWRpYXRlIEZBS0UxMTAvBgkqhkiG9w0BCQEWImNvbmZvcm1hbmNlLXRvb2xzQGZpZG9hbGxpYW5jZS5vcmcxFjAUBgNVBAoMDUZJRE8gQWxsaWFuY2UxDDAKBgNVBAsMA0NXRzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1ZMRIwEAYDVQQHDAlXYWtlZmllbGQwIBcNNzAwMjAxMDAwMDAwWhgPMjA5OTAxMzEyMzU5NTlaMCkxJzAlBgNVBAMMHkZBS0UgQW5kcm9pZCBLZXlzdG9yZSBLZXkgRkFLRTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL0iFCFvtC90dvMA4n8y8e8VZ7A3ct8eh2RFKryiiKjvLas7lJEVTDHACNxAOqCmMwSDeQTnivfsXX8yQqU2W0GjggEWMIIBEjALBgNVHQ8EBAMCB4AwgeEGCisGAQQB1nkCAREEgdIwgc8CAQIKAQACAQEKAQAEICAVnhq_T4BVVJ4USjn40VUJGhz_G87B-lkK5Z_HQSwKBAAwab-FPQgCBgFe0-PPoL-FRVkEVzBVMS8wLQQoY29tLmFuZHJvaWQua2V5c3RvcmUuYW5kcm9pZGtleXN0b3JlZGVtbwIBATEiBCB0z8tQdIj1KRCFkcelBZGfMncy-8HYA1Jq6pgABtLYmDAyoQUxAwIBAqIDAgEDowQCAgEApQUxAwIBBKoDAgEBv4N4AwIBAr-FPgMCAQC_hT8CBQAwHwYDVR0jBBgwFoAUUpobMuBWqs1RD-9fgDcGi_KRIx0wCgYIKoZIzj0EAwIDSAAwRQIhAKvA26dfXR-AfeqTbbbSu4b-9aEVnXCHBcONtajK0mf7AiAEYrFdJKSiPJgxZLXLpz21QNvNkufCz6rIpwWxExqm91kDGDCCAxQwggK6oAMCAQICAQIwCgYIKoZIzj0EAwIwgdwxPTA7BgNVBAMMNEZBS0UgQW5kcm9pZCBLZXlzdG9yZSBTb2Z0d2FyZSBBdHRlc3RhdGlvbiBSb290IEZBS0UxMTAvBgkqhkiG9w0BCQEWImNvbmZvcm1hbmNlLXRvb2xzQGZpZG9hbGxpYW5jZS5vcmcxFjAUBgNVBAoMDUZJRE8gQWxsaWFuY2UxIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMB4XDTE5MDQyNTA1NDkzMloXDTQ2MDkxMDA1NDkzMlowgeQxRTBDBgNVBAMMPEZBS0UgQW5kcm9pZCBLZXlzdG9yZSBTb2Z0d2FyZSBBdHRlc3RhdGlvbiBJbnRlcm1lZGlhdGUgRkFLRTExMC8GCSqGSIb3DQEJARYiY29uZm9ybWFuY2UtdG9vbHNAZmlkb2FsbGlhbmNlLm9yZzEWMBQGA1UECgwNRklETyBBbGxpYW5jZTEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1ZMRIwEAYDVQQHDAlXYWtlZmllbGQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASrUGErYk0Xu8O1GwRJOwVJC4wfi52883my3tygfFKh17YN0yF13Ct-3bwm2wjVX4b2cbaU3DBNpKKKjE4DpvXHo2MwYTAPBgNVHRMBAf8EBTADAQH_MA4GA1UdDwEB_wQEAwIChDAdBgNVHQ4EFgQUo9KqLO8NjPIkAtUctGC8v2pbJBQwHwYDVR0jBBgwFoAUUpobMuBWqs1RD-9fgDcGi_KRIx0wCgYIKoZIzj0EAwIDSAAwRQIhALFvLkAvtHrObTmN8P0-yLIT496P_weSEEbB6vCJWSh9AiBu-UOorCeLcF4WixOG9E5Li2nXe4uM2q6mbKGkll8u-WhhdXRoRGF0YVik9rebzUj0SQWZ5fw2CRoiUTVpd_XyX7k6EGgB2mHpBO5BAAAAKlUOS1SqR0CfmpUat2wTATEAILxm6H8DxwPHCC1tLc-4H8XjfciIZNj3fq3UXMQSKl2rpQECAyYgASFYIL0iFCFvtC90dvMA4n8y8e8VZ7A3ct8eh2RFKryiiKjvIlggLas7lJEVTDHACNxAOqCmMwSDeQTnivfsXX8yQqU2W0E","clientDataJSON":"eyJvcmlnaW4iOiJodHRwczovL2ZpZG9pbnRlcm9wLnNlY3VyaXR5cG9jLmNvbSIsImNoYWxsZW5nZSI6IlM0WnFmVk5wc04wUzJwRXg4TGk3SDVjc3h4LWo4YjNlTlpjbGFsc0pHbHMiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"},"type":"public-key"}

After unpacking the attestationObject, x5c is these two certs (first is the attestation cert, second is an intermediate):

-----BEGIN CERTIFICATE-----
MIIDATCCAqegAwIBAgIBATAKBggqhkjOPQQDAjCBzjFFMEMGA1UEAww8RkFLRSBB
bmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF0dGVzdGF0aW9uIEludGVybWVkaWF0
ZSBGQUtFMTEwLwYJKoZIhvcNAQkBFiJjb25mb3JtYW5jZS10b29sc0BmaWRvYWxs
aWFuY2Uub3JnMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMQwwCgYDVQQLDANDV0cx
CzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMCAX
DTcwMDIwMTAwMDAwMFoYDzIwOTkwMTMxMjM1OTU5WjApMScwJQYDVQQDDB5GQUtF
IEFuZHJvaWQgS2V5c3RvcmUgS2V5IEZBS0UwWTATBgcqhkjOPQIBBggqhkjOPQMB
BwNCAAS9IhQhb7QvdHbzAOJ/MvHvFWewN3LfHodkRSq8ooio7y2rO5SRFUwxwAjc
QDqgpjMEg3kE54r37F1/MkKlNltBo4IBFjCCARIwCwYDVR0PBAQDAgeAMIHhBgor
BgEEAdZ5AgERBIHSMIHPAgECCgEAAgEBCgEABCAgFZ4av0+AVVSeFEo5+NFVCRoc
/xvOwfpZCuWfx0EsCgQAMGm/hT0IAgYBXtPjz6C/hUVZBFcwVTEvMC0EKGNvbS5h
bmRyb2lkLmtleXN0b3JlLmFuZHJvaWRrZXlzdG9yZWRlbW8CAQExIgQgdM/LUHSI
9SkQhZHHpQWRnzJ3MvvB2ANSauqYAAbS2JgwMqEFMQMCAQKiAwIBA6MEAgIBAKUF
MQMCAQSqAwIBAb+DeAMCAQK/hT4DAgEAv4U/AgUAMB8GA1UdIwQYMBaAFFKaGzLg
VqrNUQ/vX4A3BovykSMdMAoGCCqGSM49BAMCA0gAMEUCIQCrwNunX10fgH3qk222
0ruG/vWhFZ1whwXDjbWoytJn+wIgBGKxXSSkojyYMWS1y6c9tUDbzZLnws+qyKcF
sRMapvc=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDFDCCArqgAwIBAgIBAjAKBggqhkjOPQQDAjCB3DE9MDsGA1UEAww0RkFLRSBB
bmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF0dGVzdGF0aW9uIFJvb3QgRkFLRTEx
MC8GCSqGSIb3DQEJARYiY29uZm9ybWFuY2UtdG9vbHNAZmlkb2FsbGlhbmNlLm9y
ZzEWMBQGA1UECgwNRklETyBBbGxpYW5jZTEiMCAGA1UECwwZQXV0aGVudGljYXRv
ciBBdHRlc3RhdGlvbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1ZMRIwEAYDVQQH
DAlXYWtlZmllbGQwHhcNMTkwNDI1MDU0OTMyWhcNNDYwOTEwMDU0OTMyWjCB5DFF
MEMGA1UEAww8RkFLRSBBbmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF0dGVzdGF0
aW9uIEludGVybWVkaWF0ZSBGQUtFMTEwLwYJKoZIhvcNAQkBFiJjb25mb3JtYW5j
ZS10b29sc0BmaWRvYWxsaWFuY2Uub3JnMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNl
MSIwIAYDVQQLDBlBdXRoZW50aWNhdG9yIEF0dGVzdGF0aW9uMQswCQYDVQQGEwJV
UzELMAkGA1UECAwCTVkxEjAQBgNVBAcMCVdha2VmaWVsZDBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABKtQYStiTRe7w7UbBEk7BUkLjB+LnbzzebLe3KB8UqHXtg3T
IXXcK37dvCbbCNVfhvZxtpTcME2kooqMTgOm9cejYzBhMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgKEMB0GA1UdDgQWBBSj0qos7w2M8iQC1Ry0YLy/alsk
FDAfBgNVHSMEGDAWgBRSmhsy4FaqzVEP71+ANwaL8pEjHTAKBggqhkjOPQQDAgNI
ADBFAiEAsW8uQC+0es5tOY3w/T7IshPj3o//B5IQRsHq8IlZKH0CIG75Q6isJ4tw
XhaLE4b0TkuLadd7i4zarqZsoaSWXy75
-----END CERTIFICATE-----

The AAGUID is: 550E4B54-AA47-409F-9A95-1AB76C130131

This correctly correlates to the metadata document: Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Android Key Attestation.json

The trusted root CA from the metadata document is:
-----BEGIN CERTIFICATE-----
MIIDFTCCArygAwIBAgIJAPYG0nMp5fspMAoGCCqGSM49BAMCMIHcMT0wOwYDVQQD
DDRGQUtFIEFuZHJvaWQgS2V5c3RvcmUgU29mdHdhcmUgQXR0ZXN0YXRpb24gUm9v
dCBGQUtFMTEwLwYJKoZIhvcNAQkBFiJjb25mb3JtYW5jZS10b29sc0BmaWRvYWxs
aWFuY2Uub3JnMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMSIwIAYDVQQLDBlBdXRo
ZW50aWNhdG9yIEF0dGVzdGF0aW9uMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTVkx
EjAQBgNVBAcMCVdha2VmaWVsZDAgFw0xOTA0MjUwNTQ5MzJaGA8yMDc0MDEyNjA1
NDkzMlowgdwxPTA7BgNVBAMMNEZBS0UgQW5kcm9pZCBLZXlzdG9yZSBTb2Z0d2Fy
ZSBBdHRlc3RhdGlvbiBSb290IEZBS0UxMTAvBgkqhkiG9w0BCQEWImNvbmZvcm1h
bmNlLXRvb2xzQGZpZG9hbGxpYW5jZS5vcmcxFjAUBgNVBAoMDUZJRE8gQWxsaWFu
Y2UxIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xCzAJBgNVBAYT
AlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEaH+BmKuo1XRtjS3UJVLrjh0bNl/lLhU7VX89N8+kuI8r
nZCfXVD5k3qpOFSY6oTtrcZ1aQRSyR4sZ8EC6Hoi7aNjMGEwDwYDVR0TAQH/BAUw
AwEB/zAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0OBBYEFFKaGzLgVqrNUQ/vX4A3Bovy
kSMdMB8GA1UdIwQYMBaAFFKaGzLgVqrNUQ/vX4A3BovykSMdMAoGCCqGSM49BAMC
A0cAMEQCIAfWMAOOjxO6noErB+wtRBmrDruNIApw70G7kBhliXLkAiBM8sYUVClP
sJkCUHI5Wix3ybY31L5J51VS+f1gACNn+Q==
-----END CERTIFICATE-----

In my analysis of this cert chain, the attestation cert (I call it x5c.0.pem) IS NOT signed by the provided intermediate (x5c.1.pem). The provided intermediate IS signed by the trusted root in the metadata document (android-key-ca.pem), so the problem appears to be that the wrong attestation cert is provided.

This shows the intermediate is signed by the CA:

$ openssl verify -CAfile android-key-ca.pem x5c.1.pem
x5c.1.pem: OK

Two different ways to try verify the full chain - both produce the same error, indicating the attestation cert is not signed by the intermediate.

$ openssl verify -CAfile android-key-ca.pem -untrusted x5c.1.pem x5c.0.pem
x5c.0.pem: CN = FAKE Android Keystore Key FAKE
error 20 at 0 depth lookup:unable to get local issuer certificate

$ openssl verify -CAfile <(cat x5c.1.pem android-key-ca.pem) x5c.0.pem
x5c.0.pem: CN = FAKE Android Keystore Key FAKE
error 20 at 0 depth lookup:unable to get local issuer certificate

**Comment by herrjemand** [comment]
Resolved now.

**Comment by todowenil** [comment]
Hi @sbweeden,
Is your problem solved?
When i test v1.1.5 in windows 10, still got this error.

**Comment by sbweeden** [comment]
I still have the problem also

**Comment by kishorechandran41** [comment]
@herrjemand this is been reopened as https://github.com/fido-alliance/conformance-tools-issues/issues/499
