### ISSUE TITLE
CRL resolution issue for Android-SafetyNet server test case

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-tools-issues#490]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
Mac

## Issue description

This test case:

Server-ServerAuthenticatorAttestationResponse-Resp-B Test server processing "android-safetynet" attestation
P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-safetynet" attestation, and check that the server succeeds

relies on metadata file: Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json

This contains a couple of rootCAs that have a CRL distribution point of: https://fidoalliance.co.nz/safetynetpki/crl/root-s1.crl

Attempts to retrieve this URL result in:

$ curl -k https://fidoalliance.co.nz/safetynetpki/crl/root-s1.crl

{"error":"404 NOT FOUND","routes":[{"location":"/register","description":"Registeres facetID and returns authToken","type":"POST: application/x-www-form-urlencoded;charset=UTF-8","form":{"facetID":"FacetID of the client"},"response":"{\"authToken\": \"...auth token...\"}"},{"location":"/get","description":"Returns new appID with testCase set to good facet","headers":{"authorization":"AuthToken from /register"},"type":"POST application/x-www-form-urlencoded;charset=UTF-8","form":{"testName":"Optional. If set to veryLongAppID returns very long appID"},"response":"{\"appID\": \"https://example.com/execute/abaush352k2h...\"}"},{"location":"/set","description":"Sets a test to be extended to a given appID","type":"POST: application/x-www-form-urlencoded;charset=UTF-8","form":{"appID":"appID ¯\\_(ツ)_/¯","testName":"testName ¯\\_(ツ)_/¯"},"response":"{\"status\": \"SUCCEESS\"}","additional":{"tests":["goodFacet","goodRedirect","missingCurrentFacet","missingTrustedFacets","badTrustedFacets","emptyTrustedFacets","missingVersion","badVersion","badVersionMajor","badVersionMinor","missingIDs","badIDS","emptyIDs","veryLongAppID","httpAppID","rogueSubdomain","httpListedFacet","leastSpecificeTLD","missingRedirectHeader","falseRedirectHeader","nullRedirectHeader","badRedirect","default"]}},{"location":"/execute","description":"Returns test case data","type":"GET","response":"TrustedFacetList"}]}

Our PKIX trust path validation does not like this. Can you please provide a valid CRL document at the distribution point, otherwise the test case doesn't (and shouldn't) pass successfully.

**Comment by sbweeden** [comment]
This appears to be a duplicate of #476

**Comment by herrjemand** [comment]
Dublicate

**Comment by sbweeden** [comment]
This issue still appears to be prevelant. Tested with v1.1.5, but the issue is with the CRL site, not the test tool or its metadata.
