### ISSUE TITLE
fido tool version 1.1.4 has test failures

### ISSUE THREAD

**Issue by xjrosasx** [fido-alliance/conformance-tools-issues#491]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
MacOS; Mojave

## Issue description
Several tests fail when running the Server Test Set:
MakeCredential Response
> **Server-ServerAuthenticatorAttestationResponse-Resp-9**
> P-1 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation for SHA-256, and check that server succeeds
> P-2 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation for SHA-1, and check that server succeeds
> P-3 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation pubArea.nameAlg is not matching algorithm used for generate attested.name, and check that server succeeds

and

> **Server-ServerAuthenticatorAttestationResponse-Resp-B**
> P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-safetynet" attestation, and check that server succeeds

The steps I have taken to troubleshoot the issue are:

1. imported certs from the attached screenshot
![Screen Shot 2019-08-01 at 2 03 08 PM](https://user-images.githubusercontent.com/5342760/62327340-34ad9b00-b465-11e9-8a4c-1c06580f1969.png)
 to my java keystore via keytool
2. imported all metadata downloaded from tool into auth server
3. tested older tool build: v0.10.150
4. imported metadata downloaded from older tool build: v0.10.150

The interesting thing is that the tests pass when running the older tool build: v0.10.150.

**Comment by herrjemand** [comment]
Fixed now!
