### ISSUE TITLE
Release v1.1.5 folder is empty, no binaries

### ISSUE THREAD

**Issue by grzuy** [fido-alliance/conformance-tools-issues#493]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v1.1.5

## What is the OS and the version are you running?

N/A

## Issue description

Visiting https://conformance-test.fidoalliance.org/Desktop%20UAF%20FIDO2%20U2F/v1.1.5/ gives me an empty folder, no binaries.

**Comment by herrjemand** [comment]
@grzuy fixed

**Comment by grzuy** [comment]
Thank you!
