### ISSUE TITLE
TypeError: Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by kishorechandran41** [fido-alliance/conformance-tools-issues#494]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
FIDO Conformance Tools v1.1.5(FIDO2 )

## What is the OS and the version are you running?
Windows 10

## Issue description
On clicking 'RUN' getting a pop up saying **Error while executing tests. Error message: TypeError: Cannot read property 'crypto' of undefined**
Attached Screenshot, 
![Fido2_Conformance_Tool_v1 1 5](https://user-images.githubusercontent.com/17059033/62457297-24b0f680-b798-11e9-95af-cbe5fda5437f.JPG)

**Comment by herrjemand** [comment]
Rebuild the build.

**Comment by kishorechandran41** [comment]
@herrjemand the new build is also failing with same error.
