### ISSUE TITLE
P-3 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation pubArea.nameAlg is not matching algorithm used for generate attested.name, and check that server succeeds

### ISSUE THREAD

**Issue by Spomky** [fido-alliance/conformance-tools-issues#496]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.1.4

## What is the OS and the version are you running?

Windows 10

## Issue description

This test is failed for my implementation, but I am not sure how to fix it.
As @herrjemand wrote in one of his blog post (thank you for these articles by the way), the attested name is the concatenation of the hashing algorithm identifier and the hash of the pubArea.

> 9.  Hash pubArea to create pubAreaHash using the nameAlg in attested
> 10. Concatenate attested.nameAlg and pubAreaHash to create attestedName.
> 11. Check that certInfo.attested.name is equals to attestedName.

This is exactly what is done in [these lines](https://github.com/web-auth/webauthn-framework/blob/v2.1/src/webauthn/src/AttestationStatement/TPMAttestationStatementSupport.php#L60-L62).

With the following options and response, the test should succeed, but it does not.
It looks like the hash alg is sha256 instead of sha1 as indicated by `nameAlg`

Is there anything I missed?

<details>{"status":"ok","errorMessage":"","rp":{"name":"Webauthn Demo","id":"webauthn.spomky-labs.com"},"pubKeyCredParams":[{"type":"public-key","alg":-8},{"type":"public-key","alg":-7},{"type":"public-key","alg":-43},{"type":"public-key","alg":-35},{"type":"public-key","alg":-36},{"type":"public-key","alg":-257},{"type":"public-key","alg":-258},{"type":"public-key","alg":-259},{"type":"public-key","alg":-37},{"type":"public-key","alg":-38},{"type":"public-key","alg":-39}],"challenge":"WTDxpo5kkWJjtJ3ohDhpTWEx39ivkYt_c4xwHJgefUc","attestation":"direct","user":{"name":"BtpYiT5YeM0g0AvHIcqd","id":"MGQ2OGFkZDQtNjZiYy00NzY1LWJlOTctMWIzNmIyMmJjMjU1","displayName":"Freddie Montijo"},"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"timeout":60000}</details>

<details>{"id":"Y449VyCutqNSfYqIanYCnG_ERdnZ_bgfIPP8hT5i0iM","rawId":"Y449VyCutqNSfYqIanYCnG_ERdnZ_bgfIPP8hT5i0iM","response":{"attestationObject":"o2NmbXRjdHBtZ2F0dFN0bXSmY2FsZzkBAGNzaWdZAQBoKU879k-i-bG6_hrHxPktZ2r0lDoOcA1RmExoSFlJ2Z8NasTKES620i-q79eo5lGasEFM4FN-1dZypsbiZdFWYJ5hpbNRjuG8qFO7CReELVuGH8kXHifspf1rCQETTamx2kU4uK0BQoojVv57wK5t0hr1PXfKjIO7rCEJH1zKOYywmkb2_saJ1odIb1fbwjoGVrw41JCuOHyJn4snWd-khnGZli25LC9GeEWGKs0DdFVX0XvI6iYlpLg6IVcG8g5KRQCflSvzNFiOOn346Fp9PbnmTilxwGMJ22b8bfuHhdkJJbUNerZObDleRWog6cOLVoTaHD4Bq4x6rDJI-76pY3ZlcmMyLjBjeDVjglkEhzCCBIMwggNroAMCAQICDwRfumLFa6Y4qANCPY4RZjANBgkqhkiG9w0BAQsFADBBMT8wPQYDVQQDEzZOQ1UtTlRDLUtFWUlELTAzN0FGNzM4MTEwRjk2MDU0RENERjA4MkVGRkEwMzFGOUJGODEwQUYwHhcNMTgwMjAxMDAwMDAwWhcNMjUwMTMxMjM1OTU5WjAAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwIq0W2FetalcMPNXbagB9PlG5uMpK5s1AdGA4r-LivPMV0tpQrlBITMluhVwPIL0QDn2FNc7uudslujJRR3p-afkaeptk97Mpn7r6TFiHm-H4gna7P-wAAML58kxjJOApjVIJabyhS6w6oDkmHcU8pdz2h39ZRUD0mBug4OwJ3xS8cj8D1Dx6JTNqh5w1REpr9ZQDJxgOBAWjrf1fiXb0XuO2XO3taLI_dZGxZsovUXC94QeQIi0tADas89v3L9lR1ZcRuNj5s2nlnXrKtfAZdtFTEicUVmH9xgD_YiuxoE9ZGrDa0ZAuKmaMQQWw6ChIXFlqohFP1pZnxRwokxfnwIDAQABo4IBtzCCAbMwDgYDVR0PAQH_BAQDAgeAMAwGA1UdEwEB_wQCMAAwewYDVR0gAQH_BHEwbzBtBgkrBgEEAYI3FR8wYDBeBggrBgEFBQcCAjBSHlAARgBBAEsARQAgAEYASQBEAE8AIABUAEMAUABBACAAVAByAHUAcwB0AGUAZAAgAFAAbABhAHQAZgBvAHIAbQAgAEkAZABlAG4AdABpAHQAeTAQBgNVHSUECTAHBgVngQUIAzBKBgNVHREBAf8EQDA-pDwwOjE4MA4GBWeBBQIDDAVpZDoxMzAQBgVngQUCAgwHTlBDVDZ4eDAUBgVngQUCAQwLaWQ6RkZGRkYxRDAwHwYDVR0jBBgwFoAUUX8iyOZTpXzVTN0wWH4w_2c2jF0wHQYDVR0OBBYEFDVEHgiRA6Zs7ZvY5mep4iuPE7zgMHgGCCsGAQUFBwEBBGwwajBoBggrBgEFBQcwAoZcaHR0cHM6Ly9maWRvYWxsaWFuY2UuY28ubnovdHBtcGtpL05DVS1OVEMtS0VZSUQtMDM3QUY3MzgxMTBGOTYwNTREQ0RGMDgyRUZGQTAzMUY5QkY4MTBBRi5jcnQwDQYJKoZIhvcNAQELBQADggEBAFznNexHQnnvMe8yzXICp7o6dJV21_ULuDMK2OQbqPOSKOaBhbcl0H9kHGip3dw70nLvhnDZRqV9aTbPUXa9T3AcVHmlznYCmBq7zl977AxfG55jsVnjO8yalexQu9f_CKuNpXDhgyvlBPFl5MFudAalwl-u2oNVTFppdDLgUe4t1yyzmTXjjYPD5KbJo-k4I_gDblnb1M-pr-kPvHzAnstDHIVeqsVXdbFTwQ89uagoSKf3XGd21S6ljGR8b_j7JKBRJNlXpM9cffW-8LT5jz18feIyZS-xsXFoHYGra7RX0EPdmHDCW5g_KZ-Sh9vsw3SJNjKZsPQN77Yhpct-Mn9ZBgUwggYBMIID6aADAgECAg8Ea4iQoZL_Z7CuCmNqDHMwDQYJKoZIhvcNAQELBQAwgb8xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMQwwCgYDVQQLDANDV0cxNjA0BgNVBAMMLUZJRE8gRmFrZSBUUE0gUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxODExMC8GCSqGSIb3DQEJARYiY29uZm9ybWFuY2UtdG9vbHNAZmlkb2FsbGlhbmNlLm9yZzAeFw0xNzAyMDEwMDAwMDBaFw0zNTAxMzEyMzU5NTlaMEExPzA9BgNVBAMTNk5DVS1OVEMtS0VZSUQtMDM3QUY3MzgxMTBGOTYwNTREQ0RGMDgyRUZGQTAzMUY5QkY4MTBBRjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANc-c30RpQd-_LCoiLJbXz3t_vqciOIovwjez79_DtVgi8G9Ph-tPL-lC0ueFGBMSPcKd_RDdSFe2QCYQd9e0DtiFxra-uWGa0olI1hHI7bK2GzNAZSTKEbwgqpf8vXMQ-7SPajg6PfxSOLH_Nj2yd6tkNkUSdlGtWfY8XGB3n-q--nt3UHdUQWEtgUoTe5abBXsG7MQSuTNoad3v6vk-tLd0W44ivM6pbFqFUHchx8mGLApCpjlVXrfROaCoc9E91hG9B-WNvekJ0dM6kJ658Hy7yscQ6JdqIEolYojCtWaWNmwcfv--OE1Ax_4Ub24gl3hpB9EOcBCzpb4UFmLYUECAwEAAaOCAXUwggFxMAsGA1UdDwQEAwIBhjAWBgNVHSAEDzANMAsGCSsGAQQBgjcVHzAbBgNVHSUEFDASBgkrBgEEAYI3FSQGBWeBBQgDMBIGA1UdEwEB_wQIMAYBAf8CAQAwHQYDVR0OBBYEFFF_IsjmU6V81UzdMFh-MP9nNoxdMB8GA1UdIwQYMBaAFFx_Ni2QrVq8uo512t46oO3BTgKLMGgGA1UdHwRhMF8wXaBboFmGV2h0dHBzOi8vZmlkb2FsbGlhbmNlLmNvLm56L3RwbXBraS9jcmwvRklETyBGYWtlIFRQTSBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDE4LmNybDBvBggrBgEFBQcBAQRjMGEwXwYIKwYBBQUHMAKGU2h0dHBzOi8vZmlkb2FsbGlhbmNlLmNvLm56L3RwbXBraS9GSURPIEZha2UgVFBNIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTguY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCN1i8OPMdt_K9yL8UI_SUx7NkEpDRQ-FWJ6-JNQIfpV8aTAPmDLiSqeSQEheq_F0s4RuiGQLkS3xRFFiIF9y5-ouiqyWMKJLVMNdhkMr1YJmBzkrcGYLEVl80WhtxoK_8QUpQpzqjpXjyJdVAi5nnbOvQ4gUuSDXD1BUynY3xAxn9Sn73QhKlgZSSxV65DsP3_VG4nZqQ_EnpiSP_QVIas6MR4F96N3NReQ2Qc9RAZ05xArnbZW32xCApSeAgUoWJiSYTOUdPW8whl05B0ni_PCgOn3QtVlMC3Zm0d7P8WXihpGtT24_h6q0ewBJKeXejcXW4gohHNtPfBCAKypTw_rsJrzsMk1SnzA5dJEyoTcz4_Yh_tRXjg9-pDuECqZrnb_Z3hDB0ctqPvSVwONhWkyrWgejExBfJ3i2oGlzihqcZ2VsTvsFostfRB2dRwm1JWoy63_39uZW48pkfI3JRXgNPHJWiH16Zz8Jb6jx2brOmyifTmMyhfgDkuwSYG5Wp2-hsORKTjRlzkEooi9n57GEGi8OIhe6a4l8ZeIee4C7DdTT7WZeIL2Muxg0bEDz63NiVdQBp6gJkbTzzgLfRDVPVwXfzxCwdp-uf2dw0QjTAQ8kecVW_AZ5Y5BWJHdWjWUMA9xFarDti1dAznGPZscrMNHEhhpmLmhxBL_Nk0kGdwdWJBcmVhWQE2AAEABAAGBHIAIJ3_y_NsODrmmfuYaNxty4nXFTiEvigDkiwSQVi_rSKuABAAEAgAAAAAAAEArXFsoAQGAUXIBenPIFztxECVr8ldoCqlJkeN0BSG5ekSsE8DY0kDGlf2UizeC5AXH0oTCw_0saW53XBe6ewghp5lzxpAq4a5lyJv40Yis1YkX8YvtMf_Ic_kVsrqOK2iKm4NGtzK-t4iDj17Hh3sAOMg8RxuaJV-QU7PoVSbduzB0amktaqc5FNgZjnc_EbLBR7YvGGFBP3aGNomZurYFA8vVMDhw0qmOrA4iX2XGzKLd_YywouJQ_c9gkCP9N-Xo3S9oZlAW1pYvRDTuMdQ6DBikj802fjdcuIZpT4N6fyYFGeS8NP94-0l3j2Vpv0nZWku1kca7H6th29s49eo9WhjZXJ0SW5mb1it_1RDR4AXACIACxHmjtRNtTcuFCluL4Ssx4OYdRiBkh4w_CKgb4tzx5RTACDZLMfHrTF_lwAnrhF3IFiMvEqwtMdrnHnKZY7iBpANZgAAAAFHcBdIVWl7S8aFYKUBc375jTRWVfsAIgALezMaOCNoGuG34tNxgR4WQ5A5o4F-BKpPvxSi_wiXBykAIgAL4WlD31qwtzON1tYuOIv7vPS2CQQqxQLYf9KGJ9ZZPg1oYXV0aERhdGFZAWeWBOqCgk6YpK2hS0Ri0Nc6jsRpEw2pGxkwdFkin3SjWUEAAACUp9bZOooNEeialKbPcQcvcwAgY449VyCutqNSfYqIanYCnG_ERdnZ_bgfIPP8hT5i0iOkAQMDOQEAIFkBAK1xbKAEBgFFyAXpzyBc7cRAla_JXaAqpSZHjdAUhuXpErBPA2NJAxpX9lIs3guQFx9KEwsP9LGlud1wXunsIIaeZc8aQKuGuZcib-NGIrNWJF_GL7TH_yHP5FbK6jitoipuDRrcyvreIg49ex4d7ADjIPEcbmiVfkFOz6FUm3bswdGppLWqnORTYGY53PxGywUe2LxhhQT92hjaJmbq2BQPL1TA4cNKpjqwOIl9lxsyi3f2MsKLiUP3PYJAj_Tfl6N0vaGZQFtaWL0Q07jHUOgwYpI_NNn43XLiGaU-Den8mBRnkvDT_ePtJd49lab9J2VpLtZHGux-rYdvbOPXqPUhQwEAAQ","clientDataJSON":"eyJvcmlnaW4iOiJodHRwczovL3dlYmF1dGhuLnNwb21reS1sYWJzLmNvbSIsImNoYWxsZW5nZSI6IldURHhwbzVra1dKanRKM29oRGhwVFdFeDM5aXZrWXRfYzR4d0hKZ2VmVWMiLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0"},"type":"public-key"}</details>

**Comment by grzuy** [comment]
For what is worth, I think there's a discussion about this in https://github.com/fido-alliance/conformance-tools-issues/issues/396.

**Comment by Spomky** [comment]
Thank you @grzuy. I missed that one.

**Comment by Spomky** [comment]
OK I fixed the test with the details provided in the conversation in #396.
Only 1 test to fix before full compliance 👍
