### ISSUE TITLE
Android Keystore certificate path still invalid

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-tools-issues#499]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.1.5

## What is the OS and the version are you running?
Mac osx

## Issue description

This is essentially a re-open of #489 as the android key attestation path still does not validate. The attestation certificate (x5c[0]) has changed in v1.1.5 to:

-----BEGIN CERTIFICATE-----
MIIDATCCAqegAwIBAgIBATAKBggqhkjOPQQDAjCBzjFFMEMGA1UEAww8RkFLRSBB
bmRyb2lkIEtleXN0b3JlIFNvZnR3YXJlIEF0dGVzdGF0aW9uIEludGVybWVkaWF0
ZSBGQUtFMTEwLwYJKoZIhvcNAQkBFiJjb25mb3JtYW5jZS10b29sc0BmaWRvYWxs
aWFuY2Uub3JnMRYwFAYDVQQKDA1GSURPIEFsbGlhbmNlMQwwCgYDVQQLDANDV0cx
CzAJBgNVBAYTAlVTMQswCQYDVQQIDAJNWTESMBAGA1UEBwwJV2FrZWZpZWxkMCAX
DTcwMDIwMTAwMDAwMFoYDzIwOTkwMTMxMjM1OTU5WjApMScwJQYDVQQDDB5GQUtF
IEFuZHJvaWQgS2V5c3RvcmUgS2V5IEZBS0UwWTATBgcqhkjOPQIBBggqhkjOPQMB
BwNCAAR9Am+wV41e9ZVPS6d1ctcgOhjy4/YT7itBOH2paeHrfYZvZgTL/kiitq73
8NsnCoJDbqLKN15cFPsaEWMDQjido4IBFjCCARIwCwYDVR0PBAQDAgeAMIHhBgor
BgEEAdZ5AgERBIHSMIHPAgECCgEAAgEBCgEABCATWbuBocrSlVEl9kEgqWXKwqLK
0bK+GoEGT8NBitaK7gQAMGm/hT0IAgYBXtPjz6C/hUVZBFcwVTEvMC0EKGNvbS5h
bmRyb2lkLmtleXN0b3JlLmFuZHJvaWRrZXlzdG9yZWRlbW8CAQExIgQgdM/LUHSI
9SkQhZHHpQWRnzJ3MvvB2ANSauqYAAbS2JgwMqEFMQMCAQKiAwIBA6MEAgIBAKUF
MQMCAQSqAwIBAb+DeAMCAQK/hT4DAgEAv4U/AgUAMB8GA1UdIwQYMBaAFKPSqizv
DYzyJALVHLRgvL9qWyQUMAoGCCqGSM49BAMCA0gAMEUCID6GVXQ+HXtAtTjqtATq
xfZDBDea8cU7LW89nrU4+MCNAiEAqq0pCzl9/6URwAebNN7HfvbyWtapCWi5eQbn
hsy+Quc=
-----END CERTIFICATE-----

however I still cannot get it to verify against xc5[1] of the chain which remains as previously reported in #489

**Comment by kishorechandran41** [comment]
I am also facing the issues as addressed in https://github.com/fido-alliance/conformance-tools-issues/issues/486

**Comment by kishorechandran41** [comment]
https://github.com/fido-alliance/conformance-tools-issues/issues/489 address on the same but was closed

**Comment by herrjemand** [comment]
Found missmatch in between Subject and Issuer. Fixed now

**Comment by Spomky** [comment]
Thank you @herrjemand.
Will you address the changes in a new release of the conformance tool (1.1.6) or will the new metadata objects be available through the current version 1.1.5?

**Comment by kishorechandran41** [comment]
Worked fine for me using conformance tool (1.1.6) @herrjemand thank you.
