### ISSUE TITLE
CRL distribution point returns 404 for android-safetynet

### ISSUE THREAD

**Issue by sbweeden** [fido-alliance/conformance-tools-issues#500]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.1.5

## What is the OS and the version are you running?
MacOS

## Issue description
This is a re-open of #490 which is still broken.

The x5c[0] contains a CRL distribution point of: https://fidoalliance.co.nz/safetynetpki/crl/attest.android.com.crl
That returns a 404.

The x5c[1] contains a CRL distribution point of:
https://fidoalliance.co.nz/safetynetpki/crl/FIDO%20Fake%20Root%20Certificate%20Authority%202018.crl
That returns a 404.

The rootCA contains a CRL distribution point of:
https://fidoalliance.co.nz/safetynetpki/crl/root-s1.crl
That returns a 404.

It seems nothing has been done to address this defect as originally reported in #490 - it was just closed???

**Comment by kishorechandran41** [comment]
I am also facing the issues as addressed in https://github.com/fido-alliance/conformance-tools-issues/issues/486

**Comment by kishorechandran41** [comment]
https://github.com/fido-alliance/conformance-tools-issues/issues/490 was also address on the same but was closed.

**Comment by herrjemand** [comment]
Dublicate of #476
