### ISSUE TITLE
U2F Check that metadata that AttestationKeyIdentifiers contain SKIDs from the batch

### ISSUE THREAD

**Issue by herrjemand** [fido-alliance/conformance-tools-issues#501]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/U2F/FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?

Server/Client/ASM+Authr

**Comment by bdewater** [comment]
I think I just ran into the same issue - the metadata generated by the tool does not have any entries/statements that with the `attestationCertificateKeyIdentifiers` array containing `564df7c0f8c655b6a11f6c4d19f3bf41e2fd0179`, so metadata lookup for the root certificate fails.

**Comment by herrjemand** [comment]
@bdewater This is only for U2F. For FIDO you lookup by AAGUID. For UAF by AAID
