### ISSUE TITLE
FIDO2 BLE Test Error

### ISSUE THREAD

**Issue by rui12356** [fido-alliance/conformance-tools-issues#503]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
v1.1.5

## What is the OS and the version are you running?
Win10 1903

## Issue description
When running the tool, it prompts "error connecting to BLE API", and could not connect to any BLE authenticators.

**Comment by herrjemand** [comment]
@rui12356 Fixed in the new build.

**Comment by Chellapandi** [comment]
The same issue occurred when I update macOS Catalina. Please look into it.
