### ISSUE TITLE
Server Conformance Test Tool Should Validate Facets Version

### ISSUE THREAD

**Issue by talaieru** [fido-alliance/conformance-tools-issues#508]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

1.1.6

## What is the OS and the version are you running?

MacOS 10.14.6

## Issue description

The conformance test tool does not do a check on the version published in the facets.
This generated trouble in the Seoul interoperability testing event: all the FIDO UAF 1.1 servers where using `1.1` as version for the supported applications. The server had to be changed because the client used by one of the participants was expecting `1.0`.

Note: I think that the issue https://github.com/fido-alliance/conformance-tools-issues/issues/482 should be reopened and fixed: the version to be specified in the facet information for clients implementing FIDO UAF 1.1 should be 1.1, and for those implementing 1.0, it should be 1.0; that is, as far as i see it, the goal of having an array of elements (one per version).

**Comment by herrjemand** [comment]
TFC must always be 1.0

**Comment by talaieru** [comment]
Any particular reason to close this bug?  Has any additional test been added to the server conformance test tool?
