### ISSUE TITLE
Improve conformance tools to make debugging failed tests easier.

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#509]
## What protocol and version of the protocol are you testing?
ALL: UAF/U2F/FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?
ALL: Server/Client/ASM+Authr

## What is the version of the tool are you using?
Latest

## What is the OS and the version are you running?
ALL

## Issue description

# Improve debugging of failed test cases
This is a general suggestion for improving the ability for developers to debug conformance test cases that are failing. It applies to the Server and Mobile conformance tools for all implementation classes and all protocols/versions.

When the conformance tests are run, there are dozens of tests that are run at one time. In many cases, one conformance test case results in multiple calls made to the implementation under test. It is often challenging to determine which calls to the implementation under test are related to the conformance test cases that are failing. 

It would be helpful if the conformance test case description related to the call to the implementation under test were passed as a part of the request. The protocols provide a way to pass application-specific data as a part of the request. These application-specific mechanisms could be used to include the test case description. Here are some suggestions for various protocol and implementation classes.

## UAF Server
When the conformance tool sends a GetUAFRequest to the UAF Server, the test case description can be passed in the context object. 

## UAF Client/ASM/Authenticator
The best way to pass the test case description down to the Authenticator is to use the UAF Extension. An extension with an id of "org.fidoalliance.conformance.test-description" with data set to the description and fail_if_unknown set to false.

## FIDO2 Server & Authenticator
TBD

# Test Case Descriptions
In the case of the conformance tools for Android and iOS, the description of the test case that is displayed is truncated on the first line and at the right side. Even on a high-resolution tablet, most of the test case's description is not visible. The complete description can be seen in the logs, but when you have a test case failing, it would be easier to view it in the conformance tool. Keeping the test case description to one line is fine to keep scrolling through the results easier. It should be possible for the developer to expand a test case description so that the complete description can be viewed.

**Comment by herrjemand** [comment]
Dublicate of #156
