### ISSUE TITLE
UAF 1.1 iOS X-Callback-URL Transport response URL format

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#510]
## What protocol and version of the protocol are you testing?
UAF/v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
iOS 12

## Issue description

The FIDO Conformance tool incorrectly expects the X-Callback-URL Transport response URL to delimit the query string (a.k.a "x-callback and action parameters") using an ampersand (&) instead of the proper question mark (?).

There was even a post on the fido-dev group where someone was incorrectly told to use a & instead of a ? to delimit the query string.
https://groups.google.com/a/fidoalliance.org/d/msg/fido-dev/s4AVTKTWqkg/nRmv9As-CAAJ

Here are the relevant UAF Specifications that say that the query string is delimited using the question mark (?).

https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-client-api-transport-v1.1-id-20170202.html#x-callback-url-transport

**7.1.1 X-Callback-URL Transport**

Conversely, when the FIDO UAF Client responds to the request, it sends the following URL back in standard x-callback-url format:

**EXAMPLE 10**
```
[RelyingPartyURL]://x-callback-url/
      [UAFxResponseType]?
      state=[STATE]&
      json=[Base64EncodedJWE]
```

Here are the x-callback-url specifications that are referenced by the UAF specs.
http://x-callback-url.com/specifications/

**URL Structure**
```
[scheme]://[host]/[action]?[x-callback parameters]&[action parameters]
```

**RFC 1738 - Uniform Resource Locators (URL)**
URLs have been using the ? to delimit the query string from the path since 1994.
https://tools.ietf.org/html/rfc1738#section-3.3

...  <searchpart> is a query string.
```
An HTTP URL takes the form:
      http://<host>:<port>/<path>?<searchpart>
```

https://en.wikipedia.org/wiki/URL#Syntax

**Comment by herrjemand** [comment]
This is legacy matter, so wontfix

**Comment by mirkop** [comment]
Not fixing this in the conformance tool leaves a discrepancy between the UAF Specifications and the UAF Conformance Tool. Anyone developing to the FIDO UAF Application API and Transport Binding Specification will run into problems trying to get their UAF Client to work with the Conformance Tool. There is no official documentation indicating that this discrepancy exists.
