### ISSUE TITLE
UAF 1.1 setting appID to facetID in response message.

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#511]
## What protocol and version of the protocol are you testing?
UAF/v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
Android & iOS

## Issue description
The conformance tool fails the registration and authentication test cases shown below when the client sets the appID to the facetID when the request's appID was empty, per the specifications.

<img width="855" alt="Screen Shot 2019-09-12 at 2 57 35 PM" src="https://user-images.githubusercontent.com/1010379/64812929-355e4480-d56e-11e9-981e-0c3f00e3f307.png">

<img width="837" alt="Screen Shot 2019-09-12 at 3 48 27 PM" src="https://user-images.githubusercontent.com/1010379/64816349-832a7b00-d575-11e9-9345-9739e71c5d64.png">

Below are the specifications that state that appID to must be set to the facetID.

**FIDO UAF Protocol Specification**

https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#registration-response-generation-rules-for-fido-uaf-client
**3.4.6.4 Registration Response Generation Rules for FIDO UAF Client**
2. Copy RegistrationRequest.header into RegistrationResponse.header

> When the appID provided in the request was empty, the FIDO Client must set the appID in this header to the facetID.

https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-uaf-protocol-v1.1-id-20170202.html#authentication-response-generation-rules-for-fido-uaf-client
**3.5.7.4 Authentication Response Generation Rules for FIDO UAF Client**
2. Copy AuthenticationRequest.header into AuthenticationResponse.header

> When the appID provided in the request was empty, the FIDO Client must set the appID in this header to the facetID.

**Comment by herrjemand** [comment]
Damn @mirkop! Excellent issues!

**Comment by herrjemand** [comment]
@mirkop If AppID is empty, then you set FacetID in FCParams not the deader. The header must always be the same
