### ISSUE TITLE
UAF 1.1 Conformance tool sets member values to null in ChannelBinding object.

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#512]
## What protocol and version of the protocol are you testing?
UAF/v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
Android and iOS

## Issue description

When the FIDO Conformance Tool runs conformance and interop tests, it passes a TLS ```ChannelBinding``` JSON dictionary with its member values set to ```null```.  

From Conformance tool Android logcat message:
```
D/CORDOVA-UAF-CLIENT: uafOperation: channel bindings: {"serverEndPoint":null,"tlsServerCertificate":null,"tlsUnique":null,"cid_pubkey":null}
```

All of the UAF specifications that have dictionary definitions state the following...

> WebIDL dictionary members **MUST NOT** have a value of null.

The channel binding object is required but none of the dictionary members are required. The conformance tool should be passing in an empty ```ChannelBinding``` JSON object. Like this ```{}```.

The conformance tool should also test that the UAF Client returns a PROTOCOL_ERROR 0x06 if the ChannelBinding member values are set to null.

**Comment by herrjemand** [comment]
This is JAVA translating undefined to NULL
