### ISSUE TITLE
UAF 1.1 Verify that the client is using the correct FacetID

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#513]
## What protocol and version of the protocol are you testing?
UAF/v1.1

## What is your implementation class?
Client

## What is the version of the tool are you using?
1.1.4

## What is the OS and the version are you running?
Android & iOS

## Issue description

The conformance tool should include a test to ensure that the UAF Client is getting the correct facetID. This can be accomplished by checking that the AppID is set to the FacetID in the reg/auth response messages when the AppID is not set in the reg/auth request message. (See issue #511) It should also check the FinalChallengeParams.facetID for the correct FacetID there.

Android Conformance Tool FacetID:
```android:apk-key-hash:hoG2zCMzhpGCNnLFceBuVpPfDqM```

iOS Conformance Tool FacetID:
```ios:bundle-id:org.fidoalliance.mobile.conformancetools```

**Comment by herrjemand** [comment]
Already done
