### ISSUE TITLE
[FIDO2] Unexpected test case of non-display authenticator

### ISSUE THREAD

**Issue by baulhoa** [fido-alliance/conformance-tools-issues#514]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?

v1.1.5

## What is the OS and the version are you running?

MacOS

## Issue description

The test case for non-display proceeded even I select display authenticator
<img width="1439" alt="Screen Shot 2019-09-20 at 4 35 08 PM" src="https://user-images.githubusercontent.com/9248863/65313296-b8af1400-dbc6-11e9-859e-ddae491194c7.png">

**Comment by herrjemand** [comment]
The credential counter should be set to the number of credentials(3) and not to the number of credentials left to fetch(2)

**Comment by baulhoa** [comment]
We are not testing non-display authenticator. Isn't the case P-3 supposed to be executed?
