### ISSUE TITLE
[FIDO2] Can NOT detect fido authenticator

### ISSUE THREAD

**Issue by DaoThanhLong** [fido-alliance/conformance-tools-issues#515]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.1.0/1.1.4/1.1.6

## What is the OS and the version are you running?
Windows 10 Home - build 18326

## Issue description
Fido conformance tool can't dectect fido2 authenticator
![image](https://user-images.githubusercontent.com/30427088/65580064-2bdbd000-dfa3-11e9-8a55-771900c81aa3.png)

**Comment by herrjemand** [comment]
@DaoThanhLong Run tools as administrator. MSFT restricts FIDO authenticators only to priviledged processes.
