### ISSUE TITLE
Why do I have to register in order to see the test vectors?

### ISSUE THREAD

**Issue by MicahZoltu** [fido-alliance/conformance-tools-issues#517]
## Issue description

I'm trying to help debug an issue with a product that is using FIDO2 and part of that process requires me to look at the test vectors to see if the issue is with a missing test vector, or an incorrect test vector (against spec).  However, when I went looking for the standard FIDO/FIDO2 test vectors I found that they are behind a registration wall.  There is no indication _why_ I need to register and in this day and age hiding _test vectors for a public specification_ doesn't make any sense to me.

Can someone explain _WHY_ I have to register in order to _see_ the test vectors?  I am not building a product that needs to get FIDO certified, I'm just trying to be helpful and am quite annoyed that I cannot help because of this.

**Comment by herrjemand** [comment]
@MicahZoltu The registration is free. We only collect registration for usage tracking. We do not sell nor share this information to anyone else.

**Comment by MicahZoltu** [comment]
If it is just anonymous usage tracking, then why do I have to wait 24 hours for "approval"?  This suggests to me that a human _is_ looking at my personally identifiable information (name/email) and it isn't just a computer doing anonymous usage tracking.
