### ISSUE TITLE
[BLE] ERROR CONNECTING TO BLE API. MAYBE YOU ARE RUNNING WIN7.

### ISSUE THREAD

**Issue by yrevyakin** [fido-alliance/conformance-tools-issues#519]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.1.6

## What is the OS and the version are you running?

Win10 EE, 1903, build 18362.387

## Issue description

The tool say that: 
[BLE] ERROR CONNECTING TO BLE API. MAYBE YOU ARE RUNNING WIN7.

The issues history mentions that the equal behavior (FIDO2 BLE Test Error #503) was fixed but it looks like it wasn't

**Comment by herrjemand** [comment]
v1.2.0 will finaly fix that

**Comment by Chellapandi** [comment]
This issue still exists in 1.2.0 in macOS Catalina. Have a look at it.

**Comment by yrevyakin** [comment]
This issue still exists in 1.2.0 in Windows. All right on Mac where it was installed for very first time. 
Is there any cache or another kind of trail?

**Comment by snakeye** [comment]
I have the same issue on Mac OS X Catalina running v1.3.2 of the tools
