### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-B Test server processing "android-safetynet" attestation

### ISSUE THREAD

**Issue by tlsm** [fido-alliance/conformance-tools-issues#520]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.1.6

## What is the OS and the version are you running?

Windows 10

## Issue description

Server-ServerAuthenticatorAttestationResponse-Resp-B Test server processing "android-safetynet" attestation

"Authority Key Identifier" of the attestation certificate with CN="C=US, O=FIDO Alliances FAKE Trust Services, CN=FIDO Alliances FAKE Internet Authority F1" is 

5C:5B:90:B8:0E:7E:81:E7:AD:E3:9D:4D:A7:09:3A:93:62:9B:9F:28

"Subject Key Identifier" of both certificates with CN="C=US, O=FIDO Alliance, CN=FIDO Alliances FAKE Root CA - S1" in the metadata of Android SafetyNet is
 
C2:14:AA:36:FF:41:69:D2:9D:8A:3B:D8:1C:65:D3:5B:DE:6B:70:2D:94:90

Mismatch between the two key identifiers had resulted failure in the relevant test case mentioned above.

**Comment by herrjemand** [comment]
dublicate of #514
