### ISSUE TITLE
PING test case is  getting TIMEOUT

### ISSUE THREAD

**Issue by saravnandm** [fido-alliance/conformance-tools-issues#521]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.1.6

## What is the OS and the version are you running?
running the tool in MAC and want to test with iOS authr

## Issue description
I'm implementing a fido2 BLE authenticator Whenever I ran the fido-conformance-tool PING test case is getting a timeout. Later I found that PING cmd is received before 'fido-Status' characteristic is subscribed. As per the specification 'fido-Status' (notify) should be subscribed first then only we can respond to any cmd's. 

Even adding a delay was not working. Is there a way to fix this issue? PFA screenshot.

![Screenshot 2019-10-09 at 2 54 23 PM](https://user-images.githubusercontent.com/8371681/66469508-94e43d00-eaa5-11e9-80a5-e37d2bc031bb.png)

**Comment by herrjemand** [comment]
Seems like your authenticator did not respond to ping command @saravnandm

**Comment by saravnandm** [comment]
Hi @herrjemand 
My authenticator will send a response only when the fidStatus characteristic is subscribed.  fidoStatus is the option to send any data to the client, always use to check this before sending any data. Any idea why it is not subscribing before PING?

**Comment by herrjemand** [comment]
@saravnandm you authenticator should not wait for that.

**Comment by saravnandm** [comment]
@herrjemand fidoStatus characteristic(notify channel) is the way to send data to the client. If that way is not opened or closed, how do I send it? 

fidoStatus is getting subscribed exactly after 10 sec from the ping request. Even I tried sending the ping response immediately after subscription but still getting TIMEOUT.

**Comment by herrjemand** [comment]
@saravnandm Sorry I got confused. Yes, the tools is subscribing and then it send PING.
<img width="440" alt="Screenshot 2019-10-16 17 37 15" src="https://user-images.githubusercontent.com/1636116/66924394-9d0b2200-f03b-11e9-92ec-6e171f241da2.png">

Is that what you get in console?

**Comment by saravnandm** [comment]
Yes. But in my case its not subscribing properly. I'm testing it in MAC 10.14.6 Mojave. May I know your OS and version details?

**Comment by herrjemand** [comment]
@saravnandm Same. 10.14.6. I am testing with other authenticators and it works for me. I can see that in your console you get subscription before the ping. I am a little bit confused about the issue.

**Comment by herrjemand** [comment]
@Chellapandi  @saravnandm Are you making hardware authenticator or software?

**Comment by Chellapandi** [comment]
@herrjemand I am making software authenticator for Android platform. I just analysed the issue. 

When I select test (any test) at first, it fails. Other test cases are working fine. For example, If I check **Transport**, Generic, MakeCredential request, etc., from Conformance tool test cases, **Transport** test case fails( first selection). If I check **MakeCredential request**,Transport, Generic, MakeCredential response, etc., from Conformance tool test cases, **MakeCredential request** test case fails( first selection).

**Comment by herrjemand** [comment]
@Chellapandi You mean that if you select all, you get different result?

BTW: If you guys comfortable emailing me your authenticator, email conformance-tools@fidoalliance.org
