### ISSUE TITLE
The HID device is not listed in the authenticators.

### ISSUE THREAD

**Issue by konacert** [fido-alliance/conformance-tools-issues#522]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing? 
FIDO2 v1.2

## What is your implementation class?
Authenticator

## What is the version of the tool are you using?
v1.2.0

## What is the OS and the version are you running?
Windows10 1903

## Issue description
The conformance tool cannot recognize the HID device after updating windows 10 OS to 1903.
In the FIDO Authenticators entry shows the '[BLE] ERROR CONNECTING TO BLE API. MAYBE YOU ARE RUNNING WIN7'. 
When I try to test with NFC, the tool can recognize the NFC reader. But the HID can't. 
And I checked the 'Device Manager' too. I can find the HID device.
And I tried  to install and uninstall the conformance tool several times, but cannot solve this problem.
I was wondering if this can be solved.
Thank you.

**Comment by herrjemand** [comment]
@konacert Run tools as an admin
