### ISSUE TITLE
U2F HID-1 F-4: does not check for InvalidSeq with a CONT package

### ISSUE THREAD

**Issue by FabianHenneke** [fido-alliance/conformance-tools-issues#524]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F v1.1
## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.2.1

## What is the OS and the version are you running?

Windows 10
## Issue description

The U2F HID-1 F-4 test ("Send a valid CTAPHID_PING, with a a large payload size(1024 bytes), that has a continuation frame with a SEQ that is out of order") incorrectly sets the CMD byte of the packet that is supposed to be out of order to the CMD byte of the first packet + 1, which makes the packet an INIT instead of a CONT packet. As a result, the conformance tool expects an InvalidSeq error where an InvalidCmd error would be correct.

The line in the code that is the root cause of this issue:
```
pingFrames[pingFrames.length - 1].set([pingFrames[0][4] + 1], 4)
```
should e.g. become
```
pingFrames[pingFrames.length - 1].set([pingFrames[1][4] + 1], 4)
```

**Comment by herrjemand** [comment]
Thanks @FabianHenneke
