### ISSUE TITLE
FIDO2 Options Resident-Key P-3: Incorrect preconditions

### ISSUE THREAD

**Issue by FabianHenneke** [fido-alliance/conformance-tools-issues#526]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.3.0

## What is the OS and the version are you running?

Windows 10

## Issue description

The FIDO2 Options Resident-Key P-3 test is labelled as "FOR AUTHENTICATORS WITHOUT A DISPLAY AND EITHER UV IS TRUE OR CLIENTPIN IS USED", but the test uses the following precondition check:

```
if(authenticatorWithDisplay && !(supportsClientPin1 || supportedOptions.uv))
    this.skip()
```

If the authenticator has a display and e.g. supports UV, the check above will not lead to the test being skipped. The correct conditional would be:

```
if(authenticatorWithDisplay || !(supportsClientPin1 || supportedOptions.uv))
    this.skip()
```

**Comment by herrjemand** [comment]
Fixed in the new version.

Sorry for the delay
