### ISSUE TITLE
FIDO2 Options Resident-Key P-3: Incorrect scenario description

### ISSUE THREAD

**Issue by FabianHenneke** [fido-alliance/conformance-tools-issues#527]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Authr

## What is the version of the tool are you using?

1.3.0

## What is the OS and the version are you running?

Windows 10

## Issue description

The test description of the FIDO2 Options Resident-Key P-3 test states that `uv` is set to `false` in the `authenticatorMakeCredential` message, when in fact it is set to `true`:

```
        if(supportedOptions.uv)
            options.uv = true
```

**Comment by herrjemand** [comment]
Good catch @FabianHenneke !
