### ISSUE TITLE
ServerAuthenticatorAttestationResponse-Resp-A P1 android-key attestation trust path

### ISSUE THREAD

**Issue by padulafacundo** [fido-alliance/conformance-tools-issues#529]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.2.1

## What is the OS and the version are you running?
macOS 10.15

## Issue description

On ServerAuthenticatorAttestationResponse-Resp-A Test server processing "android-key" attestation P-1:

The attestation trust path contains an intermediate CA certificate signed by the one of the root certificates in the metadata. However, the root certificate also has a path length basic constraint equal to 0, so it can only issue end-entity certificates. This leads to a failed trust path validation.
In addition, the intermediate certificate's issuer and the root certificate have different Organizational Unit values.

I tried verifying the turst path using the root certificate of an[ older ](https://github.com/fido-alliance/conformance-tools-issues/issues/489) conformance tools version and it worked fine (doesn't have a path length constraint and the OU matches the one of the intermediate certificate issuer).

Some info:
`AAGUID` of authenticator: 550e4b54-aa47-409f-9a95-1ab76c130131

`subjectKeyIdentifier` of root certificate in metadata: 52:9A:1B:32:E0:56:AA:CD:51:0F:EF:5F:80:37:06:8B:F2:91:23:1D
`subjectKeyIdentifier` of intermediate CA certificate: A3:D2:AA:2C:EF:0D:8C:F2:24:02:D5:1C:B4:60:BC:BF:6A:5B:24:14

`OU` fields of root certificate in metadata: _CWG_
`OU` fields of intermediate CA certificate: _Authenticator Attestation_

**Comment by herrjemand** [comment]
Updated to 1.3

Yuriy Ackermann
FIDO, Identity, Standards
skype: ackermann.yuriy
github: @herrjemand <https://github.com/herrjemand>
twitter: @herrjemand <https://twitter.com/herrjemand>
medium: @herrjemand <https://medium.com/@herrjemand>

**Comment by padulafacundo** [comment]
Didn't notice the new version 😅
Issue still persists on v1.3, though.

**Comment by herrjemand** [comment]
@padulafacundo did you re-download the metadata?

**Comment by padulafacundo** [comment]
The problem wasn't with the metadata itself but with the way I was reading it. 
Root certificates for authenticators with aaguid `80f53d1e-852e-43ed-bb3f-d02f1322e5af` and `550e4b54-aa47-409f-9a95-1ab76c130131` are identical (same public key, subject identifier, etc) save for `OU` and path length extension. This led to using one instead of the other.
Thanks!

**Comment by herrjemand** [comment]
@padulafacundo ay ay!
