### ISSUE TITLE
Receiving "Before all" hooks on 3 tests

### ISSUE THREAD

**Issue by xjrosasx** [fido-alliance/conformance-tools-issues#533]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF/v1.0/v1.1

## What is your implementation class?

Client

## What is the version of the tool are you using?

v1.4.4
## What is the OS and the version are you running?

android and ios
## Issue description

receiving the same errors on both platforms for 3 tests. screenshots attached.
![Screenshot_20191121-075213](https://user-images.githubusercontent.com/5342760/69369852-a0548780-0c51-11ea-803e-0a5663ecdd03.png)
![Screenshot_20191121-075236](https://user-images.githubusercontent.com/5342760/69369853-a0548780-0c51-11ea-96fa-0faecf89c6ea.png)
![Screenshot_20191121-075250](https://user-images.githubusercontent.com/5342760/69369855-a0548780-0c51-11ea-934e-c639ebe48c80.png)

**Comment by xjrosasx** [comment]
The example shown is for UAF1.1 but it is reproducible for 1.1 and 1.0

**Comment by herrjemand** [comment]
@xjrosasx Fixed now. *) Servers been down for some reason
