### ISSUE TITLE
TPM subjectAlternativeName uses fake manufacturer ID

### ISSUE THREAD

**Issue by bdewater** [fido-alliance/conformance-tools-issues#537]
## What protocol and version of the protocol are you testing?
FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?
1.3.2

## What is the OS and the version are you running?
macOS 10.15.2 Catalina

## Issue description

This is related to https://github.com/fido-alliance/conformance-tools-issues/issues/505

When properly implementing the above per the TCG specs, the conformance tests fail because of the fake identifier (`id:FFFFF1D0`) used in the subjectAlternativeName. From the top of my head the rest of the conformance authenticator data pretends to be a Surface tablet (or at least it looked very similar to it).

I'm not sure why the manufacturer ID would need to be fake here - the fact the cert isn't signed by one of the approved TCG roots should be enough of an indicator that it's not real. From my point of view this only makes it frustrating to implement the SAN check by having to add special code paths solely for conformance testing.

**Comment by herrjemand** [comment]
@bdewater we only use fake id:FFFFF1D0. I mean how would conformance tools otherwise do that?

**Comment by bdewater** [comment]
That the tools use `id:FFFFF1D0` is exactly why I opened this issue. Can this be re-opened please?

From #505:

> Per https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf section 3.2.9:
> > This contains the alternative name of the entity associated with this certificate. The issuer MUST include TPM manufacturer, TPM part number and TPM firmware version, using the directoryNameform within the GeneralName structure. The ASN.1 encoding is specified in section 3.1.2 TPM Device Attributes. In accordance with [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.6), this extension MUST be critical if subject is empty and SHOULD be non-critical if subject is non-empty.
> > - The TPM manufacturer identifies the manufacturer of the TPM. This value MUST be the
vendor ID defined in the [TCG Vendor ID Registry](https://trustedcomputinggroup.org/resource/vendor-id-registry/). It MUST match the value reported by the command TPM2_GetCapability(property = TPM_PT_MANUFACTURER).

`id:FFFFF1D0` is not on the TCG Vendor ID Registry. If the conformance tools would use one of the IDs that is on the TCG list, like `id:57454300`, I would not have to code an exception in my TPM validation path that's only there to please the tools.

**Comment by herrjemand** [comment]
I think using a valid TPM identifier would be even worse idea. You could
just add test id to your config temporary and then delete it?

Yuriy Ackermann
FIDO, Identity, Standards
skype: ackermann.yuriy
github: @herrjemand <https://github.com/herrjemand>
twitter: @herrjemand <https://twitter.com/herrjemand>
medium: @herrjemand <https://medium.com/@herrjemand>

**Comment by bdewater** [comment]
Can you elaborate why that would be even worse? TCG specs are clear that a vendor ID 'MUST' be on the TCG registry, `id:FFFFF1D0` makes the TPM certs from the tool non-conformant. Isn't the point of the tool to generate conformant data (for the 'everything is correct' test cases), but signed by fake certificates?

If it's concerns about claiming 'real looking data'... the certs from the tool do that already:
- Android Safetynet: claims [`"ctsProfileMatch": true`](https://developer.android.com/training/safetynet/attestation#use-response-server)
- Android Key: the TEE AuthorizationList claims the [Origin is 'generated'](https://source.android.com/security/keystore/tags#origin) (while the Software AuthorizationList Origin is undefined)

I don't see why using a TPM manufacturer ID from the registry would be any different.

Yes we can work around it ([already do](https://github.com/cedarcode/webauthn-ruby/blob/e01cf4d2a4c776530c36e5a68027873b889ec3fa/spec/conformance/conformance_patches.rb)) it but TPM is the _only_ format we need to do this for. Every other format only need to rely on a strategy pattern for finding root certificates (given an attestation format, AAGUID or subjectKeyIdentifier)

**Comment by bdewater** [comment]
Also, assuming https://github.com/fido-alliance/conformance-tools-issues/issues/505 is still of interested to be implemented, how would you go about that if you're already using a fake identifier?

**Comment by tanguilp** [comment]
Agree, would be nice not to have a different code path for testing, especially because test server and FIDO2 libraries can be distinct.
