### ISSUE TITLE
Metadata in ServerAuthenticatorAttestationResponse-Resp-6 F-2

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-tools-issues#539]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.3.2

## What is the OS and the version are you running?

Windows 10

## Issue description

Test `Server-ServerAuthenticatorAttestationResponse-Resp-6 Test server processing "packed" SELF(SURROGATE) attestation`, `F-2 Send ServerAuthenticatorAttestationResponse with SELF "packed" attestation, that contains full attestation, and check that server returns an error` checks if the server looks at the `attestationTypes` list in the metadata. The actual attestation type used is Basic (15879)

The authenticator used has a key identifier of `564df7c0f8c655b6a11f6c4d19f3bf41e2fd0179` and an AAGUID of `2b2ecbb4-59b4-44fa-868d-a072485d8ae0`. Both have different metadata files:

**Att key ID 564df7c0f8c655b6a11f6c4d19f3bf41e2fd0179 (A)**
Virtual Secp256K1 FIDO2 Conformance Testing U2F Authenticator.json
attestationTypes: [15879] // Basic auth 

**AAGUID 2b2ecbb4-59b4-44fa-868d-a072485d8ae0 (B)**
Virtual Secp256R1 FIDO2 Conformance Testing CTAP2 Authenticator with Self(surrogate) attestation.json
attestationTypes: [15880] // Self

I am not sure if I'm missing some specific matching for the metadata or whether the test is incorrect.

If matching is done on AAGUID first, metadata B will match, attestationType does not include the type used, an error is returned an the test succeeds. However if the attestation key is looked up first, metadata A will match and the attestation type is allowed, no error is returned and the test failed. 

However, if attestationTypes is seen as a matching criteria rather than a property of the metadata, only metadata A can match. This will fail the test though, since there is a valid metadata. In UAF metadata the specs explicitly state that *all* matching criteria (in `MatchCriteria`) should match. The FIDO2 metadata specs are unclear on this.

- Is attestationTypes (and any other fields for that matter) meant to be used as matching criteria for the metadata or only as a subsequent check after a metadata hit has been found? 
- Is there any priority to use AAGUID or attestation key IDs to match metadata? Or should we assume there is only one match and is the test metadata wrong?
- Is the check for attestationTypes specified anywhere in the specs? It is not part of WebAuthn but I can't find it in any other spec either.

**Comment by herrjemand** [comment]
@madwizard-thomas Matching ALWAYS have to be done with AAGUID. SKID is ONLY applicable for U2F.

**Comment by madwizard-thomas** [comment]
Can you refer to any specification that confirms this? I'd be happy to implement this correctly but I would like to have it backed up by official specification as the correct behavior.

The FIDO metadata 1.1/2.0 specs 3.1.7 say:

> 7. Iterate through the individual entries (of type MetadataTOCPayloadEntry). For each entry:
> "Ignore the entry if the AAID, AAGUID or attestationCertificateKeyIdentifiers is not relevant to the relying party (e.g. not acceptable by any policy)"
> 

The attestationCertificateKeyIdentifier seems relevant in this case. The specs do not say: if an authenticator has an AAGUID, ignore its attestationCertificateKeyIdentifier. 

Again, I'm perfectly fine with implementing this correctly but I cannot find any official documentation how I should implement this, but currently I have only your response to go on.  The FIDO2 server requirements specification does not even contain the phrase 'aaguid' and already contradicts the w3c webauthn specification in some regards (like silent authentication) so it is a bit of a mess to find the right behavior to pass the conformance tests.

**Comment by herrjemand** [comment]
@madwizard-thomas You decode the attestation. You looks at is fido-u2f or something else. If it is fido-u2f you do SKID. If it's not, then you do AAGUID.

Read that https://w3c.github.io/webauthn/#sctn-registering-a-new-credential

And this https://medium.com/@herrjemand/verifying-fido2-responses-4691288c8770
