### ISSUE TITLE
SCardTransmit error while performing Authenticator tests

### ISSUE THREAD

**Issue by tsenger** [fido-alliance/conformance-tools-issues#540]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

U2F v1.1

## What is your implementation class?

Authr

## What is the version of the tool are you using?
v1.3.2

## What is the OS and the version are you running?
Windows 10 Pro 1903

## Issue description
Testing a connteactless U2F JavaCard Applet connected via a "ReinerSCT cyberjack RFID basic" reader resolv in the following error message when performing test case 

> NFC-1 Test U2F NFC support
> P-1 Send FIDO applet selection command and check that authenticator succeeds. For CTAP1(U2F) compatible authenticators check that authenticator returns 0x5532465F5632(U2F_V2) in response.

```
Error: the object {
  "errorMessage": "Error while sending buffer: Error: SCardTransmit error: Der Zugriff auf die Datei wurde verweigert.\r\n(0x80100027)"
  "statusCode": 28416
  "statusCodeDef": "SW_UNKNOWN"
} was thrown, throw an Error :)
    at h.fail (js/vendor/mocha.min.js:1:43543)
    at file:///C:/Users/tobi/AppData/Local/F/app-1.3.2/resources/app/app/js/vendor/mocha.min.js:1:46426
    at u (js/vendor/mocha.min.js:1:39333)
    at file:///C:/Users/tobi/AppData/Local/F/app-1.3.2/resources/app/app/js/vendor/mocha.min.js:1:39862
    at <anonymous>
```

Seems there is a restriction in access the smartcard reader.

**Comment by herrjemand** [comment]
@tsenger Try running as Administrator

**Comment by tsenger** [comment]
works!
