### ISSUE TITLE
Conflicting MDS and metadata.zip

### ISSUE THREAD

**Issue by madwizard-thomas** [fido-alliance/conformance-tools-issues#542]
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.3.2

## What is the OS and the version are you running?

Windows 10

## Issue description

There is both the test MDS service and the metadata.zip file that can be downloaded from the tool. Both seem needed at the same time to pass all tests. For the metadata tests (Server-ServerAuthenticatorAttestationResponse-Resp-1) this leads to several tests succeeding that should fail.

For F-1, F-3, F-4, F-5 and F-6 the following AAGUIDs are used. The ones marked MDS are actually in the metadata service but all deliberately have issues so they should fail.
```
F-1 	27ea7797-07e5-44b2-acdb-c398b732a6fc	MDS 
F-3 	1315faa3-036e-46d6-84e1-edb82a5de582     
F-4	3375db42-46e3-486f-88ba-ddc8a05a94a6	MDS
F-5	7bff65b9-cd5b-42bb-ae5f-0b891cd4a1b2	MDS	
F-6	722bac59-d965-4358-90b6-04f0d4354676	MDS	
```
These tests pass fine as long as I only use the test MDS. If I add the metadata.zip into the mix the tests will fail (successful responses). Because all of the above authenticators all use a certificate key identifier of `564df7c0f8c655b6a11f6c4d19f3bf41e2fd0179` and this key is in `Virtual Secp256K1 FIDO2 Conformance Testing U2F Authenticator.json`, the server will fall back on this valid metadata after MDS fails to return any metadata. I cannot only use MDS because then other tests will fail.

**Comment by scottbrady91** [comment]
Good find. We are currently being affected by this same issue.

**Comment by herrjemand** [comment]
@madwizard-thomas The SKID is only used in U2F attestation. FIDO2 is explicitly using aaguid. Don't mix those up
