### ISSUE TITLE
the wrong asn1 structure of MDSROOT.crl

### ISSUE THREAD

**Issue by MingHaoChiang** [fido-alliance/conformance-tools-issues#543]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Server

## What is the version of the tool are you using?

fido-conformance-tools-electron v1.3.2

## What is the OS and the version are you running?

MacOS 10.15.2

## Issue description

The cRLDistributionPoints in https://fidoalliance.co.nz/mds/pki/MDSROOT.crt is [https://fidoalliance.co.nz/mds/crl/MDSROOT.crl] ， the content in MDSROOT.crl start line is "-----BEGIN CERTIFICATE-----"  and  end line is "-----END CERTIFICATE-----" ，isn't it should be start with "-----BEGIN X509 CRL-----" and end with "-----END X509 CRL-----"?

**Comment by herrjemand** [comment]
Duh. Thanks @MingHaoChiang!

**Comment by herrjemand** [comment]
@MingHaoChiang Fixed. Try again!
