### ISSUE TITLE
Is it mandatory to pass fido2 conformance tool testcases for software authenticators?

### ISSUE THREAD

**Issue by saravnandm** [fido-alliance/conformance-tools-issues#548]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2 v1.2

## What is your implementation class?

ASM+Authr

## What is the version of the tool are you using?
1.3.4

## What is the OS and the version are you running?
iOS & Android

## Issue description
There are many issues in fido-conformance-tool to test the BLE fido2 authenticator in both iOS and Android. It's an even more painful job to pass the test case compared to development. As I have noticed the BLE connectivity, TIMEOUT, etc issues are still there from version 1.1.5 to the latest 1.3.4.

As far as I know, the tool works well with the server. Have the following questions, 
1. Is it really mandatory to pass the conformance tool test cases to get certification for software authenticators?  
2. If so why didn't the team is not solving any of these issues? 
3. Is there any documentation regarding the conformance tool test cases to test authenticators?

**Comment by herrjemand** [comment]
@saravnandm 

1. Yes.
2. Provide us with the issue that you are experiencing
3. Need to write it *)
