### ISSUE TITLE
UI : unrelated pending

### ISSUE THREAD

**Issue by antonio-fr** [fido-alliance/conformance-tools-issues#550]
## What protocol and version of the protocol are you testing?
FIDO2 Tests (at least)

## What is the version of the tool are you using?
v1.3.4

## What is the OS and the version are you running?
Windows 10

## Issue description
When the mouse cursor is hoovering a skipped tested, written in blue, the app adds _(pending)_ to the test description displayed.

**Comment by herrjemand** [comment]
@antonio-fr Means that tests was skipped.
