### ISSUE TITLE
Conformance test tool open via command line

### ISSUE THREAD

**Issue by apthilaga** [fido-alliance/conformance-tools-issues#555]
## What protocol and version of the protocol are you testing?

FIDO2 2.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
v1.3.4

## What is the OS and the version are you running?
windows 10, 64 bit

## Issue description
May I know if the conformance test tool be opened using command line?
-	If yes, could you please give additional information?
-	If no, could you please tell if any plans to implement this option?

I don’t find more details about command line in the FIDO Conformance Tools instructions.pdf document.

**Comment by herrjemand** [comment]
Dublicate of #506 

No plans yet. One day
